// .old_project /packages/cyoda-ui-lib/src/components-library/elements/Home/Home.vue
<template>
  <div class="wrap-home">
    <HomeMenuDisplay v-for="menu in menus" :key="menu.link" :menu="menu" />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

import Menu from "./Menu";
import HomeMenuDisplay from "./HomeMenuDisplay.vue";

let menus = ref(Menu);
</script>

<style lang="scss">
.wrap-home {
  width: 800px;
  margin: 40px auto 0;
}
</style>

// packages/ui-lib-react/src/components/Home/Home.tsx
import React from 'react'
import { HomeMenuDisplay } from './HomeMenuDisplay'
import { defaultMenuItems, type MenuItem } from './types'
import './Home.scss'

export interface HomeProps {
  menus?: MenuItem[]
}

/**
 * Home Component
 * Main home page with menu items
 * 
 * Migrated from Vue: .old_project/packages/cyoda-ui-lib/src/components-library/elements/Home/Home.vue
 */
export const Home: React.FC<HomeProps> = ({
  menus = defaultMenuItems
}) => {
  return (
    <div className="wrap-home">
      {menus.map((menu, index) => (
        <HomeMenuDisplay 
          key={menu.link || `${menu.name}-${index}`} 
          menu={menu} 
        />
      ))}
    </div>
  )
}
