// .old_project /packages/cyoda-ui-lib/src/components-library/elements/Home/HomeMenuDisplay.vue
<template>
  <div class="home-menu-display">
    <template v-if="menu.name === 'delimiter'">
      <hr />
    </template>
    <template v-else>
      <el-row :gutter="20">
        <el-col
          :class="{
            'text-center': !isDisplayDescription
          }"
          :span="isDisplayDescription ? 12 : 24"
        >
          <template v-if="menu.isRouterLink">
            <router-link class="cyoda-btn" :to="menu.link">{{ menu.name }}</router-link>
          </template>
          <template v-else>
            <el-button type="success" class="cyoda-btn" @click="onClick(menu)">{{ menu.name }}</el-button>
          </template>
        </el-col>
        <el-col v-if="isDisplayDescription" :span="12">
          {{ menu.description }}
        </el-col>
      </el-row>
    </template>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  menu: {
    default: () => {
      return {};
    }
  },
  isDisplayDescription: {
    default: true
  }
});

function onClick(menu: any) {
  window.open(getLink(menu), "_blank");
}

function getLink(menu: any) {
  if (window.location.href.indexOf("localhost") > -1 && menu.hasOwnProperty("localhostLink")) {
    return menu.localhostLink;
  } else {
    let url = `${location.protocol}//${location.hostname}`;
    if (location.port) {
      url += `:${location.port}`;
    }
    return `${url}${menu.link}`;
  }
}

function checkIsPM(menu: any) {
  if (menu.name === "System Monitor" && location.href.indexOf("processing-manager") === -1) {
    return false;
  }
  return true;
}
</script>

<style lang="scss">
.home-menu-display {
  .el-row {
    margin-bottom: 15px;

    .text-center {
      text-align: center;
    }

    .cyoda-btn {
      background-color: #148751;
      border-color: #148751;
      width: 300px;
      color: #fff;
      padding: 12px 20px;
      font-size: 14px;
      border-radius: 4px;
      text-align: center;
      display: block;
      text-decoration: none;

      &:after {
        display: none;
      }

      &:hover {
        background-color: #149c66;
        border-color: #149c66;
      }
    }
  }

  hr {
    box-shadow: none;
    display: block;
    height: 0;
    border: 0;
    border-top: 2px solid rgb(232, 232, 232);
    margin: 1em 0;
    padding: 0;
  }
}
</style>

// react-project/packages/ui-lib-react/src/components/Home/HomeMenuDisplay.tsx
import React from 'react'
import { Link } from 'react-router-dom'
import { Button, Row, Col } from 'antd'
import type { MenuItem } from './types'
import './HomeMenuDisplay.scss'

export interface HomeMenuDisplayProps {
  menu: MenuItem
  isDisplayDescription?: boolean
}

/**
 * HomeMenuDisplay Component
 * Displays a single menu item with optional description
 * 
 * Migrated from Vue: .old_project/packages/cyoda-ui-lib/src/components-library/elements/Home/HomeMenuDisplay.vue
 */
export const HomeMenuDisplay: React.FC<HomeMenuDisplayProps> = ({
  menu,
  isDisplayDescription = true
}) => {
  const getLink = (menu: MenuItem): string => {
    if (window.location.href.indexOf('localhost') > -1 && menu.localhostLink) {
      return menu.localhostLink
    } else {
      let url = `${location.protocol}//${location.hostname}`
      if (location.port) {
        url += `:${location.port}`
      }
      return `${url}${menu.link}`
    }
  }

  const handleClick = (menu: MenuItem) => {
    window.open(getLink(menu), '_blank')
  }

  // Render delimiter
  if (menu.name === 'delimiter') {
    return (
      <div className="home-menu-display">
        <hr />
      </div>
    )
  }

  return (
    <div className="home-menu-display">
      <Row gutter={20}>
        <Col
          span={isDisplayDescription ? 12 : 24}
          className={!isDisplayDescription ? 'text-center' : ''}
        >
          {menu.isRouterLink && menu.link ? (
            <Link className="cyoda-btn" to={menu.link}>
              {menu.name}
            </Link>
          ) : (
            <Button
              type="primary"
              className="cyoda-btn"
              onClick={() => handleClick(menu)}
              block
            >
              {menu.name}
            </Button>
          )}
        </Col>
        {isDisplayDescription && menu.description && (
          <Col span={12}>
            {menu.description}
          </Col>
        )}
      </Row>
    </div>
  )
}
