// react-project/packages/cobi-react/src/components/DataMapper/MetaParams.tsx
import React from 'react';
import MetaParamsRow from './MetaParamsRow';
import type { EntityMappingConfigDto } from '../../types';
import './MetaParams.css';

interface MetaParam {
  name: string;
  displayName: string;
  type?: string;
}

interface MetaParamsProps {
  metaParams: MetaParam[];
  allDataRelations: any[];
  selectedEntityMapping: EntityMappingConfigDto;
  onRelationsUpdate?: () => void;
}

const MetaParams: React.FC<MetaParamsProps> = ({
  metaParams,
  allDataRelations,
  selectedEntityMapping,
  onRelationsUpdate,
}) => {
  if (!metaParams || metaParams.length === 0) {
    return null;
  }

  return (
    <div className="meta-params">
      <h2>Meta Params</h2>
      {metaParams.map((metaParam) => (
        <MetaParamsRow
          key={metaParam.name}
          metaParam={metaParam}
          allDataRelations={allDataRelations}
          selectedEntityMapping={selectedEntityMapping}
          onRelationsUpdate={onRelationsUpdate}
        />
      ))}
    </div>
  );
};

export default MetaParams;

// .old_project /packages/cobi/src/components/DataMapper/MetaParams/MetaParams.vue
<template>
  <div class="meta-params">
    <h2>Meta Params</h2>
    <MetaParamsRow v-for="metaParam in metaParams" :key="metaParam.name" :metaParam="metaParam" :allDataRelations="allDataRelations":selectedEntityMapping="selectedEntityMapping"
    />
  </div>
</template>

<script setup lang="ts">
import MetaParamsRow from "./MetaParamsRow.vue";

const props = defineProps({
  metaParams: undefined,
  allDataRelations: undefined,
  selectedEntityMapping: {
    default: () => {
      return {};
    },
  }
});
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.meta-params {
  margin-top: 30px;
}
</style>
