// packages/cobi-react/src/components/DataMapper/MetaParamsRow.tsx
import React, { useState, useRef, useMemo } from 'react';
import { Popover, Button, Tooltip } from 'antd';
import { CodeOutlined } from '@ant-design/icons';
import type { EntityMappingConfigDto } from '../../types';
import './MetaParamsRow.css';

interface MetaParam {
  name: string;
  displayName: string;
  type?: string;
}

interface MetaParamsRowProps {
  metaParam: MetaParam;
  allDataRelations: any[];
  selectedEntityMapping: EntityMappingConfigDto;
  onRelationsUpdate?: () => void;
}

const MetaParamsRow: React.FC<MetaParamsRowProps> = ({
  metaParam,
  allDataRelations,
  selectedEntityMapping,
  onRelationsUpdate,
}) => {
  const [popoverVisible, setPopoverVisible] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);

  // Get current relations for this meta param
  const currentRelations = useMemo(() => {
    return allDataRelations.filter(
      (el) => el.column?.srcColumnPath === metaParam.name
    );
  }, [allDataRelations, metaParam.name]);

  const isSelected = currentRelations.length > 0;

  const allRelationClasses = useMemo(() => {
    return currentRelations.map((el) => encodeURIComponent(el.column?.srcColumnPath || ''));
  }, [currentRelations]);

  // Check if meta param exists in script input meta paths
  const isExistInMeta = useMemo(() => {
    return selectedEntityMapping.script?.inputMetaPaths?.includes(metaParam.name) || false;
  }, [selectedEntityMapping.script, metaParam.name]);

  const handleStartDragLine = (event: React.MouseEvent) => {
    event.preventDefault();
    setPopoverVisible(false);

    const circleEl = rootRef.current?.querySelector('.circle') as HTMLElement;
    if (circleEl) {
      // Trigger drag start event
      // This would integrate with your drag-drop handler
      const dragEvent = new CustomEvent('startDragLine', {
        detail: {
          el: circleEl,
          path: metaParam.name,
          jsonPath: metaParam.name,
          type: 'cobiCoreMetadata',
        },
      });
      document.dispatchEvent(dragEvent);
    }
  };

  const handleDeleteRelation = () => {
    if (currentRelations.length > 0) {
      setPopoverVisible(false);
      
      // Trigger delete relation event
      const deleteEvent = new CustomEvent('removeRelation', {
        detail: currentRelations,
      });
      document.dispatchEvent(deleteEvent);

      if (onRelationsUpdate) {
        onRelationsUpdate();
      }
    }
  };

  const handleToggleMeta = () => {
    if (!selectedEntityMapping.script) {
      selectedEntityMapping.script = { inputMetaPaths: [] };
    }
    if (!selectedEntityMapping.script.inputMetaPaths) {
      selectedEntityMapping.script.inputMetaPaths = [];
    }

    const inputMetaPaths = selectedEntityMapping.script.inputMetaPaths;
    
    if (isExistInMeta) {
      // Remove from meta paths
      const index = inputMetaPaths.indexOf(metaParam.name);
      if (index > -1) {
        inputMetaPaths.splice(index, 1);
      }
    } else {
      // Add to meta paths
      inputMetaPaths.push(metaParam.name);
    }

    if (onRelationsUpdate) {
      onRelationsUpdate();
    }
  };

  const popoverContent = (
    <div>
      <div className="action">
        <Button type="link" onClick={handleStartDragLine}>
          Add new
        </Button>
      </div>
      {allRelationClasses.length > 0 && (
        <div className="action">
          <Button type="link" danger onClick={handleDeleteRelation}>
            Delete
          </Button>
        </div>
      )}
    </div>
  );

  return (
    <div
      ref={rootRef}
      className="meta-params-row"
      data-relation={allRelationClasses.join(' ')}
    >
      <div className="key">
        <CodeOutlined
          className={`settings ${isExistInMeta ? 'success' : 'error'}`}
          onClick={handleToggleMeta}
          title={isExistInMeta ? 'Remove from script meta paths' : 'Add to script meta paths'}
        />
        <Tooltip title={metaParam.name} mouseEnterDelay={1}>
          <span>{metaParam.displayName}</span>
        </Tooltip>

        <Popover
          content={popoverContent}
          title="Actions"
          placement="topLeft"
          trigger="click"
          open={popoverVisible}
          onOpenChange={setPopoverVisible}
          overlayClassName="popover-actions"
        >
          <div
            className={`circle ${isSelected || popoverVisible ? 'selected' : ''} cobi-core-metadata`}
          >
            {allRelationClasses.length > 1 && allRelationClasses.length}
          </div>
        </Popover>
      </div>
    </div>
  );
};

export default MetaParamsRow;

// .old_project /packages/cobi/src/components/DataMapper/MetaParams/MetaParamsRow.vue
<template>
  <div ref="rootRef" class="row" :data-relation="allRelationClasses.join(' ')">
    <div class="key">
      <font-awesome-icon
        @click="onClickToMeta"
        :icon="['fab', 'js']"
        class="settings"
        :class="{
            error: !isExistInMeta,
            success: isExistInMeta
          }"
      />
      <el-tooltip :show-after="1000" effect="dark" :content="metaParam.name" placement="top">
        <span>{{ metaParam.displayName }}</span>
      </el-tooltip>

      <el-popover popper-class="popover-actions" placement="top-start" title="Actions" width="200" trigger="click" v-model:visible="visibleTooltip">
        <div>
          <div class="action">
          <el-button @click="onStartDragLine($event, 'cobiCoreMetadata')" type="primary" link>Add new</el-button>
          </div>
          <div class="action" v-if="allRelationClasses.length > 0">
            <el-button @click="onDeleteRelation" type="primary" link>Delete</el-button>
          </div>
        </div>
        <template #reference>
        <div
          class="circle"
          :class="{
            selected: isSelected || visibleTooltip,
            'cobi-core-metadata': true
          }"
        >
          <template v-if="allRelationClasses.length > 1">{{ allRelationClasses.value.length }}</template>
        </div>
        </template>
      </el-popover>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import eventBus from "@cyoda/ui-lib/src/plugins/eventBus";

const props = defineProps({
  metaParam: undefined,
  allDataRelations: undefined,
  selectedEntityMapping: {
    default: ()=> {
      return {};
    }
  }
});

const visibleTooltip = ref(false);

const rootRef=ref(null);

const allRelationClasses = computed(() => {
  return getAllSelectedRelations.value.map((el: any) => encodeURIComponent(el.column.srcColumnPath));
});
const isColumnMapping = computed(() => {
  return !!currentRelations.value.find((el) => el.type === "cobiCoreMetadata");
});
const currentRelations = computed(() => {
  return props.allDataRelations.filter((el) => el.column.srcColumnPath == props.metaParam.name);
});
const isSelected = computed(() => {
  return currentRelations.value && currentRelations.value.length > 0;
});
const getAllSelectedRelations = computed(() => {
  const relations: any[] = [];
  currentRelations.value.forEach((el: any) => {
    relations.push(el);
  });
  return relations;
});

function onStartDragLine(event: any, type) {
  visibleTooltip.value = false;
  eventBus.$emit("startDragLine", {
    el: rootRef.value.querySelector(".circle"),
    path: props.metaParam.name,
    jsonPath: props.metaParam.name,
    type
  });
}
function onDeleteRelation() {
  if (allRelationClasses.value.length > 0) {
    visibleTooltip.value = false;
    eventBus.$emit("removeRelation", getAllSelectedRelations.value);
  }
}

const isExistInMeta= computed(()=> {
  return props.selectedEntityMapping.script.inputMetaPaths.includes(props.metaParam.name);
})

function onClickToMeta() {
  const inputMetaPaths =props.selectedEntityMapping.script.inputMetaPaths
  if (isExistInMeta.value) {
    props.selectedEntityMapping.script.inputMetaPaths = inputMetaPaths.filter((el) => el !== props.metaParam.name);
  } else {
    inputMetaPaths.push(props.metaParam.name);
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.row {
  display: flex;
  padding: 10px 10px 10px 0px;
  border-top: 1px solid #dedede;
  align-items: center;
  transition: all 0.5s;
}

.row {
  position: relative;

  .circle {
    position: absolute;
    right: -17px;
    min-width: 17px;
    white-space: nowrap;
    height: 18px;
    border-radius: 0 10px 10px 0;
    top: 9px;
    opacity: 0;
    transition: all 0.5s;
    background-color: #858484;
    border: 2px solid #858484;
    font-size: 13px;
    text-align: center;
    line-height: 14px;

    &.selected {
      opacity: 1;
      cursor: pointer;
    }

    &.cobi-core-metadata {
      background-color: #409eff;
      border-color: #409eff;
    }
  }

  &.is-partial-match {
    .circle {
      border: 2px dotted #858484;
      background-color: #fff;
      opacity: 1;
    }
  }

  &:hover {
    .circle {
      opacity: 1;
    }
  }

  &.selectable .key span {
    font-weight: bold;
  }

  &.is-not-hovered .circle.selected {
    opacity: 0.2;
  }

  .settings {
    opacity: 0.6;
    cursor: pointer;
    transition: all 0.5s;
    margin-left: 10px;
    margin-right: 7px;

    &:hover {
      opacity: 1;
    }

    &.success {
      color: #67c23a;
    }

    &.error {
      color: #f56c6c;
    }
  }
}
</style>
