// packages/statemachine-react/src/components/CriteriaForm.tsx
/**
 * Criteria Form Component (Embedded)
 * Wrapper for Criteria page to be used in modals
 */

import React, { useEffect, useState, useMemo } from 'react';
import { Form, Input, Button, message, Space, Select, Alert, Tabs, Switch } from 'antd';
import {
  useCriteria,
  useCriteriacheckers,
  useCreateCriteria,
  useUpdateCriteria,
} from '../hooks/useStatemachine';
import { useStatemachineStore } from '../stores/statemachineStore';
import type { PersistedType, CriteriaForm as CriteriaFormType } from '../types';
import FilterBuilderGroup from './FilterBuilder/FilterBuilderGroup';
import HelperFilter, { type GroupCondition } from './FilterBuilder/HelperFilter';
import { ReportEditorTabModel, HelperReportDefinition } from '@cyoda/tableau-react';
import './CriteriaForm.scss';

const { TextArea } = Input;

/**
 * Extract all field paths from condition recursively
 * Excludes alias names from the result
 */
function extractFieldPathsFromCondition(conditions: any[], aliasNames: string[]): string[] {
  let colPaths: string[] = [];

  if (!conditions || !Array.isArray(conditions)) {
    return colPaths;
  }

  conditions.forEach((el) => {
    if ('conditions' in el && Array.isArray(el.conditions)) {
      // Recursively process nested groups
      colPaths = [...colPaths, ...extractFieldPathsFromCondition(el.conditions, aliasNames)];
    } else if (el.fieldName) {
      // Add fieldName if it's not an alias and not already added
      if (!aliasNames.includes(el.fieldName) && !colPaths.includes(el.fieldName)) {
        colPaths.push(el.fieldName);
      }
    }
  });

  return colPaths;
}

interface CriteriaFormProps {
  criteriaId?: string;
  entityClassName: string;
  persistedType: PersistedType;
  mode?: 'embedded' | 'standalone' | 'page';
  onSubmitted?: (params: { id?: string }) => void;
  onCancel?: () => void;
}

export const CriteriaForm: React.FC<CriteriaFormProps> = ({
  criteriaId = '',
  entityClassName,
  persistedType,
  mode = 'embedded',
  onSubmitted,
  onCancel,
}) => {
  const [form] = Form.useForm();
  const [criteriaParameters, setCriteriaParameters] = React.useState<any[]>([]);
  const [condition, setCondition] = useState<GroupCondition>(HelperFilter.getGroup());

  // Config definition for Fields tab (colDefs and aliasDefs)
  const [configDefinition, setConfigDefinition] = useState<any>({
    requestClass: entityClassName,
    colDefs: [],
    aliasDefs: [],
  });

  // Update requestClass when entityClassName changes
  useEffect(() => {
    setConfigDefinition((prev: any) => ({
      ...prev,
      requestClass: entityClassName,
    }));
  }, [entityClassName]);

  // Determine if criteria is coded (Developer Coded) or built-in UI
  // Based on condition @bean type - if it contains "ConfigurableUnaryCondition" it's coded
  const isCodeCriteria = useMemo(() => {
    return (
      condition &&
      condition['@bean'] &&
      condition['@bean'].indexOf('ConfigurableUnaryCondition') !== -1
    );
  }, [condition]);

  const isNew = !criteriaId || criteriaId === 'new';
  const isRuntime = persistedType === 'transient';

  // Build cols for FilterBuilder from configDefinition (colDefs + aliasDefs)
  const cols = useMemo(() => {
    console.log('CriteriaForm - configDefinition:', configDefinition);
    const builtCols = HelperReportDefinition.buildCols(configDefinition);
    console.log('CriteriaForm - built cols:', builtCols);
    return builtCols;
  }, [configDefinition]);

  // Queries
  const { data: criteria, isLoading: isLoadingCriteria } = useCriteria(
    persistedType,
    criteriaId || '',
    entityClassName,
    !isNew
  );
  const { data: criteriacheckers = [], isLoading: isLoadingCheckers } = useCriteriacheckers(entityClassName);
  
  // Mutations
  const createCriteriaMutation = useCreateCriteria();
  const updateCriteriaMutation = useUpdateCriteria();
  
  // Criteria checker options
  const checkerOptions = React.useMemo(() => {
    if (Array.isArray(criteriacheckers)) {
      return criteriacheckers.map((checker: any) => {
        // Handle both string and object formats
        if (typeof checker === 'string') {
          return {
            label: checker.split('.').pop() || checker,
            value: checker,
          };
        }
        // Object format with name property
        const fullName = checker.name || checker.value || checker;
        const shortName = fullName.split('.').pop() || fullName;
        return {
          label: shortName,
          value: fullName,
        };
      });
    }
    return [];
  }, [criteriacheckers]);

  // Get parameters for the selected criteria checker
  const getCriteriaCheckerParameters = React.useCallback((criteriaChecker: string) => {
    if (!criteriaChecker || !Array.isArray(criteriacheckers)) {
      return [];
    }

    const checker = criteriacheckers.find((item: any) => {
      if (typeof item === 'string') {
        return item === criteriaChecker;
      }
      return item.name === criteriaChecker || item.value === criteriaChecker;
    });

    if (checker && typeof checker === 'object' && Array.isArray(checker.parameters)) {
      return checker.parameters.map((p: any) => ({
        name: p.name,
        valueType: p.type,
        availableValues: p.availableValues,
        value: {
          '@type': p.type.charAt(0).toUpperCase() + p.type.slice(1).toLowerCase(),
          value: null,
        },
      }));
    }

    return [];
  }, [criteriacheckers]);

  // Watch for criteria checker changes and update parameters
  const selectedChecker = Form.useWatch('criteriaChecker', form);

  React.useEffect(() => {
    if (selectedChecker) {
      const newParams = getCriteriaCheckerParameters(selectedChecker);
      console.log('CriteriaForm - Checker changed, updating parameters:', {
        checker: selectedChecker,
        parameters: newParams,
      });

      // Only update parameters for new criteria or when checker changes
      if (isNew || (criteria && criteria.criteriaChecker !== selectedChecker)) {
        setCriteriaParameters(newParams);
      }
    }
  }, [selectedChecker, getCriteriaCheckerParameters, isNew, criteria]);

  // Initialize form when criteria data loads
  useEffect(() => {
    if (criteria) {
      const formValues: any = {
        name: criteria.name,
        description: criteria.description || '',
        criteriaChecker: criteria.criteriaChecker || '',
      };

      // Load condition for FilterBuilder
      if (criteria.condition) {
        // Check if it's a ConfigurableUnaryCondition (coded criteria) - keep as is
        const isCodedCondition = criteria.condition['@bean'] &&
          criteria.condition['@bean'].indexOf('ConfigurableUnaryCondition') !== -1;

        if (isCodedCondition) {
          // Keep coded condition as is
          setCondition(criteria.condition);
        } else if (criteria.condition.conditions && Array.isArray(criteria.condition.conditions)) {
          // It's already a GroupCondition
          setCondition(criteria.condition);
        } else {
          // Wrap single condition in a group
          const group = HelperFilter.getGroup();
          group.conditions = [criteria.condition];
          setCondition(group);
        }
      }

      // Load aliasDefs for Fields tab
      const aliasDefs = criteria.aliasDefs || [];
      setConfigDefinition((prev: any) => ({
        ...prev,
        aliasDefs,
      }));

      // Set parameters from loaded criteria
      if (criteria.parameters && Array.isArray(criteria.parameters)) {
        setCriteriaParameters(criteria.parameters);

        // Set parameter values in form
        criteria.parameters.forEach((param: any) => {
          formValues[`param_${param.name}`] = param.value?.value;
        });
      }

      form.setFieldsValue(formValues);
    }
  }, [criteria, form]);

  // Load colDefs from API when criteria is loaded
  // Extract field paths from condition and fetch column definitions
  useEffect(() => {
    if (!criteria || !criteria.condition || !criteria.condition.conditions) {
      return;
    }

    const loadColDefs = async () => {
      try {
        // Get alias names to exclude from colPaths
        const aliasNames = (criteria.aliasDefs || []).map((el: any) => el.name);

        // Extract all field paths from condition
        const colPaths = extractFieldPathsFromCondition(criteria.condition.conditions, aliasNames);

        if (colPaths.length > 0) {
          // Fetch column definitions from API
          const { data: colDefs } = await useStatemachineStore.getState().getCriteriaDefs({
            rootClass: entityClassName,
            colPaths,
          });

          // Update configDefinition with loaded colDefs
          setConfigDefinition((prev: any) => ({
            ...prev,
            colDefs: colDefs || [],
          }));
        }
      } catch (error) {
        console.error('Failed to load column definitions:', error);
      }
    };

    loadColDefs();
  }, [criteria, entityClassName]);

  // Handlers
  const handleSubmit = async () => {
    try {
      // Validate required fields
      await form.validateFields();

      // Validate condition (only for Built-in UI criteria)
      if (!isCodeCriteria && condition.conditions) {
        const isValid = HelperReportDefinition.validateConfigDefinition(condition.conditions);
        if (!isValid) {
          message.error('Please fill all filter conditions');
          return;
        }
      }

      // Get all form values
      const values = form.getFieldsValue(true);

      // Process parameters - convert integer values
      const processedParameters = criteriaParameters.map((param) => {
        const paramValue = values[`param_${param.name}`];
        const processedParam = { ...param };

        if (paramValue !== undefined && paramValue !== null && paramValue !== '') {
          processedParam.value = {
            ...param.value,
            value: param.value['@type'].toLowerCase() === 'integer'
              ? parseInt(paramValue, 10)
              : paramValue,
          };
        }

        return processedParam;
      });

      const formData: CriteriaFormType = {
        '@bean': 'com.cyoda.core.model.stateMachine.dto.CriteriaDto',
        name: values.name || '',
        description: values.description || '',
        criteriaChecker: values.criteriaChecker || '',
        entityClassName,
        condition: condition, // Always send the condition (either GroupCondition or ConfigurableUnaryCondition)
        parameters: processedParameters,
        aliasDefs: configDefinition.aliasDefs || [], // Send aliasDefs to API
        // Note: colDefs is NOT sent to the API (it's removed in the old Vue project)
        // colDefs is only used internally for the criteria builder UI
      };

      console.log('CriteriaForm - Submitting formData:', JSON.stringify(formData, null, 2));

      let resultId;
      if (isNew) {
        const result = await createCriteriaMutation.mutateAsync({
          persistedType,
          form: formData,
        });
        resultId = result?.id || result?.Data?.id;
        message.success('Criteria created successfully');
      } else {
        await updateCriteriaMutation.mutateAsync({
          persistedType,
          criteriaId: criteriaId!,
          form: formData,
        });
        resultId = criteriaId;
        message.success('Criteria updated successfully');
      }
      
      if (onSubmitted) {
        onSubmitted({ id: resultId });
      }
    } catch (error: any) {
      console.error('❌ CriteriaForm - Error saving criteria:', error);
      const errorMessage = error?.response?.data?.message || error?.message || 'Failed to save criteria';
      message.error(`Failed to save criteria: ${errorMessage}`);
    }
  };
  
  const isLoading = isLoadingCriteria || createCriteriaMutation.isPending || updateCriteriaMutation.isPending;
  
  return (
    <Form
      form={form}
      layout="vertical"
    >
      <Form.Item
        label="Name"
        name="name"
        rules={[{ required: true, message: 'Please enter a name' }]}
        style={{ maxWidth: 600 }}
      >
        <Input disabled={isRuntime} />
      </Form.Item>

      <Form.Item
        label="Description"
        name="description"
        style={{ maxWidth: 600 }}
      >
        <TextArea
          disabled={isRuntime}
          autoSize={{ minRows: 3, maxRows: 6 }}
        />
      </Form.Item>

      {/* Criteria Section */}
      <div style={{ marginBottom: '24px' }}>
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginBottom: '16px'
        }}>
          <h3 style={{
            margin: 0,
            fontSize: '12px',
            fontWeight: 600,
            textTransform: 'uppercase',
            letterSpacing: '0.5px',
            color: '#888'
          }}>
            Criteria
          </h3>
          <Space>
            <span style={{ fontSize: '14px' }}>Developer Coded</span>
            <Switch
              checked={!isCodeCriteria}
              disabled={true}
            />
            <span style={{ fontSize: '14px', color: '#888' }}>Built in UI</span>
          </Space>
        </div>

        {isCodeCriteria ? (
          <Alert
            message="Criteria is coded. No filter builder available"
            type="info"
            showIcon
            style={{ marginBottom: '16px' }}
          />
        ) : (
          <Tabs
            type="card"
            className="criteria-tabs"
            items={[
              {
                key: 'filterbuilder',
                label: 'FilterBuilder',
                children: (
                  <div style={{ padding: '16px' }}>
                    <FilterBuilderGroup
                      condition={condition}
                      cols={cols}
                      readOnly={isRuntime}
                      showErrors={false}
                      onChange={setCondition}
                    />
                  </div>
                ),
              },
              {
                key: 'fields',
                label: 'Fields',
                children: (
                  <div style={{ padding: '16px' }}>
                    <ReportEditorTabModel
                      configDefinition={configDefinition}
                      onChange={(updates) => {
                        setConfigDefinition({ ...configDefinition, ...updates });
                      }}
                      readOnly={isRuntime}
                      showAliases={true}
                    />
                  </div>
                ),
              },
            ]}
          />
        )}
      </div>

      {/* Criteria Checker - always shown, not just for coded criteria */}
      <Form.Item
        label="Criteria Checker"
        name="criteriaChecker"
        rules={[{ required: isCodeCriteria, message: 'Please select a criteria checker' }]}
      >
        <Select
          placeholder="Select criteria checker"
          disabled={isRuntime}
          loading={isLoadingCheckers}
          options={checkerOptions}
          showSearch
          filterOption={(input, option) =>
            (option?.label ?? '').toLowerCase().includes(input.toLowerCase())
          }
          popupClassName="criteria-form-dropdown"
          dropdownStyle={{ minWidth: '400px' }}
        />
      </Form.Item>

      {/* Criteria Parameters */}
      {isCodeCriteria && criteriaParameters.length > 0 && (
        <>
          <h2 style={{ marginTop: '24px', marginBottom: '16px' }}>Criteria parameters</h2>
          {criteriaParameters.map((param, index) => {
            const fieldName = `param_${param.name}`;
            const paramType = param.value['@type'];

            // If parameter has available values, render as select
            if (param.availableValues && Array.isArray(param.availableValues)) {
              return (
                <Form.Item
                  key={index}
                  label={param.name}
                  name={fieldName}
                  rules={[{ required: true, message: 'Please select a value' }]}
                  initialValue={param.value.value}
                >
                  <Select
                    disabled={isRuntime}
                    placeholder={`Select ${param.name}`}
                    options={param.availableValues.map((val: any) => ({
                      label: val,
                      value: val,
                    }))}
                    popupClassName="criteria-form-dropdown"
                    dropdownStyle={{ minWidth: '300px' }}
                  />
                </Form.Item>
              );
            }

            // Otherwise render as input with type hint
            return (
              <Form.Item
                key={index}
                label={
                  <span>
                    {param.name} <small style={{ color: '#999' }}>{paramType}</small>
                  </span>
                }
                name={fieldName}
                rules={[{ required: true, message: 'Please fill field' }]}
                initialValue={param.value.value}
              >
                <Input
                  disabled={isRuntime}
                  placeholder={`Enter ${param.name}`}
                  type={paramType.toLowerCase() === 'integer' ? 'number' : 'text'}
                />
              </Form.Item>
            );
          })}
        </>
      )}

      <Form.Item>
        <Space>
          <Button
            type="primary"
            onClick={handleSubmit}
            loading={isLoading}
            disabled={isRuntime}
          >
            {isNew ? 'Create' : 'Update'}
          </Button>
        </Space>
      </Form.Item>
    </Form>
  );
};

export default CriteriaForm;

// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/CriteriaForm/CriteriaForm.vue
<template>
  <transition name="fade" mode="out-in">
    <el-form v-loading="isAnyLoading" :model="form" :key="form.id" ref="formRef" :rules="rules" label-width="auto"
             label-position="top">
      <div class="wrap-title">
        <h2>{{ pageTitle }}</h2>
      </div>

      <el-form-item style="max-width: 600px" label="Name" prop="name">
        <el-input :disabled="isRuntime" v-model="form.name"/>
      </el-form-item>

      <el-form-item style="max-width: 600px" label="Description" prop="description">
        <el-input
          :disabled="isRuntime"
          v-model="form.description"
          :autosize="{ minRows: 3, maxRows: 6 }"
          type="textarea"
        />
      </el-form-item>

      <el-form-item label="Criteria">
        <template #label>
          <div class="wrapper-title">
            <label class="el-form-item__label">Criteria</label>
            <div class="wrap-toggle">
              <el-switch
                :value="!isCodeCriteria"
                :disabled="true"
                active-text="Built in UI"
                inactive-text="Developer Coded"
              />
            </div>
          </div>
        </template>
        <div class="wrapper-criteria">
          <template v-if="isCodeCriteria">
            <el-alert :closable="false" title="Criteria is coded. No filter builder available" type="info"
                      show-icon></el-alert>
          </template>
          <template v-else>
            <el-tabs type="border-card">
              <el-tab-pane>
                <template #label>
                  <span :class="{ 'has-error': showErrors }">FilterBuilder</span>
                </template>
                <FilterBuilderGroup :readOnly="isRuntime" :showErrors="showErrors" :level="0" :cols="cols"
                                    :condition="form.condition"/>
              </el-tab-pane>
              <el-tab-pane label="Fields">
                <ConfigEditorReportsTabModelling :aria-readonly="isRuntime" :configDefinition="configDefinition"/>
              </el-tab-pane>
            </el-tabs>
          </template>
        </div>
      </el-form-item>

      <el-form-item label="Criteria Checker" prop="criteriaChecker">
        <el-select
          :disabled="isRuntime"
          v-model="form.criteriaChecker"
          filterable
          clearable
        >
          <el-option
            v-for="item in criteriacheckersListComputed"
            :key="item.value"
            :label="item.label"
            :value="item.value"
          />
        </el-select>
      </el-form-item>

      <div v-if="form.parameters.length">
        <h2>Process parameters</h2>
        <div v-for="(item, index) in form.parameters">
          <template v-if="item.availableValues">
            <el-form-item :label="item.name" :prop="`parameters.${index}.value.value`" :rules="{
                 required: true, message: 'Please fill field', trigger: 'change'
              }">
              <el-select
                v-model="item.value.value"
                :disabled="isRuntime"
                filterable
                placeholder="Select"
                clearable
              >
                <el-option
                  v-for="item in item.availableValues"
                  :key="item.value.value"
                  :label="item.displayValue"
                  :value="item.value.value"
                />
              </el-select>
            </el-form-item>
          </template>
          <template v-else>
            <el-form-item :prop="`parameters.${index}.value.value`" :rules="{
                 required: true, message: 'Please fill field', trigger: 'blur'
              }">
              <template #label>
                  <span>
                    {{ item.name }} <small>{{ item.value["@type"] }}</small>
                  </span>
              </template>
              <el-input :disabled="isRuntime" v-model.trim="item.value.value"/>
            </el-form-item>
          </template>
        </div>
      </div>

      <temlate v-if="mode === 'embedded'">
        <template v-if="!isNew">
          <el-button :disabled="isRuntime" :loading="isLoading" @click="onSubmit" type="primary">
            Update
          </el-button>
        </template>
        <template v-else>
          <el-button :disabled="isRuntime" :loading="isLoading" type="primary" @click="onSubmit">
            Create
          </el-button>
        </template>
      </temlate>

      <template v-else>
        <el-button :disabled="isRuntime" @click="onCancel">
          Cancel
        </el-button>

        <template v-if="!isNew">
          <el-button :disabled="isRuntime" :loading="isLoading" @click="onSubmit"
                     type="primary">
            Update & Continue Editing
          </el-button>
          <el-button :disabled="isRuntime" :loading="isLoadingUpdate" @click="onUpdate" type="primary">
            Update
          </el-button>
        </template>
        <template v-else>
          <el-button :disabled="isRuntime" :loading="isLoadingCreateAddAnother" type="primary"
                     @click="onCreateAddAnother">
            Create & Add Another
          </el-button>
          <el-button :disabled="isRuntime" :loading="isLoading" type="primary" @click="onCreate">
            Create
          </el-button>
        </template>
      </template>
    </el-form>
  </transition>
</template>

<script setup lang="ts">
import {useRoute, useRouter} from "vue-router";
import {ref, computed, watch, reactive, onMounted} from "vue";
import FilterBuilderGroup from "@cyoda/ui-lib/src/components-library/patterns/FilterBuilder/FilterBuilderGroup.vue";

import HelperFilter from "../FilterBuilder/HelperFilter";
import HelperReportDefinition from "../../../../../http-api/src/helpers/HelperReportDefinition";
import ConfigEditorReportsTabModelling
  from "../../../../../http-api/src/views/ConfigEditor/tabs/ConfigEditorReportsTabModelling.vue";
import {useStatemachineStore} from "@cyoda/statemachine/src/stores/statemachine";
import {useCriteriaMixin} from "@cyoda/statemachine/src/mixins/criteriaMixin";
import HelperProcesses from "../../../helpers/HelperProcesses";

const emit = defineEmits(["submitted", "update:criteriaTitle", "submitted", "update:criteriaTitle"]);
const formRef = ref(null);
const showErrors = ref<boolean>(false);
const props = defineProps({
  entityClassName: {type: String, required: true},
  persistedType: {type: String, required: true},
  criteriaId: {type: String, default: ""},
  workflowId: {type: String, default: ""},
  workflowPersistedType: {type: String, required: false},
  mode: {type: String, default: ""},
});
const isLoading = ref(false);
const isLoadingCreateAddAnother = ref(false);
const isLoadingCreate = ref(false);
const isLoadingUpdate = ref(false);
const router = useRouter();

const isAnyLoading = computed(() => {
  return isLoading.value || isLoadingCreateAddAnother.value || isLoadingUpdate.value || isLoadingCreate.value;
})

const defaultForm = {
  "@bean": "com.cyoda.core.model.stateMachine.dto.CriteriaDto",
  name: "",
  description: "",
  condition: HelperFilter.getGroup(),
  colDefs: [],
  aliasDefs: [],
  entityClassName: props.entityClassName,
  parameters: [],
  criteriaChecker: "",
}

const form = ref(JSON.parse(JSON.stringify(defaultForm)));

const rules = reactive({
  name: [
    {required: true, message: 'Please input name', trigger: 'blur'},
  ]
});

const route = useRoute();
const statemachineStore = useStatemachineStore();
const {isCodeCriteria} = useCriteriaMixin(form.value);
const criteriacheckersList = ref([]);
let entityParentClassesAndInterfaces = ref([]);

onMounted(() => {
  loadCriteriacheckers();
  // loadEntityParentClassesAndInterfaces();
})

const isNew = computed(() => {
  return !props.criteriaId || props.criteriaId === 'new';
});

const pageTitle = computed(() => {
  return isNew.value ? `New criteria ${form.value.name}` : `Criteria ${form.value.name}`;
});

function updateCriteria(arg: object) {
  // return statemachineStore.updateCriteria(arg);
}

let configDefinition = reactive({
  requestClass: props.entityClassName,
  colDefs: form.value.colDefs,
  aliasDefs: form.value.aliasDefs
});

const cols = computed(() => {
  return HelperReportDefinition.buildCols(configDefinition);
});

async function save() {
  let formValidate = false;
  try {
    await formRef.value.validate();
    formValidate = true;
  } catch (error) {
    throw error;
  }

  if (form.value?.parameters.length > 0) {
    form.value?.parameters.forEach((el) => {
      if (el.value['@type'].toLowerCase() === 'integer') el.value.value = parseInt(el.value.value, 10);
    })
  }

  const validate = form.value.condition.conditions ? HelperReportDefinition.validateConfigDefinition(form.value.condition.conditions) : true;
  showErrors.value = !validate;

  if (!validate || !formValidate) throw new Error('validation error');

  const criteriaTmp = JSON.parse(JSON.stringify(form.value));
  delete criteriaTmp.colDefs;
  try {
    isLoading.value = true;
    if (isNew.value) {
      const {data} = await statemachineStore.postCriteria(props.persistedType, criteriaTmp);

      formRef.value.resetFields();
      return data.id;
    }

    await statemachineStore.putCriteria(props.persistedType, criteriaTmp.id, criteriaTmp);
  } catch (error) {
    throw error;
  } finally {
    isLoading.value = false;
  }
}

async function onSubmit() {
  try {
    isLoading.value = true;
    const id = await save();

    if (isNew.value) {
      emit("submitted", {
        // Need to replace
        url: `/statemachine/criteria/${id}?persistedType=${props.persistedType}&entityClassName=${props.entityClassName}&workflowPersistedType=${props.workflowPersistedType}`,
        id
      });
    } else {
      emit("submitted");
    }
  } finally {
    isLoading.value = false;
  }
}

async function onUpdate() {
  try {
    isLoadingUpdate.value = true;
    await save();
    emit("submitted", {
      url: backLink.value
    });
  } finally {
    isLoadingUpdate.value = false;
  }
}

async function onCreate() {
  try {
    isLoadingCreate.value = true;
    await save();
    emit("submitted", {
      url: backLink.value
    });
  } finally {
    isLoadingCreate.value = false;
  }
}

async function onCreateAddAnother() {
  try {
    isLoadingCreateAddAnother.value = true;
    await save();
    emit("submitted");
    reset();
  } finally {
    isLoadingCreateAddAnother.value = false;
  }
}

const backLink = computed(() => {
  return `/statemachine/workflow/${props.workflowId}?persistedType=${props.workflowPersistedType}&entityClassName=${props.entityClassName}#processes-list`;
});

function onCancel() {
  router.push(backLink.value)
}

function reset() {
  form.value = JSON.parse(JSON.stringify(defaultForm));
  setTimeout(() => {
    formRef.value!.clearValidate();
  }, 100);
}

// watch(
//   form,
//   () => {
//     configDefinition.colDefs = form.value.colDefs;
//     configDefinition.aliasDefs = form.value.aliasDefs;
//   },
//   {immediate: true, deep: true}
// );

watch(() => configDefinition, () => {
  form.value.colDefs = configDefinition.colDefs;
  form.value.aliasDefs = configDefinition.aliasDefs;
}, {deep: true})

function functionGetAllPathsFromCriteria(conditions, aliasesArr) {
  let colPaths: string[] = [];
  conditions.forEach((el) => {
    if ("conditions" in el) {
      colPaths = [...colPaths, ...functionGetAllPathsFromCriteria(el.conditions, aliasesArr)];
    } else {
      if (!aliasesArr.includes(el.fieldName) && !colPaths.includes(el.fieldName)) {
        colPaths.push(el.fieldName);
      }
    }
  });
  return colPaths;
}

const isRuntime = computed(() => {
  return props.persistedType === 'runtime';
});


async function loadCriteriacheckers() {
  const {data} = await statemachineStore.getCriteriacheckers(props.entityClassName);
  criteriacheckersList.value = data;
}

// async function loadEntityParentClassesAndInterfaces() {
//   const {data} = await statemachineStore.getEntityParentClassesAndInterfaces(props.entityClassName);
//   entityParentClassesAndInterfaces.value = data;
// }


function getParameters() {
  const criteriaChecker = criteriacheckersList.value.find((item) => {
    return item.name === form.value.criteriaChecker;
  });

  if (criteriaChecker) {
    return criteriaChecker.parameters.map((p: any) => {
      const parameter: any = {
        name: p.name,
        valueType: p.type,
        value: {
          "@type": p.type.charAt(0).toUpperCase() + p.type.slice(1).toLowerCase(),
          value: null
        }
      };
      if (p.availableValues) {
        parameter.availableValues = p.availableValues;
      }
      return parameter;
    });
  } else {
    return [];
  }
}


const criteriacheckersListComputed = computed(() => {
  return criteriacheckersList.value
    .map((p) => ({value: p.name, label: p.name.split(".").pop()}));
});

watch(() => props.criteriaId, async () => {
  if (isNew.value) return;
  try {
    isLoading.value = true;
    const entityClassName = isRuntime.value ? props.entityClassName : undefined;
    const {data} = await statemachineStore.getCriteria(props.persistedType, props.criteriaId, entityClassName);
    form.value = data;

    configDefinition.aliasDefs = form.value.aliasDefs;

    if (form.value && form.value.condition && form.value.condition.conditions) {
      const aliasesArr = form.value.aliasDefs.map((el) => el.name);
      let colPaths: string[] = [];
      colPaths = functionGetAllPathsFromCriteria(form.value.condition.conditions, aliasesArr);
      if (colPaths.length > 0) {
        const {data: colDefs} = await statemachineStore.getCriteriaDefs({
          rootClass: props.entityClassName,
          colPaths
        });
        form.value.colDefs = colDefs;
        configDefinition.colDefs = form.value.colDefs;
      }
    }
  } finally {
    isLoading.value = false;
  }
}, {immediate: true});

watch(
  () => form.value.criteriaChecker,
  () => {
    if (isNew.value) {
      form.value.parameters = getParameters();
    }
  },
  {immediate: true, deep: true}
);

watch(() => form.value.parameters, () => {
  form.value = HelperProcesses.format(form.value);
});
</script>

<style lang="scss" scoped>
.wrapper-criteria {
  width: 100%;
}

.wrapper-title {
  display: flex;
  align-items: center;

  label {
    margin: 0 !important;
  }
}
</style>
