// .old_project /packages/statemachine/src/views/Instances.vue
<template>
  <div class="instances">
    <div class="actions">
      <el-row :gutter="20">
        <el-col :span="6">
          <el-select
            :loading="isLoadingEntities"
            @change="onChangeEntityClassName"
            clearable
            filterable
            v-model="form.entityClassName"
            placeholder="Select entity"
          >
            <el-option
              v-for="workflowEnabledType in workflowEnabledTypesOptions"
              :key="workflowEnabledType.value"
              :label="workflowEnabledType.label"
              :value="workflowEnabledType.value"
            />
          </el-select>
        </el-col>
        <el-col :span="6">
          <el-input
            :disabled="!form.entityClassName"
            v-model="form.filter"
            placeholder="Search by id"
            clearable
          />
          <div class="hint">
            To search for multiple values, please enter the IDs separated by commas
          </div>
        </el-col>
        <el-col :span="6">
          <el-button :disabled="!form.entityClassName" @click="onRun" type="primary">
            <font-awesome-icon :icon="['fas', 'magnifying-glass']" />
          </el-button>
          <el-button @click="onToggleAdvanced" type="warning"> Advanced </el-button>
        </el-col>
      </el-row>

      <el-collapse-transition>
        <div v-show="isShowAdvanced">
          <el-divider />
          <RangeCondition :form="form" />
        </div>
      </el-collapse-transition>
    </div>
    <el-divider />

    <el-table v-loading="isLoading" :data="tableData" border style="width: 100%">
      <el-table-column prop="entityId" label="Entity Id">
        <template v-slot:default="{ row }">
          <span v-if="row.deleted" class="deleted">
            {{ row.entityId }} <small>(deleted)</small>
          </span>
          <span v-else>
            {{ row.entityId }}
          </span>
        </template>
      </el-table-column>
      <el-table-column prop="entityClassNameLabel" label="Entity Name" />
      <el-table-column prop="currentWorkflowId" label="Current Workflow">
        <template v-slot:default="{ row }">
          <span v-if="row.currentWorkflowId">
            <a class="link" :href="getWorkflowLink(row)">
              {{ getWorkflowName(row) }}
            </a>
          </span>
          <span v-else> </span>
        </template>
      </el-table-column>
      <el-table-column prop="state" label="State" />
      <el-table-column prop="creationDate" label="Created">
        <template v-slot:default="{ row }">
          {{ $filters.mktimeToDateTime(row.creationDate) }}
        </template>
      </el-table-column>
      <el-table-column prop="lastUpdateTime" label="Updated">
        <template v-slot:default="{ row }">
          {{ $filters.mktimeToDateTime(row.lastUpdateTime) }}
        </template>
      </el-table-column>
      <el-table-column width="100px" label="Action">
        <template v-slot:default="{ row }">
          <CyodaButton size="default" type="primary" :to="geDetailLink(row)">
            <font-awesome-icon :icon="['fas', 'magnifying-glass']" />
          </CyodaButton>
        </template>
      </el-table-column>
    </el-table>

    <div class="navigation">
      <el-button
        :disabled="lastResponse.pagingFilter.offset <= 0 || isLoading"
        @click="onClickPrev"
        type="primary"
      >
        <font-awesome-icon :icon="['fas', 'chevron-left']" />
        Prev
      </el-button>
      <el-button :disabled="!lastResponse.hasMore || isLoading" @click="onClickNext" type="primary">
        Next
        <font-awesome-icon :icon="['fas', 'chevron-right']" />
      </el-button>
      <template v-if="lastResponse.hasMore || currentPage > 1">
        <el-divider direction="vertical" />
        Page {{ currentPage }}
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router'
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useStatemachineStore } from '../stores/statemachine'
import { getPersistedType } from '../helpers/HelperData'
import RangeCondition from '../components/RangeCondition.vue'
import CyodaButton from '@cyoda/cobi/src/components/CyodaButton/CyodaButton.vue'
import HelperEntities from '@cyoda/ui-lib/src/helpers/HelperEntities.ts'
import HelperFeatureFlags from '@cyoda/ui-lib/src/helpers/HelperFeatureFlags.ts'
import HelperStorage from '@cyoda/ui-lib/src/helpers/HelperStorage.ts'
import { useGlobalUiSettingsStore } from '@cyoda/ui-lib/src/stores/globalUiSettings.ts'

const helperStorage = new HelperStorage()
const statemachineStore = useStatemachineStore()
const route = useRoute()
const workflowEnabledTypes = ref([])
const isLoading = ref(false)
const isLoadingEntities = ref(false)
const isShowAdvanced = ref(false)

const lastResponse = ref({
  '@bean': 'com.cyoda.core.model.PartialResultsListDto',
  hasMore: false,
  items: [],
  rangeOrder: 'ASC',
  pagingFilter: {
    offset: 0,
    maxResults: 0
  }
})

const formDefault = {
  filter: '',
  entityClassName: route.query.entityClassName,
  paging: {
    offset: 0,
    maxResults: 20
  },
  rangeOrder: 'ASC',
  rangeCondition: {
    '@bean': '',
    fieldName: '',
    operation: '',
    value: {
      '@type': '',
      value: ''
    }
  }
}

let form = reactive({
  filter: route.query.filter || '',
  entityClassName: route.query.entityClassName || '',
  paging: route.query.paging ? JSON.parse(route.query.paging) : { offset: 0, maxResults: 20 },
  rangeOrder: route.query.rangeOrder || 'ASC',
  rangeCondition: route.query.rangeCondition
    ? JSON.parse(route.query.rangeCondition)
    : { '@bean': '', fieldName: '', operation: '', value: { '@type': '', value: '' } }
})

const currentPage = ref(Math.floor(Number(form.paging.offset) / Number(form.paging.maxResults)) + 1)

const workflowList = ref([])
const router = useRouter()

const globalUiSettings = useGlobalUiSettingsStore()
const entityType = computed(() => {
  return globalUiSettings.entityType
})

async function loadData() {
  if (!form.entityClassName) return
  try {
    isLoading.value = true
    const requestData = {
      entityClassName: form.entityClassName,
      rangeOrder: form.rangeOrder,
      paging: form.paging
    }
    if (form.rangeCondition['@bean']) {
      requestData.rangeCondition = form.rangeCondition
    }
    if (form.filter.trim().length > 0) {
      requestData.entityIds = form.filter
        .split(',')
        .map((el) => el.trim())
        .filter((el) => el)
    }
    const { data } = await statemachineStore.postInstances(requestData)
    lastResponse.value = data

    const query = {
      filter: form.filter,
      entityClassName: form.entityClassName,
      paging: JSON.stringify(form.paging),
      rangeOrder: form.rangeOrder,
      rangeCondition: JSON.stringify(formDefault.rangeCondition)
    }

    router.push({ query })
  } finally {
    isLoading.value = false
  }
}

function reset() {
  Object.assign(form, JSON.parse(JSON.stringify(formDefault)))
  currentPage.value = 1
}

const tableData = computed(() => {
  return lastResponse.value.items.map((el) => {
    let entityClassNameLabel = el.entityClassName
    if (HelperFeatureFlags.isUseModelsInfo()) {
      const entityRow = workflowEnabledTypes.value.find((item) => item.name === el.entityClassName)
      if (entityRow) entityClassNameLabel += ` (${HelperEntities.entityTypeMapper(entityRow.type)})`
    }
    return {
      ...el,
      entityClassNameLabel
    }
  })
})

async function loadWorkflowsData() {
  const { data } = await statemachineStore.getWorkflowEnabledTypes()
  workflowEnabledTypes.value = data
}

async function getAllWorkflowsList() {
  const { data } = await statemachineStore.getAllWorkflowsList(form.entityClassName)
  workflowList.value = data
}

const workflowEnabledTypesOptions = computed(() => {
  return HelperEntities.getOptionsFromData(workflowEnabledTypes.value, entityType.value)
})

function onClickPrev() {
  form.paging.offset -= form.paging.maxResults
  if (form.paging.offset < 0) form.paging.offset = 0

  currentPage.value -= 1
  if (currentPage.value < 0) currentPage.value = 0
  loadData()
}

function onClickNext() {
  form.paging.offset += form.paging.maxResults
  currentPage.value += 1
  loadData()
}

function onToggleAdvanced() {
  isShowAdvanced.value = !isShowAdvanced.value
}

function onRun() {
  form.paging = { offset: 0, maxResults: 20 }
  currentPage.value = 1
  loadData()
}

onMounted(async () => {
  try {
    isLoadingEntities.value = true
    await getAllWorkflowsList()
    await Promise.all([loadData(), loadWorkflowsData()])
  } finally {
    isLoadingEntities.value = false
  }
})

function onChangeEntityClassName(value) {
  reset()
  form.entityClassName = value
}

function getWorkflowName(row) {
  const workflow: any = workflowList.value.find((el) => el.id === row.currentWorkflowId)
  return workflow?.name || row.currentWorkflowId
}

function getWorkflowLink(row) {
  return `/statemachine/workflow/${row.currentWorkflowId}?persistedType=${getPersistedType(row.persisted)}&entityClassName=${row.entityClassName}`
}

function geDetailLink(row) {
  return router.resolve({
    path: `/statemachine/instances/${row.entityId}`,
    query: {
      entityClassName: row.entityClassName,
      currentWorkflowId: row.currentWorkflowId,
      persistedType: [false, true].includes(row.persisted)
        ? getPersistedType(row.persisted)
        : undefined
    }
  })
}
</script>

<style scoped lang="scss">
.instances {
  .actions {
    margin: 15px 0;
  }

  .navigation {
    margin-top: 15px;
  }

  .hint {
    font-size: 12px;
    color: #a1a0a0;
    line-height: normal;
    display: block;
    margin-top: 5px;
    width: 100%;
  }

  .deleted {
    color: #f56c6c;
  }

  .link {
    color: #409eff;

    &:hover {
      text-decoration: none;
    }
  }
}
</style>

// react-project/packages/statemachine-react/src/pages/Instances.tsx
/**
 * Instances Page
 * State machine instances list view
 * Migrated from: .old_project/packages/statemachine/src/views/Instances.vue
 */

import React, { useState, useEffect, useMemo } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Table, Button, Input, Select, Space, Card, Row, Col, message, Divider, Collapse } from 'antd';
import { SearchOutlined, LeftOutlined, RightOutlined, ArrowLeftOutlined, WarningOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import {
  useWorkflowEnabledTypes,
  useWorkflowsList,
  useInstances,
} from '../hooks/useStatemachine';
import { EntityTypeSwitch } from '@cyoda/ui-lib-react';
import { useGlobalUiSettingsStore } from '../stores/globalUiSettingsStore';
import { RangeCondition, type RangeConditionForm } from '../components/RangeCondition';
import type { Instance, InstanceTableRow, InstancesResponse } from '../types';

const PAGE_SIZE = 20;

export const Instances: React.FC = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [entityClassName, setEntityClassName] = useState(searchParams.get('entityClassName') || '');
  const [filter, setFilter] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [instancesData, setInstancesData] = useState<InstancesResponse | null>(null);
  const [isShowAdvanced, setIsShowAdvanced] = useState(false);

  // Range condition form state
  const [rangeConditionForm, setRangeConditionForm] = useState<RangeConditionForm>({
    entityClassName: entityClassName,
    rangeOrder: 'ASC',
    rangeCondition: {
      '@bean': '',
      fieldName: '',
      operation: '',
      value: {
        '@type': '',
        value: '',
      },
    },
  });

  // Global UI settings
  const { entityType, isEnabledTechView, setEntityType } = useGlobalUiSettingsStore();

  // Queries
  const { data: workflowEnabledTypes = [], isLoading: isLoadingEntities } = useWorkflowEnabledTypes();
  const { data: workflows = [] } = useWorkflowsList(entityClassName);
  const instancesMutation = useInstances();
  
  // Update rangeConditionForm when entityClassName changes
  useEffect(() => {
    setRangeConditionForm(prev => ({
      ...prev,
      entityClassName: entityClassName,
    }));
  }, [entityClassName]);

  // Load instances
  const loadInstances = async (offset = 0) => {
    if (!entityClassName) {
      message.warning('Please select an entity');
      return;
    }

    try {
      const requestData: any = {
        entityClassName,
        rangeOrder: rangeConditionForm.rangeOrder,
        paging: {
          offset,
          maxResults: PAGE_SIZE,
        },
      };

      // Add rangeCondition if it's configured
      if (rangeConditionForm.rangeCondition['@bean']) {
        requestData.rangeCondition = rangeConditionForm.rangeCondition;
      }

      // Add entity IDs filter if provided
      if (filter.trim()) {
        requestData.entityIds = filter
          .split(',')
          .map((id) => id.trim())
          .filter((id) => id);
      }

      const response = await instancesMutation.mutateAsync(requestData);
      setInstancesData(response);
    } catch (error) {
      message.error('Failed to load instances');
    }
  };
  
  // Handlers
  const handleEntityChange = (value: string) => {
    setEntityClassName(value);
    setCurrentPage(1);
    setInstancesData(null);
  };

  const handleSearch = () => {
    setCurrentPage(1);
    loadInstances(0);
  };

  const handleToggleAdvanced = () => {
    setIsShowAdvanced(!isShowAdvanced);
  };

  const handleRangeConditionChange = (form: RangeConditionForm) => {
    setRangeConditionForm(form);
  };
  
  const handlePrevPage = () => {
    const newPage = currentPage - 1;
    const newOffset = (newPage - 1) * PAGE_SIZE;
    setCurrentPage(newPage);
    loadInstances(newOffset);
  };
  
  const handleNextPage = () => {
    const newPage = currentPage + 1;
    const newOffset = (newPage - 1) * PAGE_SIZE;
    setCurrentPage(newPage);
    loadInstances(newOffset);
  };
  
  const handleViewDetail = (record: InstanceTableRow) => {
    navigate(
      `/instances/${record.entityId}?entityClassName=${record.entityClassName}`
    );
  };
  
  const getWorkflowName = (record: Instance) => {
    if (!record.currentWorkflowId) return '';
    const workflow = workflows.find((w: any) => w.id === record.currentWorkflowId);
    return workflow ? workflow.name : record.currentWorkflowId;
  };
  
  const getWorkflowLink = (record: Instance) => {
    if (!record.currentWorkflowId) return '';
    const persistedType = 'persisted'; // Default to persisted
    return `/statemachine/workflow/${record.currentWorkflowId}?persistedType=${persistedType}&entityClassName=${record.entityClassName}`;
  };

  // Helper function to map entity type
  const entityTypeMapper = (type: string): string => {
    const map: Record<string, string> = {
      BUSINESS: 'Business',
      PERSISTENCE: 'Technical',
    };
    return map[type] || type;
  };

  // Entity options - filtered by selected entity type
  const entityOptions = useMemo(() => {
    return workflowEnabledTypes
      .filter((type: any) => {
        // If tech view is enabled, filter by entity type
        if (isEnabledTechView && typeof type === 'object' && type.type) {
          return type.type === entityType;
        }
        return true;
      })
      .map((type: any) => {
        // Handle both string arrays and object arrays
        if (typeof type === 'string') {
          return { label: type, value: type };
        }

        // If entity has type info, add it to the label
        let label = type.name || type.value || type;
        if (type.type) {
          const typeLabel = entityTypeMapper(type.type);
          label = `${type.name} (${typeLabel})`;
        }

        return {
          label,
          value: type.value || type.name || type,
        };
      });
  }, [workflowEnabledTypes, entityType, isEnabledTechView]);
  
  // Table data
  const tableData: InstanceTableRow[] = (instancesData?.instances || []).map((instance) => ({
    ...instance,
    key: instance.entityId,
    entityClassNameLabel: entityOptions.find((opt) => opt.value === instance.entityClassName)?.label || instance.entityClassName,
  }));
  
  // Table columns
  const columns: ColumnsType<InstanceTableRow> = [
    {
      title: 'Entity Id',
      dataIndex: 'entityId',
      key: 'entityId',
      render: (entityId: string, record) => (
        <span style={{ color: record.deleted ? '#ff4d4f' : 'inherit' }}>
          {entityId} {record.deleted && <small>(deleted)</small>}
        </span>
      ),
    },
    {
      title: 'Entity Name',
      dataIndex: 'entityClassNameLabel',
      key: 'entityClassNameLabel',
    },
    {
      title: 'Current Workflow',
      dataIndex: 'currentWorkflowId',
      key: 'currentWorkflowId',
      render: (_, record) => {
        if (!record.currentWorkflowId) return null;
        return (
          <a href={getWorkflowLink(record)} onClick={(e) => {
            e.preventDefault();
            navigate(getWorkflowLink(record));
          }}>
            {getWorkflowName(record)}
          </a>
        );
      },
    },
    {
      title: 'State',
      dataIndex: 'state',
      key: 'state',
    },
    {
      title: 'Created',
      dataIndex: 'creationDate',
      key: 'creationDate',
      render: (date: number) => new Date(date).toLocaleString(),
    },
    {
      title: 'Updated',
      dataIndex: 'lastUpdateTime',
      key: 'lastUpdateTime',
      render: (date: number) => new Date(date).toLocaleString(),
    },
    {
      title: 'Action',
      key: 'action',
      width: 100,
      render: (_, record) => (
        <Button
          type="primary"
          size="small"
          icon={<SearchOutlined />}
          onClick={() => handleViewDetail(record)}
        />
      ),
    },
  ];
  
  // Load instances on mount if entity is selected
  useEffect(() => {
    if (entityClassName) {
      loadInstances(0);
    }
  }, [entityClassName]);
  
  const hasMore = instancesData?.hasMore || false;
  const hasPrev = currentPage > 1;
  
  return (
    <div style={{ padding: '16px' }}>
      {/* Header with Back button and Entity Type Switch */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <Button
            icon={<ArrowLeftOutlined />}
            onClick={() => navigate('/menu')}
          >
            Back to Menu
          </Button>
          <h1 style={{ margin: 0 }}>Instances</h1>
        </div>
        <EntityTypeSwitch
          value={entityType}
          onChange={setEntityType}
          visible={isEnabledTechView}
        />
      </div>

      <Card>
        <Space direction="vertical" size="middle" style={{ width: '100%' }}>
          {/* Filters */}
          <Row gutter={[16, 16]}>
            <Col span={6}>
              <Select
                placeholder="Select entity"
                value={entityClassName || undefined}
                onChange={handleEntityChange}
                loading={isLoadingEntities}
                options={entityOptions}
                showSearch
                allowClear
                style={{ width: '100%' }}
              />
            </Col>
            <Col span={6}>
              <Input
                placeholder="Search by id (comma-separated)"
                value={filter}
                onChange={(e) => setFilter(e.target.value)}
                disabled={!entityClassName}
                allowClear
              />
              <div style={{ fontSize: '12px', color: '#999', marginTop: '4px' }}>
                To search for multiple values, please enter the IDs separated by commas
              </div>
            </Col>
            <Col span={6}>
              <Space>
                <Button
                  type="primary"
                  icon={<SearchOutlined />}
                  onClick={handleSearch}
                  disabled={!entityClassName}
                  loading={instancesMutation.isPending}
                >
                  Search
                </Button>
                <Button
                  type="default"
                  icon={<WarningOutlined />}
                  onClick={handleToggleAdvanced}
                  style={{
                    backgroundColor: isShowAdvanced ? '#faad14' : undefined,
                    borderColor: isShowAdvanced ? '#faad14' : undefined,
                    color: isShowAdvanced ? '#fff' : undefined,
                  }}
                >
                  Advanced
                </Button>
              </Space>
            </Col>
          </Row>

          {/* Advanced Filtering */}
          <Collapse
            activeKey={isShowAdvanced ? ['advanced'] : []}
            ghost
            items={[
              {
                key: 'advanced',
                label: null,
                showArrow: false,
                children: (
                  <>
                    <Divider />
                    <RangeCondition
                      form={rangeConditionForm}
                      onChange={handleRangeConditionChange}
                      disabled={!entityClassName}
                    />
                  </>
                ),
              },
            ]}
          />

          {/* Table */}
          <Table
            columns={columns}
            dataSource={tableData}
            loading={instancesMutation.isPending}
            pagination={false}
            bordered
          />
          
          {/* Pagination */}
          {instancesData && (
            <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
              <Button
                type="primary"
                icon={<LeftOutlined />}
                onClick={handlePrevPage}
                disabled={!hasPrev || instancesMutation.isPending}
              >
                Prev
              </Button>
              <Button
                type="primary"
                onClick={handleNextPage}
                disabled={!hasMore || instancesMutation.isPending}
              >
                Next
                <RightOutlined />
              </Button>
              {(hasMore || currentPage > 1) && (
                <span>Page {currentPage}</span>
              )}
            </div>
          )}
        </Space>
      </Card>
    </div>
  );
};

export default Instances;
