// .old_project /packages/processing-manager/src/views/EventView.vue
<template>
  <ViewWrapper>
    <div class="card">
      <div class="card-body">
        <div class="wrap-title flex">
          <h3>Event view</h3>
          <span>
            <ErrorViewActions @reload="onReload" v-if="!data.done" />
          </span>
        </div>
        <el-divider></el-divider>
        <ul>
          <li class="name">Create Time</li>
          <li>{{ data.event.createTime }}</li>
          <li class="name">Queue</li>
          <li>{{ data.event.queueName }}</li>
          <li class="name">Shard</li>
          <li>{{ data.event.shardId }}</li>
          <li class="name">Status</li>
          <li>{{ data.event.status }}</li>
          <li class="name">Time-UUID</li>
          <li>{{ data.event.timeUUID }}</li>
          <li class="name">Entity-Class</li>
          <li>{{ data.event.queueName }}</li>
          <li class="name">Entity-ID</li>
          <li>{{ data.event.entityId }}</li>
          <li class="name">Has Errors</li>
          <li>{{ $filters.boolean(data.event.entityHasErrors) }}</li>
          <li class="name">Error Event Time-UUID</li>
          <li>{{ data.event.errorEventTimeUUID }}</li>
          <li class="name">Core event data</li>
          <li>
            <pre :class="codeObj.class">
            <code :class="codeObj.class" v-html="codeObj.code"></code>
          </pre>
          </li>
          <li class="name">Client event data</li>
          <li>{{ data.event.clientDataClassName || "-" }}</li>
        </ul>
      </div>
    </div>
  </ViewWrapper>
</template>

<script setup lang="ts">
import { useRoute } from "vue-router";
import { ref, computed } from "vue";

import ErrorViewActions from "../components/ErrorViewActions/ErrorViewActions.vue";
import Prism from "prismjs";
import "prismjs/themes/prism.css";

import beautify from "js-beautify";
import ViewWrapper from "../components/ViewWrapper.vue";
import {useProcessingStore} from "../stores/processing";

const route = useRoute();
const processingStore = useProcessingStore();
let data = ref({event: {}});

const codeObj = computed(() => {
  const dataTmp = data.value.event.coreData && beautify.js(JSON.stringify(data.value.event.coreData).trim(), {
    indent_size: 2,
    space_in_empty_paren: true,
    wrap_line_length: 50
  }) || "{}";
  return {
    class: "language-javascript",
    code: Prism.highlight(dataTmp, Prism.languages.javascript, "javascript")
  };
});

function processingQueueErrorEventByEntity(value) {
  return processingStore.processingQueueErrorEventByEntity(value);
}

loadData();

async function loadData() {
  const { data:dataValue } = await processingQueueErrorEventByEntity({
    ...route.query
  });
  data.value = dataValue;
}

function onReload() {
  loadData();
}
</script>

<style scoped lang="scss">
.card-body ul {
  list-style: none;
  margin: 0;
  padding: 0;

  li.name {
    font-weight: bold;
    margin-top: 10px;
  }
}

.wrap-title {
  margin-bottom: 15px;

  h3 {
    display: inline;
  }
}

.flex {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>

// react-project/packages/processing-manager-react/src/pages/EventView.tsx
/**
 * Event View Page
 * Migrated from @cyoda/processing-manager/src/views/EventView.vue
 */

import { useMemo } from 'react';
import { Card, Typography, Divider, Breadcrumb, Descriptions, Tag, Button } from 'antd';
import { HomeOutlined, ReloadOutlined } from '@ant-design/icons';
import { useParams, useNavigate, useSearchParams } from 'react-router-dom';
import { useProcessingQueueErrorEventByEntity } from '../hooks';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { prism } from 'react-syntax-highlighter/dist/esm/styles/prism';

const { Title } = Typography;

export default function EventView() {
  const { name } = useParams<{ name: string }>();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();

  const queryParams = {
    queue: searchParams.get('queue') || '',
    shard: searchParams.get('shard') || '',
    timeUUID: searchParams.get('timeUUID') || '',
  };

  const { data, refetch, isLoading } = useProcessingQueueErrorEventByEntity(queryParams);

  const event = data?.event || {};
  const isDone = data?.done || false;

  const formattedCoreData = useMemo(() => {
    if (!event.coreData) return '{}';
    try {
      return JSON.stringify(event.coreData, null, 2);
    } catch (e) {
      return String(event.coreData);
    }
  }, [event.coreData]);

  const handleReload = () => {
    refetch();
  };

  const breadcrumbItems = [
    {
      title: (
        <span>
          <HomeOutlined />
          <span style={{ marginLeft: 8 }}>Processing</span>
        </span>
      ),
      onClick: () => navigate('/processing-ui'),
    },
    {
      title: 'Nodes',
      onClick: () => navigate('/processing-ui/nodes'),
    },
    {
      title: name,
      onClick: () => navigate(`/processing-ui/nodes/${name}`),
    },
    {
      title: 'Event View',
    },
  ];

  return (
    <div style={{ padding: '24px' }}>
      <Breadcrumb items={breadcrumbItems} style={{ marginBottom: 16 }} />

      <Card bordered={false} loading={isLoading}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }}>
          <Title level={3} style={{ margin: 0 }}>
            Event View
          </Title>
          {!isDone && (
            <Button icon={<ReloadOutlined />} onClick={handleReload}>
              Reload
            </Button>
          )}
        </div>

        <Divider />

        <Descriptions column={1} bordered size="small">
          <Descriptions.Item label={<strong>Create Time</strong>}>
            {event.createTime || '-'}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Queue</strong>}>
            {event.queueName || '-'}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Shard</strong>}>
            {event.shardId || '-'}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Status</strong>}>
            {event.status ? <Tag color="blue">{event.status}</Tag> : '-'}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Time-UUID</strong>}>
            {event.timeUUID || '-'}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Entity-Class</strong>}>
            {event.queueName || '-'}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Entity-ID</strong>}>
            {event.entityId || '-'}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Has Errors</strong>}>
            {event.entityHasErrors !== undefined ? (
              <Tag color={event.entityHasErrors ? 'red' : 'green'}>
                {event.entityHasErrors ? 'Yes' : 'No'}
              </Tag>
            ) : (
              '-'
            )}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Error Event Time-UUID</strong>}>
            {event.errorEventTimeUUID || '-'}
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Core event data</strong>}>
            {/* @ts-ignore - react-syntax-highlighter type compatibility issue */}
            <SyntaxHighlighter
              language="javascript"
              style={prism}
              customStyle={{
                margin: 0,
                maxHeight: '400px',
                fontSize: '12px',
              }}
            >
              {formattedCoreData}
            </SyntaxHighlighter>
          </Descriptions.Item>

          <Descriptions.Item label={<strong>Client event data</strong>}>
            {event.clientDataClassName || '-'}
          </Descriptions.Item>
        </Descriptions>
      </Card>
    </div>
  );
}
