// .old_project /packages/processing-manager/src/views/NodesDetail.vue
<template>
  <ViewWrapper>
    <div class="row">
      <div class="col-sm-12">
        <el-tabs v-model="tabsHistoryValue">
          <el-tab-pane :lazy="true" label="Processing Manager">
            <PmShardsDetailTabProcessingManager/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="Server Summary">
            <PmShardsDetailTabSummary/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="Cassandra">
            <PmShardsDetailTabCassandra/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="Processing Events">
            <PmShardsDetailTabProcessingEvents/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="Time Statistics">
            <PmShardsDetailTabTimeStatistics/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="Transactions">
            <PmShardsDetailTabTransactions/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="PM components">
            <PmShardsDetailTabPmComponents/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="Composite indexes">
            <PmShardsDetailTabCompositeIndexes/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="Caches List">
            <PmShardsDetailTabCachesList/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="Network info">
            <PmShardsDetailTabNetworkInfo/>
          </el-tab-pane>
          <el-tab-pane :lazy="true" label="ZooKeeper info">
            <PmShardsDetailTabZKInfo/>
          </el-tab-pane>
        </el-tabs>
      </div>
    </div>
  </ViewWrapper>
</template>

<script setup lang="ts">
import PmShardsDetailTabProcessingEvents
  from "../components/PmShardsDetailTab/PmShardsDetailTabProcessingEvents.vue";
import PmShardsDetailTabProcessingManager
  from "../components/PmShardsDetailTab/PmShardsDetailTabProcessingManager.vue";
import PmShardsDetailTabSummary from "../components/PmShardsDetailTab/PmShardsDetailTabSummary.vue";
import PmShardsDetailTabTimeStatistics
  from "../components/PmShardsDetailTab/PmShardsDetailTabTimeStatistics.vue";
import PmShardsDetailTabTransactions
  from "../components/PmShardsDetailTab/PmShardsDetailTabTransactions.vue";
import PmShardsDetailTabCassandra
  from "../components/PmShardsDetailTab/PmShardsDetailTabCassandra.vue";
import PmShardsDetailTabPmComponents
  from "../components/PmShardsDetailTab/PmShardsDetailTabPmComponents.vue";
import PmShardsDetailTabCompositeIndexes
  from "../components/PmShardsDetailTab/PmShardsDetailTabCompositeIndexes.vue";
import PmShardsDetailTabCachesList
  from "../components/PmShardsDetailTab/PmShardsDetailTabCachesList.vue";
import PmShardsDetailTabNetworkInfo
  from "../components/PmShardsDetailTab/PmShardsDetailTabNetworkInfo.vue";
import PmShardsDetailTabZKInfo from "../components/PmShardsDetailTab/PmShardsDetailTabZKInfo.vue";
import ViewWrapper from "../components/ViewWrapper.vue";
import useTabsHistory from "@cyoda/ui-lib/src/mixins/TabsHistoryMixin";

const {tabsHistoryValue} = useTabsHistory('nodesDetailTab');
</script>

// react-project/packages/processing-manager-react/src/pages/NodesDetail.tsx
/**
 * Nodes Detail Page
 * Migrated from @cyoda/processing-manager/src/views/NodesDetail.vue
 */

import React, { useState } from 'react';
import { Card, Typography, Tabs } from 'antd';
import { Layout } from '../components/layout';
import { useParams } from 'react-router-dom';
import {
  ShardsDetailTabProcessingManager,
  ShardsDetailTabSummary,
  ShardsDetailTabCassandra,
  ShardsDetailTabProcessingEvents,
  ShardsDetailTabTimeStatistics,
  ShardsDetailTabTransactions,
  ShardsDetailTabPmComponents,
  ShardsDetailTabCompositeIndexes,
  ShardsDetailTabCachesList,
  ShardsDetailTabNetworkInfo,
  ShardsDetailTabZKInfo,
} from '../components/shards';

const { Title } = Typography;
const { TabPane } = Tabs;

export default function NodesDetail() {
  const { name } = useParams<{ name: string }>();
  const [activeKey, setActiveKey] = useState('1');

  return (
    <Layout>
      <div style={{ padding: '24px' }}>
        <Card>
          <Title level={2}>Node Detail: {name}</Title>
          <Tabs activeKey={activeKey} onChange={setActiveKey}>
            <TabPane tab="Processing Manager" key="1">
              <ShardsDetailTabProcessingManager />
            </TabPane>
            <TabPane tab="Server Summary" key="2">
              <ShardsDetailTabSummary />
            </TabPane>
            <TabPane tab="Cassandra" key="3">
              <ShardsDetailTabCassandra />
            </TabPane>
            <TabPane tab="Processing Events" key="4">
              <ShardsDetailTabProcessingEvents />
            </TabPane>
            <TabPane tab="Time Statistics" key="5">
              <ShardsDetailTabTimeStatistics />
            </TabPane>
            <TabPane tab="Transactions" key="6">
              <ShardsDetailTabTransactions />
            </TabPane>
            <TabPane tab="PM components" key="7">
              <ShardsDetailTabPmComponents />
            </TabPane>
            <TabPane tab="Composite indexes" key="8">
              <ShardsDetailTabCompositeIndexes />
            </TabPane>
            <TabPane tab="Caches List" key="9">
              <ShardsDetailTabCachesList />
            </TabPane>
            <TabPane tab="Network info" key="10">
              <ShardsDetailTabNetworkInfo />
            </TabPane>
            <TabPane tab="ZooKeeper info" key="11">
              <ShardsDetailTabZKInfo />
            </TabPane>
          </Tabs>
        </Card>
      </div>
    </Layout>
  );
}
