// react-project/packages/ui-lib-react/src/components/DataLineageCompare/DataLineageCompare.tsx
import React, { useState, useImperativeHandle, forwardRef, useMemo } from 'react'
import { Modal } from 'antd'
import dayjs from 'dayjs'
import { CodeEditor } from '../CodeEditor'
import './DataLineageCompare.scss'

export interface Transaction {
  transactionId: string
  dateTime: string
  [key: string]: any
}

export interface ChangedField {
  columnPath: string
  columnPathContainer: {
    prevValue: any
    currValue: any
  }
}

export interface CompareData {
  changedFields?: ChangedField[]
  [key: string]: any
}

export interface DataLineageCompareProps {
  compareData?: CompareData
  checkedTransactions?: Transaction[]
  className?: string
}

export interface DataLineageCompareRef {
  dialogVisible: boolean
  setDialogVisible: (visible: boolean) => void
}

/**
 * DataLineageCompare Component
 * Displays a comparison dialog for data lineage transactions
 */
export const DataLineageCompare = forwardRef<DataLineageCompareRef, DataLineageCompareProps>(
  ({ compareData = {}, checkedTransactions = [], className = '' }, ref) => {
    const [dialogVisible, setDialogVisible] = useState(false)

    useImperativeHandle(ref, () => ({
      dialogVisible,
      setDialogVisible
    }))

    const transformDate = (date: string): string => {
      return dayjs(date, 'DD-MM-YYYY HH:mm:ss.SSS').format('DD/MM/YYYY HH:mm:ss')
    }

    const getDataFor = (field: 'currValue' | 'prevValue'): string => {
      if (!compareData?.changedFields) return ''
      
      return compareData.changedFields
        .map((el) => `${el.columnPath}: ${el.columnPathContainer[field]}`)
        .join('\n')
    }

    const oldStr = useMemo(() => getDataFor('prevValue'), [compareData])
    const newStr = useMemo(() => getDataFor('currValue'), [compareData])

    const handleClose = () => {
      setDialogVisible(false)
    }

    return (
      <Modal
        title="Compare"
        open={dialogVisible}
        onCancel={handleClose}
        width="80%"
        footer={null}
        maskClosable={false}
        className={`data-lineage-compare ${className}`}
      >
        {checkedTransactions.length >= 2 && (
          <div className="row flex">
            <div>
              <strong>Date:</strong> {transformDate(checkedTransactions[0].dateTime)}
              <br />
              <strong>Transaction Id:</strong> {checkedTransactions[0].transactionId}
            </div>
            <div>
              <strong>Date:</strong> {transformDate(checkedTransactions[1].dateTime)}
              <br />
              <strong>Transaction Id:</strong> {checkedTransactions[1].transactionId}
            </div>
          </div>
        )}
        <CodeEditor
          value={oldStr}
          language="text"
          readOnly
          diffEditor
          originalValue={oldStr}
          modifiedValue={newStr}
        />
      </Modal>
    )
  }
)

DataLineageCompare.displayName = 'DataLineageCompare'

// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/DataLineage/DataLineageCompare.vue
<template>
  <el-dialog :close-on-click-modal="false" :append-to-body="true" title="Compare" v-model="dialogVisible" class="data-lineage-compare" width="80%">
    <div class="row flex">
      <div>
        <strong>Date:</strong> {{ transformDate(checkedTransactions[0].dateTime) }}<br />
        <strong>Transaction Id:</strong> {{ checkedTransactions[0].transactionId }}
      </div>
      <div>
        <strong>Date:</strong> {{ transformDate(checkedTransactions[1].dateTime) }}<br />
        <strong>Transaction Id:</strong> {{ checkedTransactions[1].transactionId }}
      </div>
    </div>
    <CyodaEditor :old-string="oldStrComputed" :new-string="newStrComputed" :diff="true"/>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";

import moment from "moment";
import { Transaction, TransactionDiff } from "../../../types/types";
import CyodaEditor from "@cyoda/ui-lib/src/components-library/elements/CyodaEditor/CyodaEditor.vue";

const props = defineProps({
  compareData: {
    default: () => {
      return [];
    }
  },
  checkedTransactions: {
    default: () => {
      return [];
    }
  }
});
const oldStrComputed = computed(() => {
  return getDataFor("prevValue");
});
const newStrComputed = computed(() => {
  return getDataFor("currValue");
});

const dialogVisible = ref<boolean>(false);

function getDataFor(field: "currValue" | "prevValue") {
  return (
    (props.compareData &&
      props.compareData.changedFields &&
      props.compareData.changedFields
        .map((el) => {
          return `${el.columnPath}: ${el.columnPathContainer[field]}`;
        })
        .join("\n")) ||
    ""
  );
}

function transformDate(date: string) {
  return moment(date, "DD-MM-YYYY HH:mm:ss.SSS").format("DD/MM/YYYY HH:mm:ss");
}

defineExpose({ dialogVisible });
</script>

<style lang="scss">
.data-lineage-compare {
  .flex {
    display: flex;
    margin-bottom: 10px;

    > div {
      width: 50%;
      line-height: 1.3;
    }
  }
}
</style>
