// .old_project /packages/tasks/src/views/tasks/index/Tasks.vue
<template>
  <div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="actions">
              <div>
                <h2>Filters</h2>
              </div>
              <div class="text-right">
                <el-button @click="toggleApplyRealData" v-if="isApplyRealData" key="applyRealDataTrue" type="warning">
                  Unsubscribe to live data
                  <font-awesome-icon icon="times"/>
                </el-button>
                <el-button @click="toggleApplyRealData" v-else key="applyRealDataFalse" type="primary">
                  Subscribe to live data
                  <font-awesome-icon icon="satellite"/>
                </el-button>
              </div>
            </div>
            <TasksFilter @changeFilter="onChangeFilter"/>
            <keep-alive>
              <TasksGrid :isApplyRealData="isApplyRealData" :filter="filter"/>
            </keep-alive>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import {ref, computed} from "vue";

import TasksFilter from "./TasksFilter.vue";
import TasksGrid from "./TasksGrid.vue";
import type {TaskFilterType} from "../types";
import {useTasksStore} from "../../../stores/tasks";


const tasksStore = useTasksStore();
const isApplyRealData = computed(() => {
  return tasksStore.isApplyRealData;
})

function setIsApplyRealData(isApplyRealData: boolean) {
  return tasksStore.setIsApplyRealData(isApplyRealData);
}

let filter = ref({});

function onChangeFilter(filterValue: TaskFilterType) {
  filter.value = filterValue;
}

function toggleApplyRealData() {
  setIsApplyRealData(!isApplyRealData.value);
}
</script>

<style lang="scss" scoped>
.actions {
  display: flex;
  justify-content: space-between;
  align-items: center;

  .text-right {
    text-align: right;
  }
}
</style>

// packages/tasks-react/src/pages/Tasks.tsx
/**
 * Tasks Page
 * Main tasks list page with filters and grid
 * Migrated from: .old_project/packages/tasks/src/views/tasks/index/Tasks.vue
 */

import React, { useState, useCallback } from 'react';
import { Button, Card, Typography } from 'antd';
import { SyncOutlined, StopOutlined } from '@ant-design/icons';
import { TasksFilter } from '../components/TasksFilter';
import { TasksGrid } from '../components/TasksGrid';
import { useTasksState } from '../hooks/useTasks';
import type { TaskFilterType } from '../types';
import './Tasks.scss';

const { Title } = Typography;

export const Tasks: React.FC = () => {
  const [filter, setFilter] = useState<TaskFilterType>({});
  const { isApplyRealData, setIsApplyRealData } = useTasksState();

  const handleChangeFilter = useCallback((filterValue: TaskFilterType) => {
    setFilter(filterValue);
  }, []);

  const toggleApplyRealData = useCallback(() => {
    setIsApplyRealData(!isApplyRealData);
  }, [isApplyRealData, setIsApplyRealData]);

  return (
    <div className="tasks-page">
      <Card>
        <div className="tasks-header">
          <Title level={4} style={{ margin: 0 }}>Filters</Title>
          <div className="tasks-actions">
            {isApplyRealData ? (
              <Button
                type="primary"
                danger
                icon={<StopOutlined />}
                onClick={toggleApplyRealData}
              >
                Unsubscribe to live data
              </Button>
            ) : (
              <Button
                type="primary"
                icon={<SyncOutlined />}
                onClick={toggleApplyRealData}
              >
                Subscribe to live data
              </Button>
            )}
          </div>
        </div>
        <TasksFilter onChangeFilter={handleChangeFilter} />
        <TasksGrid filter={filter} isApplyRealData={isApplyRealData} />
      </Card>
    </div>
  );
};
