// react-project/packages/cobi-react/src/pages/DataManagementDashboard/components/ExecuteDialog/DataSourceConfigDialogResultTabs.tsx
import React from 'react';
import { Tabs, Divider } from 'antd';
import DataToClipboard from '../../../../components/DataToClipboard/DataToClipboard';
import DataSourceConfigDialogResultTabsData from './DataSourceConfigDialogResultTabsData';
import DataSourceConfigDialogResultTabsRaw from './DataSourceConfigDialogResultTabsRaw';
import DataSourceConfigDialogResultTabsStatistics from './DataSourceConfigDialogResultTabsStatistics';
import DataSourceConfigDialogResultTabsRawJSONResponse from './DataSourceConfigDialogResultTabsRawJSONResponse';
import './DataSourceConfigDialogResultTabs.css';

interface DataSourceConfigDialogResultTabsProps {
  result: any;
  requestId: string;
}

const DataSourceConfigDialogResultTabs: React.FC<DataSourceConfigDialogResultTabsProps> = ({
  result,
  requestId,
}) => {
  const tabItems = [];

  // Data tab
  if (result.data && result.data.length > 0) {
    tabItems.push({
      key: 'data',
      label: 'Data',
      children: <DataSourceConfigDialogResultTabsData data={result.data} />,
    });
  }

  // Errors tab
  if (result.errors && result.errors.length > 0) {
    tabItems.push({
      key: 'errors',
      label: 'Errors',
      children: <DataSourceConfigDialogResultTabsRaw data={result.errors} />,
    });
  }

  // Mapping Warnings tab
  if (result.mappingWarnings && result.mappingWarnings.length > 0) {
    tabItems.push({
      key: 'mappingWarnings',
      label: 'Mapping Warnings',
      children: <DataSourceConfigDialogResultTabsRaw data={result.mappingWarnings} />,
    });
  }

  // Mapping Statistics tab
  if (result.mappingStatistics && result.mappingStatistics.length > 0) {
    tabItems.push({
      key: 'mappingStatistics',
      label: 'Mapping Statistics',
      children: <DataSourceConfigDialogResultTabsStatistics data={result.mappingStatistics} />,
    });
  }

  // Requests Tree tab
  if (result.requestsTree && Object.keys(result.requestsTree).length > 0) {
    tabItems.push({
      key: 'requestsTree',
      label: 'Requests Tree',
      children: <DataSourceConfigDialogResultTabsRaw data={result.requestsTree} />,
    });
  }

  // JSON Response tab (always shown)
  tabItems.push({
    key: 'jsonResponse',
    label: 'JSON Response',
    children: <DataSourceConfigDialogResultTabsRawJSONResponse data={result} />,
  });

  return (
    <div className="data-source-config-dialog-result-tabs">
      <div className="status">
        <strong>State:</strong> {result.state || 'N/A'}
      </div>
      {requestId && (
        <div className="request-uuid">
          <strong>Request UUID:</strong> <DataToClipboard value={requestId} />
        </div>
      )}
      <Divider />
      <Tabs items={tabItems} />
    </div>
  );
};

export default DataSourceConfigDialogResultTabs;

// .old_project /packages/cobi/src/components/DataSourceConfig/DataSourceConfigDialogRequest/DataSourceConfigDialogResult/DataSourceConfigDialogResultTabs/DataSourceConfigDialogResultTabs.vue
<template>
  <div class="data-source-config-dialog-result-tabs">
    <div class="status"><strong>State:</strong> {{ result.state }}</div>
    <div v-if="requestId" class="request-uuid"><strong>Request UUID:</strong> <DataToClipboard :value="requestId" /></div>
    <el-divider />
    <el-tabs>
      <el-tab-pane label="Data" v-if="result.data && result.data.length > 0">
        <DataSourceConfigDialogResultTabsData :data="result.data" />
      </el-tab-pane>
      <el-tab-pane label="Errors" v-if="result.errors && result.errors.length > 0">
        <DataSourceConfigDialogResultTabsRaw :data="result.errors" />
      </el-tab-pane>
      <el-tab-pane label="Mapping Warnings" v-if="result.mappingWarnings && result.mappingWarnings.length > 0">
        <DataSourceConfigDialogResultTabsRaw :data="result.mappingWarnings" />
      </el-tab-pane>
      <el-tab-pane label="Mapping Statistics" v-if="result.mappingStatistics && result.mappingStatistics.length > 0">
        <DataSourceConfigDialogResultTabsStatistics :data="result.mappingStatistics" />
      </el-tab-pane>
      <el-tab-pane label="Requests Tree" v-if="result.requestsTree && Object.keys(result.requestsTree).length > 0">
        <DataSourceConfigDialogResultTabsRaw :data="result.requestsTree" />
      </el-tab-pane>
      <el-tab-pane label="JSON Response">
        <DataSourceConfigDialogResultTabsRawJSONResponse :data="result" />
      </el-tab-pane>
    </el-tabs>
  </div>
</template>

<script setup lang="ts">
import DataSourceConfigDialogResultTabsRaw from "./DataSourceConfigDialogResultTabsRaw.vue";
import DataSourceConfigDialogResultTabsData from "./DataSourceConfigDialogResultTabsData.vue";
import DataSourceConfigDialogResultTabsStatistics from "./DataSourceConfigDialogResultTabsStatistics.vue";
import DataToClipboard from "../../../../DataToClipboard/DataToClipboard.vue";
import DataSourceConfigDialogResultTabsRawJSONResponse from "./DataSourceConfigDialogResultTabsRawJSONResponse.vue";

const props = defineProps({
  result: {
    default: () => {
      return {};
    }
  },
  requestId: {
    default: ""
  }
});
</script>

<style>
.request-uuid {
  margin-top: 5px;
}
</style>
