// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/PmTransitionChanges/TransitionChangesTable.vue
<template>
  <div class="card">
    <div class="card-body">
      <data-tables :data="tableData" style="width: 100%">
        <el-table-column type="expand">
          <template v-slot:default="props">
            <el-table :data="props.row.changedFieldValues" style="width: 100%">
              <el-table-column prop="columnPathComputed" label="Path">
                <template v-slot:default="scope">
                  {{ scope.row.columnPath || "-" }}
                </template>
              </el-table-column>
              <el-table-column prop="prevValue" label="Old value"/>
              <el-table-column prop="currValue" label="New value"/>
            </el-table>
          </template>
        </el-table-column>
        <el-table-column label="Transaction Id" width="320px" prop="transactionId">
          <template v-slot:default="scope">
            <template v-if="disableLink">
              {{ scope.row.transactionId }}
            </template>
            <template v-else>
              <router-link :to="`/processing-ui/nodes/${route.params.name}/transaction/${scope.row.transactionId}`">
                {{ scope.row.transactionId }}
              </router-link>
            </template>
          </template>
        </el-table-column>
        <el-table-column label="Time(uuid/date)" prop="timeUid">
          <template v-slot:default="{row}"> {{ row.timeUUID }} / {{ row.creationDate }}</template>
        </el-table-column>
        <el-table-column label="State from">
          <template v-slot:default="{row}"> {{ getChangedFieldValuesByKey(row, 'state', 'prevValue') }}</template>
        </el-table-column>
        <el-table-column label="State to">
          <template v-slot:default="{row}">{{ getChangedFieldValuesByKey(row, 'state', 'currValue') }}</template>
        </el-table-column>
        <el-table-column label="User" prop="user"/>
        <el-table-column label="Change Type" prop="operation"/>
      </data-tables>
    </div>
  </div>
</template>

<script setup lang="ts">
import {useRoute} from "vue-router";
import {ref} from "vue";
import {useHttpApiProcessingStore} from "@cyoda/http-api/src/stores/httpApiProcessing";

const route = useRoute();
const props = defineProps({type: {default: ""}, entityId: {default: ""}, disableLink: {default: false}});
const httpApiProcessingStore = useHttpApiProcessingStore();

function transactionsViewEntityChanges(value) {
  return httpApiProcessingStore.transactionsViewEntityChanges(value);
}

let tableData = ref([]);

loadData();

async function loadData() {
  const {data} = await transactionsViewEntityChanges({
    type: props.type,
    id: props.entityId
  });
  tableData.value = data;
}

function getChangedFieldValuesByKey(scope, columnPath, field) {
  console.log(scope);
  const row = scope.changedFieldValues.find(elem => elem.columnPath === columnPath);
  if (!row) return;
  return row[field];
}
</script>

// packages/ui-lib-react/src/components/TransitionChangesTable/TransitionChangesTable.tsx
import React, { useState, useEffect } from 'react'
import { Table } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { Link } from 'react-router-dom'
import './TransitionChangesTable.scss'

export interface ChangedFieldValue {
  columnPath: string
  prevValue: string
  currValue: string
}

export interface TransitionChange {
  transactionId: string
  timeUUID: string
  creationDate: string
  user: string
  operation: string
  changedFieldValues: ChangedFieldValue[]
}

export interface TransitionChangesTableProps {
  /** Entity type */
  type?: string
  /** Entity ID */
  entityId?: string
  /** Whether to disable transaction links */
  disableLink?: boolean
  /** Function to fetch transaction changes */
  onFetchChanges?: (params: { type: string; id: string }) => Promise<TransitionChange[]>
  /** Base path for transaction links */
  basePath?: string
}

/**
 * TransitionChangesTable Component
 * Displays entity transition changes with expandable rows showing field changes
 * 
 * Migrated from Vue: .old_project/packages/cyoda-ui-lib/src/components-library/patterns/PmTransitionChanges/TransitionChangesTable.vue
 */
export const TransitionChangesTable: React.FC<TransitionChangesTableProps> = ({
  type = '',
  entityId = '',
  disableLink = false,
  onFetchChanges,
  basePath = '/processing-ui/nodes'
}) => {
  const [tableData, setTableData] = useState<TransitionChange[]>([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    loadData()
  }, [type, entityId])

  const loadData = async () => {
    if (!onFetchChanges || !type || !entityId) return

    try {
      setLoading(true)
      const data = await onFetchChanges({ type, id: entityId })
      setTableData(data)
    } finally {
      setLoading(false)
    }
  }

  const getChangedFieldValuesByKey = (
    record: TransitionChange,
    columnPath: string,
    field: 'prevValue' | 'currValue'
  ): string => {
    const row = record.changedFieldValues.find(elem => elem.columnPath === columnPath)
    return row ? row[field] : '-'
  }

  const expandedRowRender = (record: TransitionChange) => {
    const columns: ColumnsType<ChangedFieldValue> = [
      {
        title: 'Path',
        dataIndex: 'columnPath',
        key: 'columnPath',
        render: (text) => text || '-'
      },
      {
        title: 'Old value',
        dataIndex: 'prevValue',
        key: 'prevValue'
      },
      {
        title: 'New value',
        dataIndex: 'currValue',
        key: 'currValue'
      }
    ]

    return (
      <Table
        columns={columns}
        dataSource={record.changedFieldValues}
        pagination={false}
        rowKey={(row) => row.columnPath}
      />
    )
  }

  const columns: ColumnsType<TransitionChange> = [
    {
      title: 'Transaction Id',
      dataIndex: 'transactionId',
      key: 'transactionId',
      width: 320,
      render: (text, record) => {
        if (disableLink) {
          return text
        }
        return (
          <Link to={`${basePath}/${type}/transaction/${record.transactionId}`}>
            {text}
          </Link>
        )
      }
    },
    {
      title: 'Time(uuid/date)',
      key: 'timeUid',
      render: (_, record) => `${record.timeUUID} / ${record.creationDate}`
    },
    {
      title: 'State from',
      key: 'stateFrom',
      render: (_, record) => getChangedFieldValuesByKey(record, 'state', 'prevValue')
    },
    {
      title: 'State to',
      key: 'stateTo',
      render: (_, record) => getChangedFieldValuesByKey(record, 'state', 'currValue')
    },
    {
      title: 'User',
      dataIndex: 'user',
      key: 'user'
    },
    {
      title: 'Change Type',
      dataIndex: 'operation',
      key: 'operation'
    }
  ]

  return (
    <div className="transition-changes-table card">
      <div className="card-body">
        <Table
          columns={columns}
          dataSource={tableData}
          loading={loading}
          scroll={{ x: true, y: 400 }}
          expandable={{
            expandedRowRender,
            rowExpandable: (record) => record.changedFieldValues && record.changedFieldValues.length > 0
          }}
          rowKey={(record) => record.transactionId}
        />
      </div>
    </div>
  )
}
