// .old_project /packages/processing-manager/src/components/PmTransitionVersions/TransitionVersionsFilter.vue
<template>
  <div class="card">
    <div class="card-header">Filter</div>
    <div class="card-body">
      <el-form class="transition-versions-filter" label-position="top">
        <el-row class="wrap-row" :gutter="20">
          <el-col :span="4">
            <el-form-item label="Date From">
              <el-date-picker format="YYYY-MM-DD HH:mm:ss" value-format="YYYY-MM-DD HH:mm:ss" v-model="form.dateFrom" type="datetime" placeholder="Pick a day" />
            </el-form-item>
          </el-col>
          <el-col :span="4">
            <el-form-item label="Date To">
              <el-date-picker format="YYYY-MM-DD HH:mm:ss" value-format="YYYY-MM-DD HH:mm:ss" v-model="form.dateTo" type="datetime" placeholder="Pick a day" />
            </el-form-item>
          </el-col>
          <el-col :span="4">
            <el-form-item label="Action Type">
              <el-select v-model="form.actionTypeStr" placeholder="Action Type">
                <el-option v-for="actionType in actionTypeOptions" :key="actionType" :label="actionType" :value="actionType" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="4">
            <el-form-item label="Sort">
              <el-select v-model="form.sort" placeholder="Sort">
                <el-option label="Asc" value="ASC" />
                <el-option label="Desc" value="DESC" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col class="action-item" :span="4">
            <el-button @click="onSubmit" :loading="isLoading" type="primary">Load</el-button>
          </el-col>
        </el-row>
      </el-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

import moment from "moment";
import {useProcessingStore} from "../../stores/processing";

const emit = defineEmits(["change", "change"]);
const props = defineProps({ isLoading: { default: false } });
const processingStore = useProcessingStore();
function loadTransactionsStatuses() {
  return processingStore.loadTransactionsStatuses();
}

let transactionStatusData = ref([]);

let actionTypeOptions = ref(["ALL", "READ", "UPDATE", "REMOVE"]);

(async function () {
  await loadStatuses();
  emit("change", form.value);
})();

async function loadStatuses() {
  const { data } = await loadTransactionsStatuses();
  transactionStatusData.value = data.map((el: any) => ({
    label: el,
    value: el
  }));
}

let form = ref({
  transactionId: "",
  status: "",
  dateFrom: moment().subtract(1, "days").format("YYYY-MM-DD HH:mm:ss"),
  dateTo: moment().format("YYYY-MM-DD HH:mm:ss"),
  sort: "ASC",
  actionTypeStr: "ALL"
});

function onSubmit() {
  emit("change", form.value);
}

defineExpose({ form });
</script>

<style lang="scss">
.transition-versions-filter {
  .el-form-item__label {
    margin-bottom: 0 !important;
    padding-bottom: 0 !important;
  }

  .wrap-row {
    position: relative;

    .action-item {
      position: relative;
      left: 0;
      top: 22px;
    }
  }
}
</style>

// packages/processing-manager-react/src/components/versions/TransitionVersionsFilter.tsx
/**
 * Transition Versions Filter Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionVersions/TransitionVersionsFilter.vue
 */

import React, { useState, useEffect } from 'react';
import { Card, Form, DatePicker, Select, Button, Row, Col } from 'antd';
import dayjs from 'dayjs';
import { useTransactionStatuses } from '../../hooks';
import './TransitionVersionsFilter.scss';

interface FilterValues {
  transactionId: string;
  status: string;
  dateFrom: string;
  dateTo: string;
  sort: string;
  actionTypeStr: string;
}

interface TransitionVersionsFilterProps {
  isLoading?: boolean;
  onChange?: (values: FilterValues) => void;
}

export const TransitionVersionsFilter: React.FC<TransitionVersionsFilterProps> = ({
  isLoading = false,
  onChange,
}) => {
  const [form, setForm] = useState<FilterValues>({
    transactionId: '',
    status: '',
    dateFrom: dayjs().subtract(1, 'days').format('YYYY-MM-DD HH:mm:ss'),
    dateTo: dayjs().format('YYYY-MM-DD HH:mm:ss'),
    sort: 'ASC',
    actionTypeStr: 'ALL',
  });

  const { data: statusesData } = useTransactionStatuses();

  const actionTypeOptions = ['ALL', 'READ', 'UPDATE', 'REMOVE'];

  useEffect(() => {
    // Emit initial form values
    onChange?.(form);
  }, []);

  const handleSubmit = () => {
    onChange?.(form);
  };

  const handleFieldChange = (field: keyof FilterValues, value: any) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <Card title="Filter">
      <Form layout="vertical" className="transition-versions-filter">
        <Row gutter={20} className="wrap-row">
          <Col span={4}>
            <Form.Item label="Date From">
              <DatePicker
                showTime
                format="YYYY-MM-DD HH:mm:ss"
                value={form.dateFrom ? dayjs(form.dateFrom) : null}
                onChange={(date) =>
                  handleFieldChange('dateFrom', date ? dayjs(date).format('YYYY-MM-DD HH:mm:ss') : '')
                }
                placeholder="Pick a day"
                style={{ width: '100%' }}
              />
            </Form.Item>
          </Col>
          <Col span={4}>
            <Form.Item label="Date To">
              <DatePicker
                showTime
                format="YYYY-MM-DD HH:mm:ss"
                value={form.dateTo ? dayjs(form.dateTo) : null}
                onChange={(date) =>
                  handleFieldChange('dateTo', date ? dayjs(date).format('YYYY-MM-DD HH:mm:ss') : '')
                }
                placeholder="Pick a day"
                style={{ width: '100%' }}
              />
            </Form.Item>
          </Col>
          <Col span={4}>
            <Form.Item label="Action Type">
              <Select
                value={form.actionTypeStr}
                onChange={(value) => handleFieldChange('actionTypeStr', value)}
                placeholder="Action Type"
                options={actionTypeOptions.map((type) => ({ value: type, label: type }))}
                popupClassName="transition-versions-filter-dropdown"
                dropdownStyle={{ minWidth: '300px' }}
              />
            </Form.Item>
          </Col>
          <Col span={4}>
            <Form.Item label="Sort">
              <Select
                value={form.sort}
                onChange={(value) => handleFieldChange('sort', value)}
                placeholder="Sort"
                options={[
                  { value: 'ASC', label: 'Asc' },
                  { value: 'DESC', label: 'Desc' },
                ]}
                popupClassName="transition-versions-filter-dropdown"
                dropdownStyle={{ minWidth: '300px' }}
              />
            </Form.Item>
          </Col>
          <Col span={4} className="action-item">
            <Button type="primary" onClick={handleSubmit} loading={isLoading}>
              Load
            </Button>
          </Col>
        </Row>
      </Form>
    </Card>
  );
};

export default TransitionVersionsFilter;
