// react-project/packages/processing-manager-react/src/components/transition-detail/MembersFilter.tsx
/**
 * Members Filter Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionDetail/Members/MembersFilter.vue
 */

import React, { useState, forwardRef, useImperativeHandle } from 'react';
import { Card, Form, Select, Button, Row, Col } from 'antd';
import { useEntitiesListPossible } from '../../hooks';
import './MembersFilter.scss';

interface FilterValues {
  entityType: string;
  actionType: string;
  versionCheckResult: boolean | null;
  sort: string;
}

interface MembersFilterProps {
  isLoading?: boolean;
  onChange?: (values: FilterValues) => void;
}

export interface MembersFilterRef {
  form: FilterValues;
}

export const MembersFilter = forwardRef<MembersFilterRef, MembersFilterProps>(
  ({ isLoading = false, onChange }, ref) => {
    const [form, setForm] = useState<FilterValues>({
      entityType: '',
      actionType: 'ALL',
      versionCheckResult: null,
      sort: 'ASC',
    });

    const { data: entityClassesData } = useEntitiesListPossible();

    const entityClassOptions = entityClassesData?.map((el: string) => ({
      label: el,
      value: el,
    })) || [];

    const actionTypeOptions = ['ALL', 'READ', 'UPDATE', 'REMOVE'];

    useImperativeHandle(ref, () => ({
      form,
    }));

    const handleSubmit = () => {
      onChange?.(form);
    };

    const handleFieldChange = (field: keyof FilterValues, value: any) => {
      setForm((prev) => ({ ...prev, [field]: value }));
    };

    return (
      <Card title="Filter">
        <Form layout="vertical" className="members-filter">
          <Row gutter={20} className="wrap-row">
            <Col span={5}>
              <Form.Item label="Entity type">
                <Select
                  showSearch
                  allowClear
                  value={form.entityType}
                  onChange={(value) => handleFieldChange('entityType', value || '')}
                  options={entityClassOptions}
                />
              </Form.Item>
            </Col>
            <Col span={5}>
              <Form.Item label="Action Type">
                <Select
                  value={form.actionType}
                  onChange={(value) => handleFieldChange('actionType', value)}
                  options={actionTypeOptions.map((a) => ({ value: a, label: a }))}
                  placeholder="Action Type"
                />
              </Form.Item>
            </Col>
            <Col span={5}>
              <Form.Item label="Version check result">
                <Select
                  allowClear
                  value={form.versionCheckResult}
                  onChange={(value) => handleFieldChange('versionCheckResult', value)}
                  options={[
                    { label: 'True', value: true },
                    { label: 'False', value: false },
                  ]}
                  placeholder="Please select"
                />
              </Form.Item>
            </Col>
            <Col span={5}>
              <Form.Item label="Sort">
                <Select
                  value={form.sort}
                  onChange={(value) => handleFieldChange('sort', value)}
                  options={[
                    { label: 'Asc', value: 'ASC' },
                    { label: 'Desc', value: 'DESC' },
                  ]}
                  placeholder="Sort"
                />
              </Form.Item>
            </Col>
            <Col span={4} className="action-item">
              <Button type="primary" onClick={handleSubmit} loading={isLoading}>
                Load
              </Button>
            </Col>
          </Row>
        </Form>
      </Card>
    );
  }
);

MembersFilter.displayName = 'MembersFilter';

export default MembersFilter;

// .old_project /packages/processing-manager/src/components/PmTransitionDetail/Members/MembersFilter.vue
<template>
  <div class="card">
    <div class="card-header">Filter</div>
    <div class="card-body">
      <el-form class="members-filter" label-position="top">
        <el-row class="wrap-row" :gutter="20">
          <el-col :span="5">
            <el-form-item label="Entity type">
              <el-select filterable clearable v-model="form.entityType">
                <el-option v-for="entityClass in entityClassOptions" :key="entityClass.value" :label="entityClass.label" :value="entityClass.value"> </el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="5">
            <el-form-item label="Action Type">
              <el-select v-model="form.actionType" placeholder="Action Type">
                <el-option v-for="actionType in actionTypeOptions" :key="actionType" :label="actionType" :value="actionType" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="5">
            <el-form-item label="Version check result">
              <el-select clearable v-model="form.versionCheckResult" placeholder="Please select">
                <el-option label="True" :value="true" />
                <el-option label="False" :value="false" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="5">
            <el-form-item label="Sort">
              <el-select v-model="form.sort" placeholder="Sort">
                <el-option label="Asc" value="ASC" />
                <el-option label="Desc" value="DESC" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col class="action-item" :span="4">
            <el-button @click="onSubmit" :loading="isLoading" type="primary">Load</el-button>
          </el-col>
        </el-row>
      </el-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import {useProcessingStore} from "../../../stores/processing";

const emit = defineEmits(["change"]);
const props = defineProps({ isLoading: { default: false } });
const processingStore = useProcessingStore();
function entitiesListPossible() {
  return processingStore.entitiesListPossible();
}

let actionTypeOptions = ref(["ALL", "READ", "UPDATE", "REMOVE"]);

let entityClassOptions = ref([]);

let form = ref({
  entityType: "",
  actionType: "ALL",
  versionCheckResult: null,
  sort: "ASC"
});

function onSubmit() {
  emit("change", form.value);
}
loadEntityClass();

async function loadEntityClass() {
  const { data } = await entitiesListPossible();

  entityClassOptions.value = data.map((el: string) => ({
    label: el,
    value: el
  }));
}

defineExpose({ form });
</script>

<style lang="scss">
.members-filter {
  .el-form-item__label {
    margin-bottom: 0 !important;
    padding-bottom: 0 !important;
  }

  .wrap-row {
    position: relative;

    .action-item {
      position: relative;
      left: 0;
      top: 22px;
    }
  }
}
</style>
