// react-project/packages/processing-manager-react/src/components/transition-detail/MembersTable.tsx
/**
 * Members Table Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionDetail/Members/MembersTable.vue
 */

import React from 'react';
import { Card, Table, Spin, Space } from 'antd';
import { Link, useParams } from 'react-router-dom';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';

interface MemberRow {
  entityType: string;
  entityId: string;
  actionType: string;
  versionCheckTimeMillis: number;
  versionCheckResult: boolean;
}

interface MembersTableProps {
  tableData: MemberRow[];
  isLoading?: boolean;
}

export const MembersTable: React.FC<MembersTableProps> = ({ tableData, isLoading = false }) => {
  const { name } = useParams<{ name: string }>();

  const convertTime = (mkTime: number) => {
    return dayjs(mkTime).format('YYYY-MM-DD HH:mm:ss.SSS');
  };

  const columns: ColumnsType<MemberRow> = [
    {
      title: 'Entity Type',
      dataIndex: 'entityType',
      key: 'entityType',
      width: 330,
      fixed: 'left',
    },
    {
      title: 'Entity Id',
      dataIndex: 'entityId',
      key: 'entityId',
      width: 330,
    },
    {
      title: 'Action Type',
      dataIndex: 'actionType',
      key: 'actionType',
      width: 130,
    },
    {
      title: 'Version Check Time',
      dataIndex: 'versionCheckTimeMillis',
      key: 'versionCheckTimeMillis',
      width: 200,
      render: (versionCheckTimeMillis: number) => convertTime(versionCheckTimeMillis),
    },
    {
      title: 'Version Check Result',
      dataIndex: 'versionCheckResult',
      key: 'versionCheckResult',
      width: 200,
      render: (versionCheckResult: boolean) => (versionCheckResult ? 'Yes' : 'No'),
    },
    {
      title: 'Operations',
      key: 'operations',
      fixed: 'right',
      width: 300,
      className: 'actions-buttons',
      render: (_, record: MemberRow) => (
        <Space size="middle">
          <Link
            to={`/nodes/${name}/versions?entityId=${record.entityId}&type=${record.entityType}`}
          >
            Versions
          </Link>
          <Link to={`/nodes/${name}/changes?entityId=${record.entityId}&type=${record.entityType}`}>
            Changes
          </Link>
          <Link
            to={`/nodes/${name}/entity-state-machine?entityId=${record.entityId}&type=${record.entityType}`}
          >
            State Machine
          </Link>
        </Space>
      ),
    },
  ];

  return (
    <Card title="Transaction members with version check results">
      <Spin spinning={isLoading}>
        <Table
          columns={columns}
          dataSource={tableData}
          rowKey={(record, index) => `${record.entityId}-${index}`}
          bordered
          pagination={false}
          scroll={{ x: 'max-content' }}
        />
      </Spin>
    </Card>
  );
};

export default MembersTable;

// .old_project /packages/processing-manager/src/components/PmTransitionDetail/Members/MembersTable.vue
<template>
  <div class="card">
    <div class="card-header">Transaction members with version check results</div>
    <div class="card-body" v-loading="isLoading">
      <el-table border :data="tableData" style="width: 100%">
        <el-table-column prop="entityType" label="Entity Type" width="330" fixed> </el-table-column>
        <el-table-column prop="entityId" label="Entity Id" width="330"> </el-table-column>
        <el-table-column prop="actionType" label="Action Type" width="130"> </el-table-column>
        <el-table-column prop="versionCheckTimeMillis" label="Version Check Time" width="200">
          <template v-slot:default="{ row }">
            {{ convertTime(row.versionCheckTimeMillis) }}
          </template>
        </el-table-column>
        <el-table-column prop="versionCheckResult" label="Version Check Result" width="200">
          <template v-slot:default="{ row }">
            {{ $filters.boolean(row.versionCheckResult) }}
          </template>
        </el-table-column>
        <el-table-column fixed="right" label="Operations" class-name="actions-buttons" width="300">
          <template v-slot:default="scope">
            <router-link :to="onVersions(scope)" type="text" size="small">Versions</router-link>
            <router-link :to="onChanges(scope)" type="text" size="small">Changes</router-link>
            <router-link :to="onStateMachine(scope)" type="text" size="small">State Machine </router-link>
          </template>
        </el-table-column>
      </el-table>
    </div>
  </div>
</template>

<script setup lang="ts">
import moment from "moment";
import {useRoute} from "vue-router";

const props = defineProps({ isLoading: { default: false }, tableData: { default: () => [] } });
const route = useRoute();

function convertTime(mkTime: number) {
  return moment(mkTime).format("YYYY-MM-DD HH:mm:ss.SSS");
}

function onVersions({ row }: { row: any }) {
  const { params } = route;
  return `/processing-ui/nodes/${params.name}/versions?entityId=${row.entityId}&type=${row.entityType}`;
}

function onChanges({ row }: { row: any }) {
  const { params } = route;
  return `/processing-ui/nodes/${params.name}/changes?entityId=${row.entityId}&type=${row.entityType}`;
}

function onStateMachine({ row }: { row: any }) {
  const { params } = route;
  return `/processing-ui/nodes/${params.name}/entity-state-machine?entityId=${row.entityId}&type=${row.entityType}`;
}
</script>
