// packages/processing-manager-react/src/components/common/ErrorViewActions.tsx
/**
 * Error View Actions Component
 * Migrated from @cyoda/processing-manager/src/components/ErrorViewActions/ErrorViewActions.vue
 */

import React from 'react';
import { Button, Dropdown, Modal, message } from 'antd';
import { DownOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { useLocation } from 'react-router-dom';
import { useProcessingQueueForceMarkProcessed } from '../../hooks';

interface ErrorViewActionsProps {
  onReload?: () => void;
}

export const ErrorViewActions: React.FC<ErrorViewActionsProps> = ({ onReload }) => {
  const location = useLocation();
  const { mutateAsync: forceMarkProcessed } = useProcessingQueueForceMarkProcessed();

  const handleForceMarkProcessed = () => {
    Modal.confirm({
      title: 'Warning',
      content: 'Force mark processed. Continue?',
      okText: 'OK',
      cancelText: 'Cancel',
      onOk: async () => {
        try {
          const params = new URLSearchParams(location.search);
          await forceMarkProcessed({ params: Object.fromEntries(params) });
          onReload?.();
          message.success('Force mark processed completed');
        } catch (error) {
          message.error('Force mark processed failed');
        }
      },
      onCancel: () => {
        message.info('Force mark processed canceled');
      },
    });
  };

  const handleResubmitWithErrorEvent = () => {
    Modal.confirm({
      title: 'Warning',
      content: 'Resubmit Events For Error(with error event). Continue?',
      okText: 'OK',
      cancelText: 'Cancel',
      onOk: async () => {
        // TODO: Implement resubmit with error event
        message.success('Resubmit Events For Error(with error event) completed');
      },
      onCancel: () => {
        message.info('Resubmit Events For Error(with error event) canceled');
      },
    });
  };

  const handleResubmitWithoutErrorEvent = () => {
    Modal.confirm({
      title: 'Warning',
      content: 'Resubmit Events For Error(without error event). Continue?',
      okText: 'OK',
      cancelText: 'Cancel',
      onOk: async () => {
        // TODO: Implement resubmit without error event
        message.success('Resubmit Events For Error(without error event) completed');
      },
      onCancel: () => {
        message.info('Resubmit Events For Error(without error event) canceled');
      },
    });
  };

  const handleMenuClick: MenuProps['onClick'] = ({ key }) => {
    switch (key) {
      case 'forceMarkProcessed':
        handleForceMarkProcessed();
        break;
      case 'resubmitWithErrorEvent':
        handleResubmitWithErrorEvent();
        break;
      case 'resubmitWithoutErrorEvent':
        handleResubmitWithoutErrorEvent();
        break;
    }
  };

  const items: MenuProps['items'] = [
    {
      key: 'forceMarkProcessed',
      label: 'Force mark processed',
    },
    {
      key: 'resubmitWithErrorEvent',
      label: 'Resubmit Events For Error(with error event)',
    },
    {
      key: 'resubmitWithoutErrorEvent',
      label: 'Resubmit Events For Error(without error event)',
    },
  ];

  return (
    <Dropdown menu={{ items, onClick: handleMenuClick }} trigger={['click']}>
      <Button type="primary">
        Actions <DownOutlined />
      </Button>
    </Dropdown>
  );
};

export default ErrorViewActions;

// .old_project /packages/processing-manager/src/components/ErrorViewActions/ErrorViewActions.vue
<template>
  <el-dropdown trigger="click" @command="handleClear">
    <el-button type="primary"> Actions <i class="el-icon-arrow-down el-icon--right"></i></el-button>
    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item command="forceMarkProcessed">Force mark processed</el-dropdown-item>
        <el-dropdown-item command="resubmitWithErrorEvent">Resubmit Events For Error(with error
          event)
        </el-dropdown-item>
        <el-dropdown-item command="resubmitWithoutErrorEvent">Resubmit Events For Error(without
          error event)
        </el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
</template>

<script setup lang="ts">
import {ElMessage, ElMessageBox} from "element-plus";
import {useRoute} from "vue-router";
import {useProcessingStore} from "../../stores/processing";

const route = useRoute();
const processingStore = useProcessingStore();
const emit=defineEmits(['reload']);

function processingQueueForceMarkProcessed(value) {
  return processingStore.processingQueueForceMarkProcessed(value);
}

function handleClear(command: string) {
  if (command === "forceMarkProcessed") {
    onForceMarkProcessed();
  } else if (command === "resubmitWithErrorEvent") {
    onResubmitWithErrorEvent();
  } else if (command === "resubmitWithoutErrorEvent") {
    onResubmitWithoutErrorEvent();
  }
}

function onForceMarkProcessed() {
  ElMessageBox.confirm("Force mark processed. Continue?", "Warning", {
    confirmButtonText: "OK",
    cancelButtonText: "Cancel",
    type: "warning"
  })
    .then(async () => {
      await processingQueueForceMarkProcessed({
        params: route.query
      });
      emit("reload");
      ElMessage({
        type: "success",
        message: "Force mark processed completed"
      });
    })
    .catch(() => {
      ElMessage({
        type: "info",
        message: "Force mark processed canceled"
      });
    });
}

function onResubmitWithErrorEvent() {
  ElMessageBox.confirm("Resubmit Events For Error(with error event). Continue?", "Warning", {
    confirmButtonText: "OK",
    cancelButtonText: "Cancel",
    type: "warning"
  })
    .then(async () => {
      ElMessage({
        type: "success",
        message: "Resubmit Events For Error(with error event) completed"
      });
    })
    .catch(() => {
      ElMessage({
        type: "info",
        message: "Resubmit Events For Error(with error event) canceled"
      });
    });
}

function onResubmitWithoutErrorEvent() {
  ElMessageBox.confirm("Resubmit Events For Error(without error event). Continue?", "Warning", {
    confirmButtonText: "OK",
    cancelButtonText: "Cancel",
    type: "warning"
  })
    .then(async () => {
      ElMessage({
        type: "success",
        message: "Resubmit Events For Error(without error event) completed"
      });
    })
    .catch(() => {
      ElMessage({
        type: "info",
        message: "Resubmit Events For Error(without error event) canceled"
      });
    });
}
</script>

<style scoped>
svg {
  margin-right: 5px;
}
</style>
