// .old_project /packages/cyoda-ui-lib/src/components-library/elements/TasksNotifications/TasksNotifications.vue
<template>
  <div></div>
</template>

<script setup lang="ts">
import {useAuthStore} from "@cyoda/ui-lib/src/stores/auth";
import {ElNotification} from "element-plus";
import {useRoute} from "vue-router";
import {ref, computed, watch, onBeforeUnmount} from "vue";

import _ from "lodash";
import HelperConstants from "../../../helpers/HelperConstants";
import {EventSourcePolyfill} from "event-source-polyfill";
import eventBus from "../../../plugins/eventBus";
import {useTasksStore} from "@cyoda/tasks/src/stores/tasks";

const route = useRoute();
const tasksStore = useTasksStore();
const authStore = useAuthStore();
const isApplyRealData = computed(() => {
  return tasksStore.isApplyRealData;
});
const token = computed(() => {
  return authStore.token;
});

function getAllTasks(value) {
  return tasksStore.getAllTasks(value);
}

const allTasks = ref(undefined);
const intervalId = ref(undefined);
const source = ref(undefined);
const lastTaskTime = ref(undefined);
const isLoading = ref<boolean>(false);

onBeforeUnmount(() => {
  stopAjaxEventSource();
  stopEventSource();
});

async function runAjaxEventSource() {
  if (intervalId.value === undefined) {
    await getAllTasksRequests();

    intervalId.value = setInterval(async () => {
      if (isLoading.value) return;

      isLoading.value = true;
      await getAllTasksRequests();
      isLoading.value = false;
    }, 5000);
  }
}

async function getAllTasksRequests() {
  const data = await getAllTasks({from: lastTaskTime.value});
  if (data.length === 0) return;
  lastTaskTime.value = data[data.length - 1].createdDatetime;
  if (allTasks.value === undefined) {
    allTasks.value = data;
  } else {
    const differences = _.differenceBy(data, allTasks.value, "id");
    allTasks.value = data;
    if (differences.length > 0) {
      ElNotification({
        title: "Tasks",
        dangerouslyUseHTMLString: true,
        onClick: () => {
          window.open(`/tasks`, "_blank");
        },
        message: `Was added ${differences.length} new task(s)<br/>
                    <strong class="task-strong-link-notification">Open All Tasks</strong>`,
        type: "success"
      });
      differences.forEach((el) => {
        eventBus.$emit(HelperConstants.NEWTASKS, {alertTask: el});
      });
    }
  }
}

function stopAjaxEventSource() {
  if (!intervalId.value) return;
  clearInterval(intervalId.value);
  intervalId.value = undefined;
}

watch(
  isApplyRealData,
  (val) => {
    if (val) {
      runEventSource();
    } else {
      stopEventSource();
      stopAjaxEventSource();
    }
  },
  {immediate: true}
);

function runEventSource() {
  if (token.value) {
    source.value = new EventSourcePolyfill(`${_.trimEnd(import.meta.env.VITE_APP_API_BASE, "/")}/alerts/tasks/emit`, {
      headers: {
        Authorization: `Bearer ${token.value}`,
        Accept: "*/*"
      }
    });

    source.value.addEventListener("error", (e) => {
      if (source.value) source.value.close();
      runAjaxEventSource();
    });

    const debounceMethod = _.debounce((task) => {
      if (route.params.id === task.alertTask.id) return;

      ElNotification({
        title: "Tasks",
        dangerouslyUseHTMLString: true,
        onClick: () => {
          window.open(`/tasks/${task.alertTask.id}`, "_blank");
        },
        message: `Was added new task(s)<br/>
                    <strong class="task-strong-link-notification">Open task</strong>`,
        type: "success"
      });
    }, 500);

    source.value.addEventListener(
      "message",
      (event: any) => {
        const task = JSON.parse(event.data);
        if (task.previousState === "None") {
          debounceMethod(task);
        }
        eventBus.$emit(HelperConstants.NEWTASKS, task);
      },
      false
    );
  }
}

function stopEventSource() {
  if (source.value) source.value.close();
  source.value = undefined;
}

function throttleNewTasksMessages() {
  return _.throttle(() => {
    ElNotification({
      title: "Tasks",
      message: `Was added new task(s)`,
      type: "success"
    });
  }, 5000);
}
</script>

<style lang="scss">
.task-strong-link-notification {
  color: #606266;
  cursor: pointer;

  &:hover {
    border-bottom: 1px solid #606266 !important;
  }
}
</style>

// react-project/packages/ui-lib-react/src/components/TasksNotifications/TasksNotifications.tsx
import React, { useEffect, useRef, useState } from 'react'
import { notification } from 'antd'
import { EventSourcePolyfill } from 'event-source-polyfill'
import _ from 'lodash'
import './TasksNotifications.scss'

export interface Task {
  id: string
  createdDatetime: string
  previousState?: string
  [key: string]: any
}

export interface TasksNotificationsProps {
  /** Whether to enable real-time notifications */
  enabled?: boolean
  /** Authentication token for SSE connection */
  token?: string
  /** Base API URL */
  apiBase?: string
  /** Callback to fetch all tasks */
  onFetchTasks?: (params: { from?: string }) => Promise<Task[]>
  /** Callback when new task is received */
  onNewTask?: (task: Task) => void
  /** Current route ID (to avoid showing notification for current task) */
  currentTaskId?: string
  /** Polling interval in milliseconds (fallback when SSE fails) */
  pollingInterval?: number
}

/**
 * TasksNotifications Component
 * Handles real-time task notifications via Server-Sent Events (SSE)
 * Falls back to polling if SSE connection fails
 * 
 * Migrated from Vue: .old_project/packages/cyoda-ui-lib/src/components-library/elements/TasksNotifications/TasksNotifications.vue
 */
export const TasksNotifications: React.FC<TasksNotificationsProps> = ({
  enabled = false,
  token,
  apiBase = import.meta.env.VITE_APP_API_BASE || '',
  onFetchTasks,
  onNewTask,
  currentTaskId,
  pollingInterval = 5000
}) => {
  const [allTasks, setAllTasks] = useState<Task[] | undefined>(undefined)
  const [lastTaskTime, setLastTaskTime] = useState<string | undefined>(undefined)
  const [isLoading, setIsLoading] = useState(false)
  
  const eventSourceRef = useRef<EventSourcePolyfill | null>(null)
  const intervalRef = useRef<NodeJS.Timeout | null>(null)

  // Fetch all tasks
  const getAllTasksRequests = async () => {
    if (!onFetchTasks) return

    const data = await onFetchTasks({ from: lastTaskTime })
    if (data.length === 0) return

    setLastTaskTime(data[data.length - 1].createdDatetime)

    if (allTasks === undefined) {
      setAllTasks(data)
    } else {
      const differences = _.differenceBy(data, allTasks, 'id')
      setAllTasks(data)

      if (differences.length > 0) {
        notification.success({
          message: 'Tasks',
          description: (
            <div>
              Was added {differences.length} new task(s)
              <br />
              <strong
                className="task-strong-link-notification"
                onClick={() => window.open('/tasks', '_blank')}
              >
                Open All Tasks
              </strong>
            </div>
          ),
          onClick: () => window.open('/tasks', '_blank')
        })

        differences.forEach(task => {
          onNewTask?.(task)
        })
      }
    }
  }

  // Start polling (fallback when SSE fails)
  const startPolling = async () => {
    if (intervalRef.current) return

    await getAllTasksRequests()

    intervalRef.current = setInterval(async () => {
      if (isLoading) return

      setIsLoading(true)
      await getAllTasksRequests()
      setIsLoading(false)
    }, pollingInterval)
  }

  // Stop polling
  const stopPolling = () => {
    if (intervalRef.current) {
      clearInterval(intervalRef.current)
      intervalRef.current = null
    }
  }

  // Start SSE connection
  const startEventSource = () => {
    if (!token) return

    const url = `${_.trimEnd(apiBase, '/')}/alerts/tasks/emit`
    
    eventSourceRef.current = new EventSourcePolyfill(url, {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: '*/*'
      }
    })

    // Handle errors - fall back to polling
    eventSourceRef.current.addEventListener('error', () => {
      if (eventSourceRef.current) {
        eventSourceRef.current.close()
        eventSourceRef.current = null
      }
      startPolling()
    })

    // Handle messages
    const debouncedNotification = _.debounce((task: Task) => {
      if (currentTaskId === task.id) return

      notification.success({
        message: 'Tasks',
        description: (
          <div>
            Was added new task(s)
            <br />
            <strong
              className="task-strong-link-notification"
              onClick={() => window.open(`/tasks/${task.id}`, '_blank')}
            >
              Open task
            </strong>
          </div>
        ),
        onClick: () => window.open(`/tasks/${task.id}`, '_blank')
      })
    }, 500)

    eventSourceRef.current.addEventListener('message', (event: any) => {
      const task = JSON.parse(event.data)
      
      if (task.previousState === 'None') {
        debouncedNotification(task)
      }
      
      onNewTask?.(task)
    })
  }

  // Stop SSE connection
  const stopEventSource = () => {
    if (eventSourceRef.current) {
      eventSourceRef.current.close()
      eventSourceRef.current = null
    }
  }

  // Main effect - start/stop based on enabled flag
  useEffect(() => {
    if (enabled) {
      startEventSource()
    } else {
      stopEventSource()
      stopPolling()
    }

    return () => {
      stopEventSource()
      stopPolling()
    }
  }, [enabled, token, apiBase])

  // This component doesn't render anything visible
  return null
}
