// react-project/packages/ui-lib-react/src/components/StateMachineConsistency/StateMachineConsistency.tsx
import React, { useState, useRef } from 'react'
import { Button } from 'antd'
import './StateMachineConsistency.scss'

export interface StateMachineConsistencyDialogRef {
  dialogVisible: boolean
  setDialogVisible: (visible: boolean) => void
}

export interface StateMachineConsistencyProps {
  onCheckConsistency?: () => Promise<any>
  renderDialog?: (data: any, ref: React.RefObject<StateMachineConsistencyDialogRef>) => React.ReactNode
  className?: string
}

/**
 * StateMachineConsistency Component
 * Main component for checking state machine consistency
 */
export const StateMachineConsistency: React.FC<StateMachineConsistencyProps> = ({
  onCheckConsistency,
  renderDialog,
  className = ''
}) => {
  const [isLoading, setIsLoading] = useState(false)
  const [data, setData] = useState<any>({})
  const dialogRef = useRef<StateMachineConsistencyDialogRef>(null)

  const handleCheckConsistency = async () => {
    try {
      setIsLoading(true)
      if (onCheckConsistency) {
        const result = await onCheckConsistency()
        setData(result)
        dialogRef.current?.setDialogVisible(true)
      }
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className={`state-machine-consistency ${className}`}>
      <div className="state-machine-consistency__actions">
        <Button 
          type="primary" 
          loading={isLoading}
          onClick={handleCheckConsistency}
        >
          Check Consistency
        </Button>
      </div>
      {renderDialog && renderDialog(data, dialogRef)}
    </div>
  )
}

// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/StateMachineConsistency/StateMachineConsistency.vue
<template>
  <div>
    <div class="actions">
      <el-button @click="onCheckConsistency" :loading="isLoading" type="primary">Check Consistency</el-button>
    </div>
    <StateMachineConsistencyDialog ref="stateMachineConsistencyDialogRef" :data="data" />
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

import * as api from "../../../api";
import StateMachineConsistencyDialog from "./StateMachineConsistencyDialog.vue";

const stateMachineConsistencyDialogRef = ref(null);

const isLoading = ref<boolean>(false);
let data = ref({});

async function onCheckConsistency() {
  try {
    isLoading.value = true;
    const { data } = await api.getStatemachineCheck();
    data.value = data;
    stateMachineConsistencyDialogRef.value.dialogVisible = true;
  } finally {
    isLoading.value = false;
  }
}
</script>

<style scoped>
.actions {
  text-align: right;
}
</style>
