// packages/cobi-react/src/components/DataMapper/DryRun/DryRunResultDialog.tsx
import React, { useState, useEffect, forwardRef, useImperativeHandle } from 'react';
import { Modal, Tabs, Alert } from 'antd';
import Prism from 'prismjs';
import 'prismjs/themes/prism.css';
import 'prismjs/components/prism-json';
import beautify from 'js-beautify';
import './DryRunResultDialog.css';

const { TabPane } = Tabs;

export interface DryRunResultDialogRef {
  open: (result: DryRunResult) => void;
}

interface DryRunResultDialogProps {}

export interface DryRunResult {
  mappedData?: any;
  entities?: any;
  parseStatistic?: any;
  tracerEvents?: any[];
}

const DryRunResultDialog = forwardRef<DryRunResultDialogRef, DryRunResultDialogProps>(
  (props, ref) => {
    const [visible, setVisible] = useState(false);
    const [result, setResult] = useState<DryRunResult | null>(null);
    const [activeTab, setActiveTab] = useState('mappedData');
    const [hasErrors, setHasErrors] = useState(false);

    useImperativeHandle(ref, () => ({
      open: (resultData: DryRunResult) => {
        setResult(resultData);
        setActiveTab('mappedData');
        checkForErrors(resultData);
        setVisible(true);
      },
    }));

    const checkForErrors = (resultData: DryRunResult) => {
      if (resultData.tracerEvents) {
        const errors = resultData.tracerEvents.filter(
          (event: any) => event.level === 'ERROR' || event.level === 'WARN'
        );
        setHasErrors(errors.length > 0);
      } else {
        setHasErrors(false);
      }
    };

    const formatJson = (data: any): string => {
      if (!data) return '';
      try {
        const jsonString = JSON.stringify(data, null, 2);
        return beautify.js(jsonString, { indent_size: 2 });
      } catch (error) {
        return String(data);
      }
    };

    const highlightJson = (json: string): string => {
      try {
        return Prism.highlight(json, Prism.languages.json, 'json');
      } catch (error) {
        return json;
      }
    };

    const handleClose = () => {
      setVisible(false);
      setResult(null);
    };

    if (!result) return null;

    return (
      <Modal
        title="Dry Run Result"
        open={visible}
        onCancel={handleClose}
        width="90%"
        footer={null}
        className="dry-run-result-dialog"
      >
        {hasErrors && (
          <Alert
            message="Errors Detected"
            description="The dry run encountered errors. Please check the Tracer Events tab for details."
            type="error"
            showIcon
            closable={false}
            style={{ marginBottom: 16 }}
          />
        )}

        <Tabs activeKey={activeTab} onChange={setActiveTab}>
          <TabPane tab="Mapped Data" key="mappedData">
            <div className="dry-run-result-content">
              <pre
                className="language-json"
                dangerouslySetInnerHTML={{
                  __html: highlightJson(formatJson(result.mappedData)),
                }}
              />
            </div>
          </TabPane>

          <TabPane tab="Entities" key="entities">
            <div className="dry-run-result-content">
              <pre
                className="language-json"
                dangerouslySetInnerHTML={{
                  __html: highlightJson(formatJson(result.entities)),
                }}
              />
            </div>
          </TabPane>

          <TabPane tab="Parse Statistic" key="parseStatistic">
            <div className="dry-run-result-content">
              <pre
                className="language-json"
                dangerouslySetInnerHTML={{
                  __html: highlightJson(formatJson(result.parseStatistic)),
                }}
              />
            </div>
          </TabPane>

          <TabPane tab="Tracer Events" key="tracerEvents">
            <div className="dry-run-result-content">
              {result.tracerEvents && result.tracerEvents.length > 0 ? (
                <div className="tracer-events-list">
                  {result.tracerEvents.map((event: any, index: number) => (
                    <div
                      key={index}
                      className={`tracer-event tracer-event-${event.level?.toLowerCase()}`}
                    >
                      <div className="tracer-event-header">
                        <span className="tracer-event-level">{event.level}</span>
                        <span className="tracer-event-time">{event.timestamp}</span>
                      </div>
                      <div className="tracer-event-message">{event.message}</div>
                      {event.details && (
                        <pre
                          className="tracer-event-details language-json"
                          dangerouslySetInnerHTML={{
                            __html: highlightJson(formatJson(event.details)),
                          }}
                        />
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                <div className="empty-state">No tracer events</div>
              )}
            </div>
          </TabPane>
        </Tabs>
      </Modal>
    );
  }
);

DryRunResultDialog.displayName = 'DryRunResultDialog';

export default DryRunResultDialog;

// .old_project /packages/cobi/src/components/DataMapper/DryRun/DryRunResultDialog.vue
<template>
  <el-dialog append-to-body :close-on-click-modal="false" title="Data" v-model="dialogVisible" width="80%">
    <el-alert v-if="isExistErrors" class="alert-box" title="Errors" type="error" :closable="false" show-icon>
      Tracer Events contain errors.
      <el-link @click="openErrors" type="danger">Open</el-link>
    </el-alert>
    <el-tabs v-model="activeTab">
      <el-tab-pane v-if="isUseModelsInfo" label="Mapped data" name="mappedData">
        <pre class="prism-detect-mappedData" :class="codeObjMappedData.class"><code :class="codeObjMappedData.class"
                                                               v-html="codeObjMappedData.code"></code></pre>
        <PrismDataDetector targetClass=".prism-detect-mappedData"/>
      </el-tab-pane>
      <el-tab-pane label="Entities" name="entities">
        <pre class="prism-detect" :class="codeObj.class"><code :class="codeObj.class"
                                                               v-html="codeObj.code"></code></pre>
        <PrismDataDetector targetClass=".prism-detect"/>
      </el-tab-pane>
      <el-tab-pane label="Parse Statistic" name="parse-statistic">
        <DryRunResultParseStatistics :data="dryRunData.parseStatistic"/>
      </el-tab-pane>
      <el-tab-pane label="Tracer Events" name="tracer-events">
        <DryRunResultTracerEvents ref="dryRunResultTracerEventsRef" :data="dryRunData.tracerEvents"/>
      </el-tab-pane>
    </el-tabs>
    <template #footer>
      <div class="dialog-footer">
        <el-button @click="dialogVisible = false">Close</el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import {ref, computed, watch} from "vue";

import "prismjs/themes/prism.css";

import beautify from "js-beautify";
import Prism from "prismjs";
import DryRunResultParseStatistics from "./DryRunResultParseStatistics.vue";
import DryRunResultTracerEvents from "./DryRunResultTracerEvents.vue";
import PrismDataDetector from "../../PrismDataDetector/PrismDataDetector.vue";
import HelperFeatureFlags from "@cyoda/ui-lib/src/helpers/HelperFeatureFlags";

const props = defineProps({
  dryRunData: {
    default: () => {
      return {};
    }
  }
});

const isUseModelsInfo = computed(() => {
  return HelperFeatureFlags.isUseModelsInfo();
})

const activeTab = ref(isUseModelsInfo.value ? 'mappedData' : 'entities');

const codeObj = computed(() => {
  const data = beautify.js(JSON.stringify(props.dryRunData.entities || {}).trim(), {
    indent_size: 2,
    space_in_empty_paren: true,
    wrap_line_length: 50
  });
  return {
    class: "language-javascript",
    code: Prism.highlight(data, Prism.languages.javascript, "javascript")
  };
});

const codeObjMappedData = computed(() => {
  const data = beautify.js(JSON.stringify(props.dryRunData.mappedData || {}).trim(), {
    indent_size: 2,
    space_in_empty_paren: true,
    wrap_line_length: 50
  });
  return {
    class: "language-javascript",
    code: Prism.highlight(data, Prism.languages.javascript, "javascript")
  };
});

const dryRunResultTracerEventsRef = ref(null);
const dialogVisible = ref<boolean>(false);

const isExistErrors = computed(() => {
  if (!props.dryRunData?.tracerEvents) return false;
  return props.dryRunData.tracerEvents.some((el) => el.level === 'ERROR');
})

function openErrors() {
  dryRunResultTracerEventsRef.value.form.filter = 'ERROR';
  activeTab.value = "tracer-events";
}

defineExpose({dialogVisible});

watch(dialogVisible, () => {
  if (!dialogVisible.value) reset()
})

function reset() {
  activeTab.value = isUseModelsInfo.value ? 'mappedData' : 'entities';
}
</script>

<style scoped lang="scss">
.alert-box {
  margin-bottom: 15px;
}
</style>
