// .old_project /packages/tasks/src/views/tasks/index/Tasks.vue
<template>
  <div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <div class="actions">
              <div>
                <h2>Filters</h2>
              </div>
              <div class="text-right">
                <el-button @click="toggleApplyRealData" v-if="isApplyRealData" key="applyRealDataTrue" type="warning">
                  Unsubscribe to live data
                  <font-awesome-icon icon="times"/>
                </el-button>
                <el-button @click="toggleApplyRealData" v-else key="applyRealDataFalse" type="primary">
                  Subscribe to live data
                  <font-awesome-icon icon="satellite"/>
                </el-button>
              </div>
            </div>
            <TasksFilter @changeFilter="onChangeFilter"/>
            <keep-alive>
              <TasksGrid :isApplyRealData="isApplyRealData" :filter="filter"/>
            </keep-alive>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import {ref, computed} from "vue";

import TasksFilter from "./TasksFilter.vue";
import TasksGrid from "./TasksGrid.vue";
import type {TaskFilterType} from "../types";
import {useTasksStore} from "../../../stores/tasks";


const tasksStore = useTasksStore();
const isApplyRealData = computed(() => {
  return tasksStore.isApplyRealData;
})

function setIsApplyRealData(isApplyRealData: boolean) {
  return tasksStore.setIsApplyRealData(isApplyRealData);
}

let filter = ref({});

function onChangeFilter(filterValue: TaskFilterType) {
  filter.value = filterValue;
}

function toggleApplyRealData() {
  setIsApplyRealData(!isApplyRealData.value);
}
</script>

<style lang="scss" scoped>
.actions {
  display: flex;
  justify-content: space-between;
  align-items: center;

  .text-right {
    text-align: right;
  }
}
</style>

// react-project/packages/tasks-react/src/pages/Tasks.tsx
/**
 * Tasks Page
 * Main tasks list page with filters and grid
 * Migrated from: .old_project/packages/tasks/src/views/tasks/index/Tasks.vue
 */

import React, { useState } from 'react';
import { Button, Card } from 'antd';
import { CloseOutlined, ApiOutlined } from '@ant-design/icons';
import { TasksFilter } from '../components/TasksFilter';
import { TasksGrid } from '../components/TasksGrid';
import { useTasksState } from '../hooks/useTasks';
import type { TaskFilterType } from '../types';

export const Tasks: React.FC = () => {
  const { isApplyRealData, setIsApplyRealData } = useTasksState();
  const [filter, setFilter] = useState<TaskFilterType>({});

  const handleChangeFilter = (filterValue: TaskFilterType) => {
    setFilter(filterValue);
  };

  const toggleApplyRealData = () => {
    setIsApplyRealData(!isApplyRealData);
  };

  return (
    <div>
      <div className="row">
        <div className="col-md-12">
          <Card>
            <div className="actions" style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 16 }}>
              <div>
                <h2>Filters</h2>
              </div>
              <div>
                {isApplyRealData ? (
                  <Button
                    type="default"
                    danger
                    icon={<CloseOutlined />}
                    onClick={toggleApplyRealData}
                  >
                    Unsubscribe to live data
                  </Button>
                ) : (
                  <Button
                    type="primary"
                    icon={<ApiOutlined />}
                    onClick={toggleApplyRealData}
                  >
                    Subscribe to live data
                  </Button>
                )}
              </div>
            </div>
            <TasksFilter onChangeFilter={handleChangeFilter} />
            <TasksGrid isApplyRealData={isApplyRealData} filter={filter} />
          </Card>
        </div>
      </div>
    </div>
  );
};
