// packages/cobi-react/src/components/DataMapper/FunctionalMappingSettings/FunctionalMappingDiff.tsx
import React, { useState, forwardRef, useImperativeHandle } from 'react';
import { Modal, Alert, Divider } from 'antd';
import beautify from 'js-beautify';
import './FunctionalMappingDiff.css';

export interface FunctionalMappingDiffRef {
  open: (oldObj: any, newObj: any) => void;
}

const FunctionalMappingDiff = forwardRef<FunctionalMappingDiffRef, {}>((props, ref) => {
  const [visible, setVisible] = useState(false);
  const [oldString, setOldString] = useState('');
  const [newString, setNewString] = useState('');

  useImperativeHandle(ref, () => ({
    open: (oldObj: any, newObj: any) => {
      setOldString(beautifyJs(oldObj));
      setNewString(beautifyJs(newObj));
      setVisible(true);
    },
  }));

  const beautifyJs = (obj: any) => {
    return beautify.js(JSON.stringify(obj).trim(), {
      indent_size: 2,
      space_in_empty_paren: true,
      wrap_line_length: 50,
    });
  };

  return (
    <Modal
      title="Inconsistent Configuration"
      open={visible}
      onOk={() => setVisible(false)}
      onCancel={() => setVisible(false)}
      width="90%"
      okText="Confirm"
      cancelButtonProps={{ style: { display: 'none' } }}
      maskClosable={false}
    >
      <Alert
        message="Warning"
        description="Inconsistent configuration translation. If you continue, you need to check the configuration for completeness."
        type="warning"
        showIcon
        closable={false}
      />
      <Divider />
      <div className="functional-mapping-diff">
        <div className="code-diff-title">
          <div className="left">
            <h3>Generated</h3>
          </div>
          <div className="right">
            <h3>From Server</h3>
          </div>
        </div>
        <div className="code-diff-content">
          <div className="code-section">
            <pre>{newString}</pre>
          </div>
          <div className="code-section">
            <pre>{oldString}</pre>
          </div>
        </div>
      </div>
    </Modal>
  );
});

FunctionalMappingDiff.displayName = 'FunctionalMappingDiff';

export default FunctionalMappingDiff;

// .old_project /packages/cobi/src/components/DataMapper/FunctionalMappingSettings/FunctionalMapping/FunctionalMappingDiff.vue
<template>
  <el-dialog appendToBody :close-on-click-modal="false" title="Inconsistent Configuration" v-model="dialogVisible" width="90%">
    <el-alert title="Warning" type="warning" description="Inconsistent configuration translation, if you continue you need to check the configuration for completeness." :closable="false" show-icon> </el-alert>
    <el-divider />
    <div class="functional-mapping-diff">
      <div class="code-diff-title">
        <div class="left">
          <h3>Generated</h3>
        </div>
        <div class="right">
          <h3>From Server</h3>
        </div>
      </div>
      <CyodaEditor :old-string="newString" :new-string="oldString" :diff="true" />
    </div>
    <template #footer>
    <span class="dialog-footer">
      <el-button type="primary" @click="dialogVisible = false">Confirm</el-button>
    </span>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref } from "vue";

import CyodaEditor from "@cyoda/ui-lib/src/components-library/elements/CyodaEditor/CyodaEditor.vue";

import beautify from "js-beautify";

const newString = ref<string>("");
const oldString = ref<string>("");

const dialogVisible = ref<boolean>(false);

function openForm(oldObj, newObj) {
  oldString.value = beautifyJs(oldObj);
  newString.value = beautifyJs(newObj);
  dialogVisible.value = true;
}

function beautifyJs(obj) {
  return beautify.js(JSON.stringify(obj).trim(), {
    indent_size: 2,
    space_in_empty_paren: true,
    wrap_line_length: 50
  });
}

defineExpose({ openForm });
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">
.code-diff-title {
  display: flex;
  margin-bottom: 10px;

  div {
    width: 50%;

    h3 {
      font-weight: bold;
    }
  }
}
</style>
