// react-project/packages/cobi-react/src/pages/DataManagementDashboard/components/ExecuteDialog/DataSourceConfigDialogRequest.tsx
import React, { forwardRef, useImperativeHandle, useState, useRef, useEffect, useMemo } from 'react';
import { Modal, Form, Switch, Select, Button, Tabs, Empty, Divider } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import DataSourceConfigDialogRequestOperation from './DataSourceConfigDialogRequestOperation';
import DataSourceConfigDialogResult, {
  DataSourceConfigDialogResultRef,
} from './DataSourceConfigDialogResult';
import DataSourceConfigDialogResultWithStatus, {
  DataSourceConfigDialogResultWithStatusRef,
} from './DataSourceConfigDialogResultWithStatus';
import DataToClipboard from '../../../../components/DataToClipboard/DataToClipboard';
import { HelperStorage } from '../../../../utils/storageHelper';
import { HelperConstants } from '../../../../utils/constants';
import * as dataSourceConfigApi from '../../../../api/dataSourceConfigApi';
import dayjs, { Dayjs } from 'dayjs';
import './DataSourceConfigDialogRequest.css';

const helperStorage = new HelperStorage();

interface DataSourceOperation {
  operation: string;
  request_fields: any;
  clientData: any;
}

interface FormData {
  data_source_operations: DataSourceOperation[];
  datasource_id: string;
  lastUpdated?: number;
}

interface FormSettings {
  operation: string | null;
  onlyState: boolean;
}

interface StatusObj {
  status: string;
  startTime: Dayjs | null;
  endTime: Dayjs | null;
  requestUuid: string | null;
}

export interface DataSourceConfigDialogRequestRef {
  openDialog: (dataSource: any, dataSourceConfigDto: any) => void;
}

const DataSourceConfigDialogRequest = forwardRef<DataSourceConfigDialogRequestRef, {}>((props, ref) => {
  const [dialogVisible, setDialogVisible] = useState(false);
  const [dataSource, setDataSource] = useState<any>({});
  const [dataSourceConfigDto, setDataSourceConfigDto] = useState<any>({});
  const [isLoading, setIsLoading] = useState(false);
  const [isLoadingState, setIsLoadingState] = useState(false);
  const [activeTab, setActiveTab] = useState<string | null>(null);
  const [resultData, setResultData] = useState<any>({});
  const [requestId, setRequestId] = useState<string>('');
  const [activeRequestFields, setActiveRequestFields] = useState<any>({});
  const [statusObj, setStatusObj] = useState<StatusObj>({
    status: '',
    startTime: null,
    endTime: null,
    requestUuid: null,
  });

  const [formSettings, setFormSettings] = useState<FormSettings>({
    operation: null,
    onlyState: false,
  });

  const [form, setForm] = useState<FormData>({
    data_source_operations: [],
    datasource_id: '',
  });

  const intervalIdRef = useRef<NodeJS.Timeout | null>(null);
  const intervalTime = 5000;
  const doneStatuses = ['DONE', 'PARTIALLY_DONE', 'AUTH_ERROR'];

  const dataSourceConfigDialogResultRef = useRef<DataSourceConfigDialogResultRef>(null);
  const dataSourceConfigDialogResultWithStatusRef =
    useRef<DataSourceConfigDialogResultWithStatusRef>(null);

  const statusObjDefault: StatusObj = {
    status: '',
    startTime: null,
    endTime: null,
    requestUuid: null,
  };

  useImperativeHandle(ref, () => ({
    openDialog: (dataSourceValue: any, dataSourceConfigDtoValue: any) => {
      setDataSource(dataSourceValue);
      setDataSourceConfigDto(dataSourceConfigDtoValue);
      setDialogVisible(true);

      // Load saved form data from localStorage
      const storageData = helperStorage.get(
        HelperConstants.getDataSourceConfigDialogRequestKey(dataSourceConfigDtoValue.id)
      );

      if (
        storageData &&
        storageData.datasource_id &&
        storageData.lastUpdated === dataSourceConfigDtoValue.lastUpdated
      ) {
        setForm(storageData);
        if (storageData.data_source_operations.length > 0) {
          setActiveTab(storageData.data_source_operations[0].operation);
        }
      }
    },
  }));

  // Initialize form with first endpoint
  useEffect(() => {
    if (
      form.data_source_operations.length === 0 &&
      dataSourceConfigDto &&
      dataSourceConfigDto.endpoints &&
      dataSourceConfigDto.endpoints.length > 0
    ) {
      addOperation(dataSourceConfigDto.endpoints[0].operation);
    }

    setForm((prev) => ({
      ...prev,
      datasource_id: dataSourceConfigDto.id || '',
    }));
  }, [dataSourceConfigDto]);

  // Save form to localStorage
  useEffect(() => {
    if (dataSourceConfigDto.id) {
      const formToSave = {
        ...form,
        lastUpdated: dataSourceConfigDto.lastUpdated,
      };
      helperStorage.set(
        HelperConstants.getDataSourceConfigDialogRequestKey(dataSourceConfigDto.id),
        formToSave
      );
    }
  }, [form, dataSourceConfigDto]);

  // Update active request fields when tab changes
  useEffect(() => {
    if (activeTab) {
      setActiveRequestFields(getActiveRequestFieldsForOperation(activeTab) || {});
    }
  }, [activeTab]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      onStop(false);
    };
  }, []);

  const operationOptions = useMemo(() => {
    if (!dataSourceConfigDto.endpoints) return [];

    const usedOperations = form.data_source_operations.map((el) => el.operation);

    return dataSourceConfigDto.endpoints
      .filter((el: any) => !usedOperations.includes(el.operation))
      .map((el: any) => ({
        value: el.operation,
        label: el.operation,
      }));
  }, [dataSourceConfigDto.endpoints, form.data_source_operations]);

  const computedTitle = `Dialog Request: ${dataSourceConfigDto.name || 'N/A'}`;

  const getActiveRequestFieldsForOperation = (operation: string) => {
    if (!dataSourceConfigDto || !dataSourceConfigDto.endpoints) return {};

    const endpointDataSourceConfigDto = dataSourceConfigDto.endpoints.find(
      (el: any) => el.operation === operation
    );
    const dataSourceOperation = dataSource.operations?.find((el: any) => el.operation === operation);
    const request_fields: any = {};

    const parameters = endpointDataSourceConfigDto?.parameters || [];
    const existParameters = parameters.map((el: any) => el.name);

    parameters.forEach((el: any) => {
      request_fields[el.name] = el.defaultValue;
    });

    if (dataSourceOperation) {
      dataSourceOperation.queryFields?.forEach((name: string) => {
        if (!existParameters.includes(name)) {
          request_fields[name] = '';
        }
      });
    }

    return request_fields;
  };

  const addOperation = (operation: string) => {
    const endpointDataSourceConfigDto = dataSourceConfigDto.endpoints.find(
      (el: any) => el.operation === operation
    );
    const request_fields = getActiveRequestFieldsForOperation(operation);

    setForm((prev) => ({
      ...prev,
      data_source_operations: [
        ...prev.data_source_operations,
        {
          operation: endpointDataSourceConfigDto.operation,
          request_fields,
          clientData: {},
        },
      ],
    }));

    setActiveTab(operation);
  };

  const onClickAddOperation = () => {
    if (formSettings.operation) {
      addOperation(formSettings.operation);
      setFormSettings((prev) => ({ ...prev, operation: null }));
    }
  };

  const removeTab = (operation: string) => {
    const index = form.data_source_operations.findIndex((el) => el.operation === operation);
    const nextIndex = index === 0 ? index + 1 : index - 1;

    if (form.data_source_operations[nextIndex]) {
      setActiveTab(form.data_source_operations[nextIndex].operation);
    }

    setForm((prev) => ({
      ...prev,
      data_source_operations: prev.data_source_operations.filter((_, i) => i !== index),
    }));
  };

  const resetStatus = () => {
    setStatusObj({ ...statusObjDefault });
  };

  const onStop = (runEvent = true) => {
    setIsLoading(false);
    if (intervalIdRef.current) {
      clearInterval(intervalIdRef.current);
      intervalIdRef.current = null;
    }
  };

  const loadList = async () => {
    const { data } = await dataSourceConfigApi.getListAll();
    return data;
  };

  const onRun = async () => {
    setIsLoading(true);
    setResultData({});
    resetStatus();
    let id = '';
    setRequestId('');

    const listConfigs: any[] = await loadList();

    try {
      const formValue = JSON.parse(JSON.stringify(form));
      delete formValue.lastUpdated;

      const dataSourceConfig: any = listConfigs.find((el) => el.id === formValue.datasource_id);

      for (const dataSourceOperation of formValue.data_source_operations) {
        const endpoint = dataSourceConfig.endpoints.find(
          (endpoint: any) => endpoint.operation === dataSourceOperation.operation
        );
        if (!endpoint) continue;
        if (!endpoint.hasOwnProperty('parameters')) continue;

        for (const key of Object.keys(dataSourceOperation.request_fields)) {
          const endpointParam = endpoint.parameters.find((el: any) => el.name === key);
          if (!endpointParam) continue;
          if (!dataSourceOperation.request_fields[key]) {
            delete dataSourceOperation.request_fields[key];
          }
        }
      }

      const { data } = await dataSourceConfigApi.request(formValue);
      id = data;
      setRequestId(id);
    } catch (e) {
      console.error(e);
      onStop();
      return;
    }

    if (formSettings.onlyState) {
      dataSourceConfigDialogResultWithStatusRef.current?.setDialogVisible(true);
      setDialogVisible(false);
    }

    doRequest(id);

    if (intervalIdRef.current) clearInterval(intervalIdRef.current);
    intervalIdRef.current = setInterval(async () => {
      doRequest(id);
    }, intervalTime);
  };

  const doRequest = async (id: string) => {
    if (formSettings.onlyState) {
      if (!statusObj.startTime) {
        setStatusObj((prev) => ({
          ...prev,
          startTime: dayjs(),
          requestUuid: id,
        }));
      }
      doRequestWithStatus(id);
    } else {
      doRequestWithResult(id);
    }
  };

  const doRequestWithResult = async (id: string) => {
    if (isLoadingState) return;

    let resultLocal = null;
    try {
      setIsLoadingState(true);
      const response = await dataSourceConfigApi.result(id);
      resultLocal = response.data;
    } catch (e) {
      onStop();
      return;
    } finally {
      setIsLoadingState(false);
    }

    if (doneStatuses.includes(resultLocal.state)) {
      onStop();
      setResultData(resultLocal);
      dataSourceConfigDialogResultRef.current?.setDialogVisible(true);
    }
  };

  const doRequestWithStatus = async (id: string) => {
    if (isLoadingState) return;

    let data = null;
    try {
      setIsLoadingState(true);
      const response = await dataSourceConfigApi.resultState(id);
      data = response.data;
    } catch (e) {
      onStop();
      return;
    } finally {
      setIsLoadingState(false);
    }

    setStatusObj((prev) => ({
      ...prev,
      status: data,
    }));

    if (doneStatuses.includes(data)) {
      setStatusObj((prev) => ({
        ...prev,
        endTime: dayjs(),
      }));
      onStop();
    }
  };

  const tabItems = form.data_source_operations.map((dataSourceOperation, index) => ({
    key: dataSourceOperation.operation,
    label: dataSourceOperation.operation,
    children: (
      <DataSourceConfigDialogRequestOperation
        key={dataSourceOperation.operation}
        dataSourceOperation={dataSourceOperation}
        activeRequestFields={activeRequestFields}
        index={index}
      />
    ),
    closable: true,
  }));

  return (
    <div className="data-source-config-dialog-request">
      <Modal
        title={
          <div className="wrap-header">
            <span className="el-dialog__title">{computedTitle}</span>
            {isLoading && requestId && (
              <>
                <Divider type="vertical" />
                Request UUID:&nbsp;
                <DataToClipboard value={requestId} />
              </>
            )}
          </div>
        }
        open={dialogVisible}
        onCancel={() => setDialogVisible(false)}
        width="70%"
        footer={
          <div>
            <Button onClick={() => setDialogVisible(false)}>Close</Button>
            {isLoading ? (
              <Button danger onClick={() => onStop()}>
                Stop
              </Button>
            ) : (
              <Button type="primary" onClick={onRun}>
                Run
              </Button>
            )}
          </div>
        }
        destroyOnClose
      >
        <Form layout="horizontal" labelCol={{ span: 6 }}>
          <Form.Item label="Return only state">
            <Switch
              checked={formSettings.onlyState}
              onChange={(checked) =>
                setFormSettings((prev) => ({ ...prev, onlyState: checked }))
              }
            />
          </Form.Item>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <Form.Item label="Operations" style={{ flex: 1, marginBottom: 0 }}>
              <Select
                value={formSettings.operation}
                onChange={(value) => setFormSettings((prev) => ({ ...prev, operation: value }))}
                placeholder="Select"
                allowClear
                options={operationOptions}
              />
            </Form.Item>
            <Button
              type="primary"
              icon={<PlusOutlined />}
              disabled={!formSettings.operation}
              onClick={onClickAddOperation}
            >
              Add
            </Button>
          </div>
        </Form>

        <Divider />

        {form.data_source_operations.length > 0 ? (
          <Tabs
            type="editable-card"
            activeKey={activeTab || undefined}
            onChange={setActiveTab}
            onEdit={(targetKey, action) => {
              if (action === 'remove') {
                removeTab(targetKey as string);
              }
            }}
            items={tabItems}
            hideAdd
          />
        ) : (
          <Empty description="Please select minimum one operation" />
        )}
      </Modal>

      <DataSourceConfigDialogResult
        ref={dataSourceConfigDialogResultRef}
        requestId={requestId}
        result={resultData}
        dataSourceConfigDto={dataSourceConfigDto}
      />

      <DataSourceConfigDialogResultWithStatus
        ref={dataSourceConfigDialogResultWithStatusRef}
        statusObj={statusObj}
        dataSourceConfigDto={dataSourceConfigDto}
        onStop={() => onStop()}
      />
    </div>
  );
});

DataSourceConfigDialogRequest.displayName = 'DataSourceConfigDialogRequest';

export default DataSourceConfigDialogRequest;

// .old_project /packages/cobi/src/components/DataSourceConfig/DataSourceConfigDialogRequest/DataSourceConfigDialogRequest.vue
<template>
  <div class="data-source-config-dialog-request">
    <el-dialog :close-on-click-modal="false" :title="computedTitle" v-model="dialogVisible" width="70%">
      <template #header>
        <div class="wrap-header">
          <span class="el-dialog__title">{{ computedTitle }}</span>
          <template v-if="isLoading && requestId">
            <el-divider direction="vertical"></el-divider>
            Request UUID:&nbsp;<DataToClipboard :value="requestId" />
          </template>
        </div>
      </template>
      <el-form v-loading="isLoading" :model="formSettings" label-width="140px">
        <el-form-item label="Return only state">
          <el-switch v-model="formSettings.onlyState"></el-switch>
        </el-form-item>
        <div class="flex flex-wrap-select">
          <el-form-item class="flex-select" label="Operations">
            <el-select clearable v-model="formSettings.operation" placeholder="Select">
              <el-option v-for="item in operationOptions" :key="item.value" :label="item.label" :value="item.value"></el-option>
            </el-select>
          </el-form-item>
          <div>
            <el-button :disabled="!formSettings.operation" @click="onClickAddOperation" type="primary">
              Add
              <font-awesome-icon icon="plus" />
            </el-button>
          </div>
        </div>
        <el-divider />

        <template v-if="form.data_source_operations.length > 0">
          <el-tabs v-model="activeTab" type="border-card" closable @tab-remove="removeTab">
            <template v-for="(dataSourceOperation, index) in form.data_source_operations">
              <el-tab-pane :label="dataSourceOperation.operation" :name="dataSourceOperation.operation">
                <DataSourceConfigDialogRequestOperation :key="dataSourceOperation.operation" :dataSourceOperation="dataSourceOperation" :activeRequestFields="activeRequestFields" :index="index" />
              </el-tab-pane>
            </template>
          </el-tabs>
        </template>
        <template v-else>
          <el-empty description="Please select minimum one operation"></el-empty>
        </template>
      </el-form>

      <template #footer>
      <span class="dialog-footer">
        <el-button @click="dialogVisible = false">Close</el-button>
        <template v-if="isLoading">
          <el-button type="danger" @click="onStop">Stop</el-button>
        </template>
        <template v-else>
          <el-button type="success" @click="onRun">Run</el-button>
        </template>
      </span>
      </template>
    </el-dialog>
    <DataSourceConfigDialogResult ref="dataSourceConfigDialogResultRef" :requestId="requestId" :result="resultData" :dataSourceConfigDto="dataSourceConfigDto" />

    <DataSourceConfigDialogResultWithStatus @stop="onStop" ref="dataSourceConfigDialogResultWithStatusRef" :statusObj="statusObj" :dataSourceConfigDto="dataSourceConfigDto" />
  </div>
</template>

<script setup lang="ts">
import { useDataSourceConfigStore } from "../../../stores/data-source-config";
import { ref, computed, watch, onBeforeUnmount } from "vue";

// import { DataSourceConfigDto } from "../DataSourceConfig";
import DataSourceConfigDialogRequestOperation from "./DataSourceConfigDialogRequestOperation.vue";
import DataSourceConfigDialogResult from "./DataSourceConfigDialogResult/DataSourceConfigDialogResult.vue";
import HelperStorage from "@cyoda/ui-lib/src/helpers/HelperStorage";
import moment from "moment";
import DataSourceConfigDialogResultWithStatus from "./DataSourceConfigDialogResultWithStatus.vue";
import HelperConstants from "../../../helpers/HelperConstants";
import DataToClipboard from "../../DataToClipboard/DataToClipboard.vue";
import eventBus from "@cyoda/ui-lib/src/plugins/eventBus";

const helperStorage = new HelperStorage();

const dataSourceConfigStore = useDataSourceConfigStore();
const operationOptions = computed(() => {
  if (!dataSourceConfigDto.value.endpoints) return [];
  const usedOperations = form.value.data_source_operations.map((el) => el.operation);
  return dataSourceConfigDto.value.endpoints

    .filter((el) => {
      return usedOperations.indexOf(el.operation) === -1;
    })
    .map((el) => {
      return {
        value: el.operation,
        label: el.operation
      };
    });
});
const computedTitle = computed(() => {
  return `Dialog Request: ${dataSourceConfigDto.value.name}`;
});

function request(form) {
  return dataSourceConfigStore.request(form);
}

function result(id) {
  return dataSourceConfigStore.result(id);
}

function resultState(id) {
  return dataSourceConfigStore.resultState(id);
}

function getListAll() {
  return dataSourceConfigStore.getListAll();
}

const dataSourceConfigDialogResultRef = ref(null);

const dataSourceConfigDialogResultWithStatusRef = ref(null);

const dialogVisible = ref<boolean>(false);

let dataSourceConfigDto = ref({});
let dataSource = ref({});

const isLoading = ref<boolean>(false);
const isLoadingState = ref<boolean>(false);
const intervalId = ref(null);
const intervalTime = ref(5000);

let formSettings = ref({
  operation: null,
  onlyState: false
});

let form = ref({
  data_source_operations: [],
  datasource_id: "",
  lastUpdated: 0
});

function openDialog(dataSourceValue, dataSourceConfigDtoValue) {
  dataSource.value = dataSourceValue;
  dataSourceConfigDto.value = dataSourceConfigDtoValue;
  dialogVisible.value = true;

  const storageData = helperStorage.get(HelperConstants.getDataSourceConfigDialogRequestKey(dataSourceConfigDto.value.id));
  if (storageData && storageData.datasource_id && storageData.lastUpdated === dataSourceConfigDto.value.lastUpdated) {
    form.value = storageData;
    if (form.value.data_source_operations.length > 0) activeTab.value = form.value.data_source_operations[0].operation;
  }
}

const activeTab = ref(null);
let resultData = ref({});
const requestId = ref<string>("");
let activeRequestFields = ref({});

let statusObj = ref({
  status: "",
  startTime: null,
  endTime: null,
  requestUuid: null
});

let statusObjDefault = ref(JSON.parse(JSON.stringify(statusObj.value)));

let doneStatuses = ref(["DONE", "PARTIALLY_DONE", "AUTH_ERROR"]);

watch(
  dataSourceConfigDto,
  () => {
    if (form.value.data_source_operations.length === 0 && dataSourceConfigDto.value && dataSourceConfigDto.value.endpoints.length > 0) {
      addOperation(dataSourceConfigDto.value.endpoints[0].operation);
    }

    form.value.datasource_id = dataSourceConfigDto.value.id;
  }
);

function addOperation(operation) {
  const endpointDataSourceConfigDto = dataSourceConfigDto.value.endpoints.find((el) => el.operation === operation)!;
  const request_fields = getActiveRequestFieldsForOperation(operation);

  form.value.data_source_operations.push({
    operation: endpointDataSourceConfigDto.operation,
    request_fields,
    clientData: {}
  });
  activeTab.value = operation;
}

function getActiveRequestFieldsForOperation(operation) {
  if (!dataSourceConfigDto.value || !dataSourceConfigDto.value.endpoints) return {};

  const endpointDataSourceConfigDto = dataSourceConfigDto.value.endpoints.find((el) => el.operation === operation)!;
  const dataSourceperation = dataSource.value.operations.find((el) => el.operation === operation)!;
  const request_fields = {};

  const parameters = endpointDataSourceConfigDto.parameters || [];
  const existParameters = parameters.map((el) => el.name);
  parameters.forEach((el) => {
    request_fields[el.name] = el.defaultValue;
  });

  if (dataSourceperation) {
    dataSourceperation.queryFields.forEach((name) => {
      if (!existParameters.includes(name)) {
        request_fields[name] = "";
      }
    });
  }
  return request_fields;
}

onBeforeUnmount(() => {
  onStop(false);
});

async function loadList() {
  const { data } = await getListAll();
  return data;
}

async function onRun() {
  isLoading.value = true;
  resultData.value = {};
  resetStatus();
  let id = "";
  requestId.value = "";
  const listConfigs: any[] = await loadList();
  try {
    const formValue = JSON.parse(JSON.stringify(form.value));
    delete formValue.lastUpdated;

    const dataSource: any = listConfigs.find((el) => el.id === formValue.datasource_id);
    for (const dataSourceOperation of formValue.data_source_operations) {
      const endpoint = dataSource.endpoints.find((endpoint) => endpoint.operation === dataSourceOperation.operation);
      if (!endpoint) continue;
      if (!endpoint.hasOwnProperty('parameters')) continue;for (const key of Object.keys(dataSourceOperation.request_fields)) {
        const endpointParam = endpoint.parameters.find((el) => el.name === key);
        if (!endpointParam) continue;
        if (!dataSourceOperation.request_fields[key]) {
          delete dataSourceOperation.request_fields[key];
        }
      }
    }
    const { data } = await request(formValue);
    id = data;
    requestId.value = id;
  } catch (e) {
    console.error(e);
    onStop();
    return;
  }

  if (formSettings.value.onlyState) {
    dataSourceConfigDialogResultWithStatusRef.value.dialogVisible = true;
    dialogVisible.value = false;
  }
  doRequest(id);

  if (intervalId.value) clearInterval(intervalId.value);
  intervalId.value = setInterval(async () => {
    doRequest(id);
  }, intervalTime.value);
}

function resetStatus() {
  statusObj.value = JSON.parse(JSON.stringify(statusObjDefault.value));
}

async function doRequest(id) {
  if (formSettings.value.onlyState) {
    if (!statusObj.value.startTime) {
      statusObj.value.startTime = moment();
      statusObj.value.requestUuid = id;
    }
    doRequestWithStatus(id);
  } else {
    doRequestWithResult(id);
  }
}

async function doRequestWithResult(id) {
  if (isLoadingState.value) return;

  let resultLocal = null;
  try {
    isLoadingState.value = true;
    const response = await result(id);
    resultLocal = response.data;
  } catch (e) {
    onStop();
    return;
  } finally {
    isLoadingState.value = false;
  }
  if (doneStatuses.value.includes(resultLocal.state)) {
    onStop();
    resultData.value = resultLocal;
    dataSourceConfigDialogResultRef.value.dialogVisible = true;
  }
}

async function doRequestWithStatus(id) {
  if (isLoadingState.value) return;

  let data = null;
  try {
    isLoadingState.value = true;
    const response = await resultState(id);
    data = response.data;
  } catch (e) {
    onStop();
    return;
  } finally {
    isLoadingState.value = false;
  }
  statusObj.value.status = data;
  if (doneStatuses.value.includes(data)) {
    statusObj.value.endTime = moment();
    onStop();
  }
}

function onStop(runEvent = true) {
  isLoading.value = false;
  if (runEvent) eventBus.$emit("connectionRun:stop");
  if (intervalId.value) {
    clearInterval(intervalId.value);
  }
  intervalId.value = null;
}

function onClickAddOperation() {
  addOperation(formSettings.value.operation);
  formSettings.value.operation = null;
}

function removeTab(operation) {
  const index = form.value.data_source_operations.findIndex((el) => el.operation === operation);
  let activeTabNew = null;
  const nextIndex = index === 0 ? index + 1 : index - 1;

  if (form.value.data_source_operations[nextIndex]) {
    activeTabNew = form.value.data_source_operations[nextIndex].operation;
    activeTab.value = activeTabNew;
  }

  form.value.data_source_operations.splice(index, 1);
}

watch(
  form,
  () => {
    form.value.lastUpdated = dataSourceConfigDto.value.lastUpdated;
    helperStorage.set(HelperConstants.getDataSourceConfigDialogRequestKey(dataSourceConfigDto.value.id), form.value);
  },
  { deep: true }
);

watch(
  activeTab,
  (value) => {
    activeRequestFields.value = getActiveRequestFieldsForOperation(value) || {};
  },
  { immediate: true }
);

const activeEndpoint = computed(()=>{
  if (!dataSourceConfigDto.value.endpoints) return {};
  // @ts-ignore
  return dataSourceConfigDto.value.endpoints.find((el) => el.operation === activeTab.value)
})

const parametersErrorDescription = computed(()=>{
  if (activeEndpoint.value.hasOwnProperty('parameters') || !activeEndpoint.value['@bean']) return null;
  return `For this type of endpoint, you cannot set additional parameters`;
})

defineExpose({ dialogVisible, dataSourceConfigDto, dataSource, openDialog });
</script>

<style lang="scss">
.data-source-config-dialog-request {
  .flex-wrap-select {
    align-items: center;
    display: flex;
  }

  .flex-select {
    flex-grow: 1;
    margin-bottom: 0 !important;
    padding-right: 15px;
  }

  .el-tabs__nav-prev,
  .el-tabs__nav-next {
    line-height: 39px !important;
  }

  .wrap-header {
    display: flex;
    align-items: center;
    line-height: 24px;
    font-size: 18px;
    color: #303133;
  }
}
</style>
