// packages/cobi-react/src/pages/DataSourceConfig/components/DialogEndpoint/DialogEndpointBlobStorage.tsx
import React, { useState, useRef } from 'react';
import { Form, Select, Button } from 'antd';
import { EditOutlined } from '@ant-design/icons';
import DialogEndpointFieldOperation from './Fields/DialogEndpointFieldOperation';
import BlobStorageParameters from '../BlobStorageParameters/BlobStorageParameters';
import DialogCreateDataMapping, {
  DialogCreateDataMappingRef,
} from '../../../DataManagementDashboard/components/DialogCreateDataMapping';
import './DialogEndpointBlobStorage.css';

interface DialogEndpointBlobStorageProps {
  endpointDto: any;
  listAllDataMappings: any[];
  onChange?: (values: any) => void;
}

const DialogEndpointBlobStorage: React.FC<DialogEndpointBlobStorageProps> = ({
  endpointDto,
  listAllDataMappings,
  onChange,
}) => {
  const dialogCreateDataMappingRef = useRef<DialogCreateDataMappingRef>(null);

  const dataMappingConfigOptions = listAllDataMappings.map((el) => ({
    value: el.id,
    label: el.name,
  }));

  const handleConsumerChange = (value: string) => {
    if (onChange) {
      onChange({
        ...endpointDto,
        consumerConfig: {
          ...endpointDto.consumerConfig,
          configId: value,
        },
      });
    }
  };

  const onEditMappingConfig = () => {
    dialogCreateDataMappingRef.current?.open();
  };

  return (
    <div className="dialog-endpoint-blob-storage">
      <DialogEndpointFieldOperation endpointDto={endpointDto} onChange={onChange} />

      <div className="flex-row">
        <div className="full-width">
          <Form.Item
            label="Consumer"
            name={['consumerConfig', 'configId']}
            rules={[{ required: true, message: 'Please select consumer' }]}
          >
            <Select
              value={endpointDto.consumerConfig?.configId}
              onChange={handleConsumerChange}
              placeholder="Select"
              allowClear
              showSearch
              filterOption={(input, option) =>
                (option?.label ?? '').toLowerCase().includes(input.toLowerCase())
              }
              options={dataMappingConfigOptions}
            />
          </Form.Item>
        </div>
        <div>
          <Button
            type="primary"
            icon={<EditOutlined />}
            disabled={!endpointDto.consumerConfig?.configId}
            onClick={onEditMappingConfig}
          >
            Edit
          </Button>
        </div>
      </div>

      <BlobStorageParameters
        parameters={endpointDto.parameters || []}
        onChange={(params) => {
          if (onChange) {
            onChange({ ...endpointDto, parameters: params });
          }
        }}
      />

      <DialogCreateDataMapping ref={dialogCreateDataMappingRef} />
    </div>
  );
};

export default DialogEndpointBlobStorage;

// .old_project /packages/cobi/src/components/DataSourceConfig/DialogEndpoint/DialogEndpointBlobStorage.vue
<template>
  <div class="dialog-endpoint-blob-storage">
    <DialogEndpointFieldOperation :endpointDto="endpointDto" />
    <div class="flex-row">
      <div class="full-width">
        <el-form-item label="Consumer" prop="consumerConfig.configId">
          <el-select filterable clearable v-model="endpointDto.consumerConfig.configId" placeholder="Select">
            <el-option v-for="item in dataMappingConfigOptions" :key="item.value" :label="item.label" :value="item.value"></el-option>
          </el-select>
        </el-form-item>
      </div>
      <div>
        <el-button :disabled="!endpointDto.consumerConfig.configId" @click="onEditMappingConfig" type="primary">
          Edit
          <font-awesome-icon icon="pencil-alt" />
        </el-button>
      </div>
    </div>

    <BlobStorageParameters :parameters="endpointDto.parameters" />
    <DialogCreateDataMapping v-if="dialogCreateDataMappingVisible" ref="dialogCreateDataMappingRef" />
  </div>
</template>

<script setup lang="ts">
import { ref, nextTick, computed } from "vue";

import DialogEndpointFieldOperation from "./Fields/DialogEndpointFieldOperation.vue";
import DialogCreateDataMapping from "../DialogCreateDataMapping.vue";
import BlobStorageParameters from "../BlobStorageParameters/BlobStorageParameters.vue";

const props = defineProps({
  endpointDto: {
    default: () => {
      return {};
    }
  },
  listAllDataMappings: {
    default: () => {
      return [];
    }
  }
});
const dataMappingConfigOptions = computed(() => {
  return props.listAllDataMappings.map((el) => {
    return {
      value: el.id,
      label: el.name
    };
  });
});

const dialogCreateDataMappingRef = ref(null);

const dialogCreateDataMappingVisible = ref<boolean>(true);

async function onEditMappingConfig() {
  dialogCreateDataMappingVisible.value = false;
  await nextTick();

  dialogCreateDataMappingVisible.value = true;
  await nextTick();
  dialogCreateDataMappingRef.value.dialogVisible = true;
  await nextTick();
  dialogCreateDataMappingRef.value.dataMapperEditRef.loadMappingById(props.endpointDto.consumerConfig.configId);
}

defineExpose({ dialogCreateDataMappingVisible });
</script>

<style lang="scss">
.dialog-endpoint-blob-storage {
  .flex-row {
    display: flex;

    .full-width {
      flex-grow: 1;
      margin-right: 15px;
    }
  }
}
</style>
