// packages/ui-lib-react/src/components/StateForm/StateForm.tsx
import React, { useState, useEffect } from 'react'
import { Form, Input, Button } from 'antd'
import './StateForm.scss'

const { TextArea } = Input

export interface StateFormData {
  name: string
  description: string
  entityClassName?: string
}

export interface StateFormProps {
  workflowId?: string | null
  stateId?: string
  entityClassName?: string
  persistedType?: string
  onLoadState?: (persistedType: string, workflowId: string, stateId: string) => Promise<StateFormData>
  onSubmit?: (persistedType: string, workflowId: string, stateId: string, data: StateFormData) => Promise<void>
  onStateTitle?: (title: string) => void
  onWorkflowTitle?: (title: string) => void
  onSubmitted?: () => void
  className?: string
}

/**
 * StateForm Component
 * Form for editing state machine states
 */
export const StateForm: React.FC<StateFormProps> = ({
  workflowId = null,
  stateId = '',
  entityClassName = '',
  persistedType = '',
  onLoadState,
  onSubmit,
  onStateTitle,
  onWorkflowTitle,
  onSubmitted,
  className = ''
}) => {
  const [form] = Form.useForm()
  const [formData, setFormData] = useState<StateFormData>({
    name: '',
    description: '',
    entityClassName
  })
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    const loadState = async () => {
      if (onLoadState && persistedType && workflowId && stateId) {
        try {
          const data = await onLoadState(persistedType, workflowId, stateId)
          setFormData(data)
          form.setFieldsValue(data)
        } catch (error) {
          console.error('Failed to load state:', error)
        }
      }
    }
    loadState()
  }, [stateId, workflowId, persistedType, onLoadState, form])

  useEffect(() => {
    const pageTitle = `State ${formData.name}`
    onStateTitle?.(pageTitle)
  }, [formData.name, onStateTitle])

  useEffect(() => {
    const workflowTitle = 'Workflow'
    onWorkflowTitle?.(workflowTitle)
  }, [onWorkflowTitle])

  const handleSubmit = async () => {
    try {
      await form.validateFields()
      const values = form.getFieldsValue()
      
      if (onSubmit && persistedType && workflowId && stateId) {
        setLoading(true)
        await onSubmit(persistedType, workflowId, stateId, values)
        onSubmitted?.()
      }
    } catch (error) {
      console.error('Form validation failed:', error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className={`state-form ${className}`}>
      <div className="state-form__title">
        <h2>{`State ${formData.name}`}</h2>
      </div>
      <Form
        form={form}
        layout="vertical"
        initialValues={formData}
      >
        <Form.Item
          label="Name"
          name="name"
          rules={[{ required: true, message: 'Please input name' }]}
        >
          <Input />
        </Form.Item>
        
        <Form.Item
          label="Description"
          name="description"
        >
          <TextArea
            autoSize={{ minRows: 3, maxRows: 6 }}
          />
        </Form.Item>

        <Button type="primary" onClick={handleSubmit} loading={loading}>
          Update State
        </Button>
      </Form>
    </div>
  )
}

// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/StateForm/StateForm.vue
<template>
  <transition name="fade" mode="out-in">
    <el-form :model="form" ref="formRef" :rules="rules" label-width="auto" label-position="top">
      <div class="wrap-title">
        <h2>{{ pageTitle }}</h2>
      </div>
      <el-form-item label="Name" prop="name">
        <el-input v-model="form.name"/>
      </el-form-item>
      <el-form-item label="Description" prop="description">
        <el-input
            v-model="form.description"
            :autosize="{ minRows: 3, maxRows: 6 }"
            type="textarea"
        />
      </el-form-item>

      <el-button type="primary" @click="onSubmit">
        Update State
      </el-button>
    </el-form>
  </transition>
</template>

<script setup lang="ts">
import {computed, watch, reactive, ref, onMounted} from "vue";

import {useStatemachineStore} from "@cyoda/statemachine/src/stores/statemachine";
import type {FormRules} from "element-plus";

const formRef = ref(null);
const props = defineProps({
  workflowId: {
    default: null,
  },
  stateId: {
    default: "",
  },
  entityClassName: {
    default: "",
  },
  persistedType: {
    default: "",
  }
});


const form = ref({
  name: "",
  description: "",
  entityClassName: props.entityClassName
})

const rules = reactive<FormRules<RuleForm>>({
  name: [
    {required: true, message: 'Please input name', trigger: 'blur'},
  ],
});

async function loadState(stateId) {
  const {data} = await statemachineStore.getState(props.persistedType, props.workflowId, stateId);
  form.value = data.Data;
}

onMounted(() => {
  loadState(props.stateId);
})

const emit = defineEmits(["update:stateTitle", "update:workflowTitle", "submitted"]);
const statemachineStore = useStatemachineStore();

const pageTitle = computed(() => {
  return `State ${form.name}`;
});

const workflowTitle = computed(() => {
  return "Workflow";
  // return meta.value.transition.workflowname || (workflow.value && workflow.value.name) || "Workflow";
});

async function onSubmit() {
  try {
    await formRef.value.validate();
    await statemachineStore.putState(props.persistedType, props.workflowId, props.stateId, form.value);
    emit("submitted");
  } catch (e) {
  }
}

watch(
    workflowTitle,
    (val: string) => {
      emit("update:workflowTitle", val);
    },
    {immediate: true}
);
</script>

<style lang="scss" scoped>
</style>
