// packages/cobi-react/src/pages/DataSourceConfig/components/DialogEndpointParameters/DialogEndpointParametersBlobStorage.tsx
import React, { forwardRef, useImperativeHandle, useState, useEffect } from 'react';
import { Modal, Form, Input, Switch } from 'antd';

interface BlobStorageParameter {
  name: string;
  required: boolean;
  defaultValue: string;
  secure: boolean;
  template: boolean;
  templateValue: string;
}

interface DialogEndpointParametersBlobStorageProps {
  parameters: BlobStorageParameter[];
  onChange?: (parameters: BlobStorageParameter[]) => void;
}

export interface DialogEndpointParametersBlobStorageRef {
  openDialogAndCreateNew: () => void;
  openDialogAndEditRecord: (data: BlobStorageParameter) => void;
}

const defaultParameter: BlobStorageParameter = {
  name: '',
  required: false,
  defaultValue: '',
  secure: false,
  template: false,
  templateValue: '',
};

const DialogEndpointParametersBlobStorage = forwardRef<
  DialogEndpointParametersBlobStorageRef,
  DialogEndpointParametersBlobStorageProps
>((props, ref) => {
  const { parameters, onChange } = props;
  const [form] = Form.useForm();
  const [dialogVisible, setDialogVisible] = useState(false);
  const [editingParameter, setEditingParameter] = useState<BlobStorageParameter | null>(null);
  const [isTemplate, setIsTemplate] = useState(false);

  useImperativeHandle(ref, () => ({
    openDialogAndCreateNew: () => {
      setEditingParameter(null);
      form.resetFields();
      form.setFieldsValue(defaultParameter);
      setIsTemplate(false);
      setDialogVisible(true);
    },
    openDialogAndEditRecord: (data: BlobStorageParameter) => {
      setEditingParameter(data);
      form.setFieldsValue(data);
      setIsTemplate(data.template || false);
      setDialogVisible(true);
    },
  }));

  const handleOk = async () => {
    try {
      const values = await form.validateFields();

      if (!onChange) return;

      if (editingParameter) {
        // Edit existing parameter
        const index = parameters.indexOf(editingParameter);
        if (index > -1) {
          const newParams = [...parameters];
          newParams[index] = values;
          onChange(newParams);
        }
      } else {
        // Add new parameter
        onChange([...parameters, values]);
      }

      setDialogVisible(false);
    } catch (error) {
      console.error('Validation failed:', error);
    }
  };

  return (
    <Modal
      title="Endpoint Parameters"
      open={dialogVisible}
      onCancel={() => setDialogVisible(false)}
      onOk={handleOk}
      okText={editingParameter ? 'Edit' : 'Apply'}
      width="90%"
      destroyOnClose
    >
      <Form form={form} layout="horizontal" labelCol={{ span: 6 }}>
        <Form.Item label="Required" name="required" valuePropName="checked">
          <Switch />
        </Form.Item>

        <Form.Item label="Secure" name="secure" valuePropName="checked">
          <Switch />
        </Form.Item>

        <Form.Item label="Template" name="template" valuePropName="checked">
          <Switch onChange={(checked) => setIsTemplate(checked)} />
        </Form.Item>

        <Form.Item
          label="Name"
          name="name"
          rules={[{ required: true, message: 'Please input name' }]}
        >
          <Input placeholder="Enter parameter name" />
        </Form.Item>

        <Form.Item
          label="Default Value"
          name="defaultValue"
          dependencies={['required']}
          rules={[
            ({ getFieldValue }) => ({
              required: !getFieldValue('required'),
              message: 'Please input Default Value',
            }),
          ]}
        >
          <Input placeholder="Enter default value" />
        </Form.Item>

        {isTemplate && (
          <Form.Item
            label="Template Value"
            name="templateValue"
            rules={[{ required: true, message: 'Please input Template Value' }]}
          >
            <Input placeholder="Enter template value" />
          </Form.Item>
        )}
      </Form>
    </Modal>
  );
});

DialogEndpointParametersBlobStorage.displayName = 'DialogEndpointParametersBlobStorage';

export default DialogEndpointParametersBlobStorage;

// .old_project /packages/cobi/src/components/DataSourceConfig/DialogEndpointParameters/DialogEndpointParametersBlobStorage.vue
<template>
  <div class="dialog-endpoint-parameters">
    <el-dialog append-to-body :close-on-click-modal="false" title="Endpoint Parameters" v-model="dialogVisible" width="90%">
      <el-form :model="blobStorageParameterDto" :rules="rules" ref="formRef" label-width="180px">
        <el-form-item label="Required" prop="required">
          <el-switch v-model="blobStorageParameterDto.required" />
        </el-form-item>

        <el-form-item label="Secure" prop="required">
          <el-switch v-model="blobStorageParameterDto.secure" />
        </el-form-item>

        <el-form-item label="Template" prop="required">
          <el-switch v-model="blobStorageParameterDto.template" />
        </el-form-item>

        <el-form-item label="Name" prop="name">
          <el-input v-model="blobStorageParameterDto.name" />
        </el-form-item>

        <el-form-item :rules="[{ required: !blobStorageParameterDto.required, message: 'Please select Default Value', trigger: 'change' }]" label="Default Value" prop="defaultValue">
          <el-input v-model="blobStorageParameterDto.defaultValue" />
        </el-form-item>

        <el-form-item v-if="blobStorageParameterDto.template" :rules="[{ required: blobStorageParameterDto.template, message: 'Please input Template Value', trigger: 'blur' }]" label="Template Value" prop="templateValue">
          <el-input v-model="blobStorageParameterDto.templateValue" />
        </el-form-item>
      </el-form>
      <template #footer>
      <span class="dialog-footer">
        <el-button @click="dialogVisible = false">Close</el-button>
        <template v-if="blobStorageParameterDtoBefore">
          <el-button type="success" @click="onEdit">Edit</el-button>
        </template>
        <template v-else>
          <el-button type="primary" @click="onSave">Apply</el-button>
        </template>
      </span>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, nextTick, watch } from "vue";

import type { BlobStorageParameterDto } from "../DataSourceConfig";

const props = defineProps({
  parameters: {
    default: function () {
      return [];
    }
  },
  placeholders: {
    default: () => {
      return [];
    }
  }
});

const formRef = ref(null);

const dialogVisible = ref<boolean>(false);

let rules = ref({
  name: [{ required: true, message: "Please input name", trigger: "change" }]
});

let blobStorageParameterDto = ref({
  name: "",
  required: false,
  defaultValue: "",
  secure: false,
  template: false,
  templateValue: ""
});

let blobStorageParameterDtoDefault = ref(JSON.parse(JSON.stringify(blobStorageParameterDto.value)));

const blobStorageParameterDtoBefore = ref(null);

function openDialogAndCreateNew() {
  dialogVisible.value = true;

  blobStorageParameterDtoBefore.value = null;
  blobStorageParameterDto.value = JSON.parse(JSON.stringify(blobStorageParameterDtoDefault.value));
}

function openDialogAndEditRecord(data: BlobStorageParameterDto) {
  dialogVisible.value = true;
  blobStorageParameterDtoBefore.value = data;
  blobStorageParameterDto.value = JSON.parse(JSON.stringify(data));
}

function onSave() {
  formRef.value.validate((valid) => {
    if (valid) {
      props.parameters.push(blobStorageParameterDto.value);
      dialogVisible.value = false;
    }
  });
}

function onEdit() {
  formRef.value.validate((valid) => {
    if (valid) {
      const index = props.parameters.indexOf(blobStorageParameterDtoBefore.value);
      if (index > -1) {
        props.parameters[index] = blobStorageParameterDto.value;

        dialogVisible.value = false;
      }
    }
  });
}

function suggestionsForName(queryString: string, cb: any) {
  let results: any[] = [];
  if (queryString) {
    results = props.placeholders.filter((el) => el.label.toLowerCase().indexOf(queryString.toLowerCase()));
  } else {
    results = props.placeholders;
  }
  cb(results);
}

watch(
  dialogVisible,
  async (val: boolean) => {
    if (val) {
      await nextTick();

      formRef.value.clearValidate();
    }
  }
);

watch(
  () => blobStorageParameterDto.value.template,
  (val: boolean) => {
    if (!val) {
      blobStorageParameterDto.value.templateValue = "";
    }
  }
);

defineExpose({ dialogVisible, openDialogAndCreateNew, openDialogAndEditRecord });
</script>
