// .old_project /packages/cobi/src/components/DataSourceConfig/DataSourceConfigDialogRequest/DataSourceConfigDialogResult/DataSourceConfigDialogResult.vue
<template>
  <el-dialog append-to-body :close-on-click-modal="false" :title="computedTitle" v-model="dialogVisible" width="80%">
    <DataSourceConfigDialogResultTabs :requestId="requestId" :result="result" />
    <template #footer>
    <span class="dialog-footer">
      <el-button @click="dialogVisible = false">Close</el-button>
    </span>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";

import "prismjs/themes/prism.css";
import DataSourceConfigDialogResultTabs from "./DataSourceConfigDialogResultTabs/DataSourceConfigDialogResultTabs.vue";
const props = defineProps({
  result: {
    default: () => {
      return {};
    }
  },
  dataSourceConfigDto: {
    default: () => {
      return {};
    }
  },
  requestId: {
    default: ""
  }
});
const computedTitle = computed(() => {
  return `Result: ${props.dataSourceConfigDto.name}`;
});

const dialogVisible = ref<boolean>(false);

defineExpose({ dialogVisible });
</script>

// packages/cobi-react/src/pages/DataManagementDashboard/components/ExecuteDialog/DataSourceConfigDialogResult.tsx
import React, { forwardRef, useImperativeHandle, useState } from 'react';
import { Modal } from 'antd';
import DataSourceConfigDialogResultTabs from './DataSourceConfigDialogResultTabs';

interface DataSourceConfigDialogResultProps {
  result: any;
  dataSourceConfigDto: any;
  requestId: string;
}

export interface DataSourceConfigDialogResultRef {
  dialogVisible: boolean;
  setDialogVisible: (visible: boolean) => void;
}

const DataSourceConfigDialogResult = forwardRef<
  DataSourceConfigDialogResultRef,
  DataSourceConfigDialogResultProps
>((props, ref) => {
  const { result, dataSourceConfigDto, requestId } = props;
  const [dialogVisible, setDialogVisible] = useState(false);

  useImperativeHandle(ref, () => ({
    dialogVisible,
    setDialogVisible,
  }));

  const computedTitle = `Result: ${dataSourceConfigDto?.name || 'N/A'}`;

  return (
    <Modal
      title={computedTitle}
      open={dialogVisible}
      onCancel={() => setDialogVisible(false)}
      footer={null}
      width="80%"
      destroyOnClose
    >
      <DataSourceConfigDialogResultTabs result={result} requestId={requestId} />
    </Modal>
  );
});

DataSourceConfigDialogResult.displayName = 'DataSourceConfigDialogResult';

export default DataSourceConfigDialogResult;
