// .old_project /packages/cobi/src/components/DataSourceConfig/DataSourceConfigDialogRequest/DataSourceConfigDialogRequestOperation.vue
<template>
  <div class="data-source-config-dialog-request-operation">
    <div class="title-client-data">
      <h4>Request Fields</h4>
      <el-button @click="onAddRequestFields" type="primary">
        Add
        <font-awesome-icon icon="plus" />
      </el-button>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th class="td-name">Name</th>
          <th>Value</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, index) in requestFieldsArr" :key="index">
          <template v-if="row.isCustom">
            <td>
              <el-input @change="onChangeClientData" v-model="row.key" />
            </td>
          </template>
          <template v-else>
            <td class="td-mapping">
              {{ row.key }}
            </td>
          </template>
          <td>
            <el-input @change="onChangeRequestFields" v-model="row.value" />
          </td>
          <td class="action">
            <el-button v-if="row.isCustom" size="default" @click="deleteRequestField(index)" type="danger">
              <font-awesome-icon icon="trash" />
            </el-button>
          </td>
        </tr>
      </tbody>
    </table>

    <el-divider />
    <div class="title-client-data">
      <h4>Client Data</h4>
      <el-button @click="onAddClientData" type="primary">
        Add
        <font-awesome-icon icon="plus" />
      </el-button>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Value</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="(row, index) in clientDataArr" :key="index">
          <td>
            <el-input @change="onChangeClientData" v-model="row.key" />
          </td>
          <td>
            <el-input @change="onChangeClientData" v-model="row.value" />
          </td>
          <td class="action">
            <el-button size="default" @click="deleteClientData(index)" type="danger">
              <font-awesome-icon icon="trash" />
            </el-button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup lang="ts">
import { useDataSourceConfigStore } from "../../../stores/data-source-config";
import { ElMessageBox } from "element-plus";
import { ref, watch } from "vue";

const props = defineProps({
  dataSourceOperation: {
    default: () => {
      return {};
    }
  },
  activeRequestFields: {
    default: () => {
      return {};
    }
  },
  index: { default: 0 }
});
const dataSourceConfigStore = useDataSourceConfigStore();
function verifyTemplateCalc() {
  return dataSourceConfigStore.verifyTemplateCalc();
}

function getAvailableAuthType() {
  return dataSourceConfigStore.getAvailableAuthType();
}

let requestFieldsArr = ref([]);
let clientDataArr = ref([]);

watch(
  () => props.dataSourceOperation.request_fields,
  () => {
    if (requestFieldsArr.value.length === 0) {
      const originalKeys = Object.keys(props.activeRequestFields);
      Object.keys(props.dataSourceOperation.request_fields).forEach((key) => {
        requestFieldsArr.value.push({
          key,
          value: props.dataSourceOperation.request_fields[key] || "",
          isCustom: !originalKeys.includes(key)
        });
      });
    }
  },
  { immediate: true }
);

watch(
  () => props.dataSourceOperation.clientData,
  () => {
    if (clientDataArr.value.length === 0) {
      Object.keys(props.dataSourceOperation.clientData).forEach((key) => {
        clientDataArr.value.push({
          key,
          value: props.dataSourceOperation.clientData[key] || ""
        });
      });
    }
  },
  { immediate: true }
);

function onChangeRequestFields() {
  props.dataSourceOperation.request_fields = {};
  requestFieldsArr.value.forEach((el) => {
    props.dataSourceOperation.request_fields[el.key] = el.value;
  });
}
function onChangeClientData() {
  props.dataSourceOperation.clientData = {};
  clientDataArr.value.forEach((el) => {
    props.dataSourceOperation.clientData[el.key] = el.value;
  });
}
function onAddRequestFields() {
  requestFieldsArr.value.push({
    key: "",
    value: "",
    isCustom: true
  });
}
function onAddClientData() {
  clientDataArr.value.push({
    key: "",
    value: ""
  });
}
function deleteRequestField(index) {
  ElMessageBox.confirm("Do you really want to remove row?", "Confirm!", {
    callback: async (action) => {
      if (action === "confirm") {
        requestFieldsArr.value.splice(index, 1);

        onChangeRequestFields();
      }
    }
  });
}
function deleteClientData(index) {
  ElMessageBox.confirm("Do you really want to remove row?", "Confirm!", {
    callback: async (action) => {
      if (action === "confirm") {
        clientDataArr.value.splice(index, 1);

        onChangeClientData();
      }
    }
  });
}
</script>

<style lang="scss">
.data-source-config-dialog-request-operation {
  .title {
    font-size: 18px;
    margin-bottom: 10px;

    span {
      font-weight: bold;
    }
  }

  .table {
    width: 100%;
    border-collapse: collapse;

    td,
    th {
      border: 1px solid #dedede;
    }

    th {
      padding: 10px 20px;
      text-align: left;
      text-transform: uppercase;
    }

    td {
      .el-input__inner, .el-input__wrapper {
        box-shadow: none !important;
        border-radius: 0;
        border: none;
      }

      &.action {
        padding: 5px 10px;
      }
    }
  }

  .actions {
    margin-bottom: 10px;
    text-align: right;
  }

  .td-mapping {
    background-color: #f5f7fa;
    padding-left: 15px;
  }

  .title-client-data {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 10px;
  }

  .td-name {
    width: 40%;
  }
}
</style>

// packages/cobi-react/src/pages/DataManagementDashboard/components/ExecuteDialog/DataSourceConfigDialogRequestOperation.tsx
import React, { useState, useEffect } from 'react';
import { Button, Input, Modal } from 'antd';
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons';
import './DataSourceConfigDialogRequestOperation.css';

interface RequestField {
  key: string;
  value: string;
  isCustom?: boolean;
}

interface DataSourceConfigDialogRequestOperationProps {
  dataSourceOperation: any;
  activeRequestFields: any;
  index: number;
}

const DataSourceConfigDialogRequestOperation: React.FC<DataSourceConfigDialogRequestOperationProps> = ({
  dataSourceOperation,
  activeRequestFields,
  index,
}) => {
  const [requestFieldsArr, setRequestFieldsArr] = useState<RequestField[]>([]);
  const [clientDataArr, setClientDataArr] = useState<RequestField[]>([]);

  // Initialize request fields
  useEffect(() => {
    if (requestFieldsArr.length === 0 && dataSourceOperation.request_fields) {
      const originalKeys = Object.keys(activeRequestFields);
      const fields: RequestField[] = [];

      Object.keys(dataSourceOperation.request_fields).forEach((key) => {
        fields.push({
          key,
          value: dataSourceOperation.request_fields[key] || '',
          isCustom: !originalKeys.includes(key),
        });
      });

      setRequestFieldsArr(fields);
    }
  }, [dataSourceOperation.request_fields, activeRequestFields, requestFieldsArr.length]);

  // Initialize client data
  useEffect(() => {
    if (clientDataArr.length === 0 && dataSourceOperation.clientData) {
      const data: RequestField[] = [];

      Object.keys(dataSourceOperation.clientData).forEach((key) => {
        data.push({
          key,
          value: dataSourceOperation.clientData[key] || '',
        });
      });

      setClientDataArr(data);
    }
  }, [dataSourceOperation.clientData, clientDataArr.length]);

  const onChangeRequestFields = (updatedFields: RequestField[]) => {
    setRequestFieldsArr(updatedFields);
    dataSourceOperation.request_fields = {};
    updatedFields.forEach((el) => {
      dataSourceOperation.request_fields[el.key] = el.value;
    });
  };

  const onChangeClientData = (updatedData: RequestField[]) => {
    setClientDataArr(updatedData);
    dataSourceOperation.clientData = {};
    updatedData.forEach((el) => {
      dataSourceOperation.clientData[el.key] = el.value;
    });
  };

  const onAddRequestFields = () => {
    const updated = [...requestFieldsArr, { key: '', value: '', isCustom: true }];
    onChangeRequestFields(updated);
  };

  const onAddClientData = () => {
    const updated = [...clientDataArr, { key: '', value: '' }];
    onChangeClientData(updated);
  };

  const deleteRequestField = (index: number) => {
    Modal.confirm({
      title: 'Confirm!',
      content: 'Do you really want to remove row?',
      onOk: () => {
        const updated = requestFieldsArr.filter((_, i) => i !== index);
        onChangeRequestFields(updated);
      },
    });
  };

  const deleteClientData = (index: number) => {
    Modal.confirm({
      title: 'Confirm!',
      content: 'Do you really want to remove row?',
      onOk: () => {
        const updated = clientDataArr.filter((_, i) => i !== index);
        onChangeClientData(updated);
      },
    });
  };

  const updateRequestField = (index: number, field: 'key' | 'value', newValue: string) => {
    const updated = [...requestFieldsArr];
    updated[index][field] = newValue;
    onChangeRequestFields(updated);
  };

  const updateClientData = (index: number, field: 'key' | 'value', newValue: string) => {
    const updated = [...clientDataArr];
    updated[index][field] = newValue;
    onChangeClientData(updated);
  };

  return (
    <div className="data-source-config-dialog-request-operation">
      <div className="title-client-data">
        <h4>Request Fields</h4>
        <Button type="primary" icon={<PlusOutlined />} onClick={onAddRequestFields}>
          Add
        </Button>
      </div>
      <table className="table">
        <thead>
          <tr>
            <th className="td-name">Name</th>
            <th>Value</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {requestFieldsArr.map((row, idx) => (
            <tr key={idx}>
              {row.isCustom ? (
                <td>
                  <Input
                    value={row.key}
                    onChange={(e) => updateRequestField(idx, 'key', e.target.value)}
                  />
                </td>
              ) : (
                <td className="td-mapping">{row.key}</td>
              )}
              <td>
                <Input
                  value={row.value}
                  onChange={(e) => updateRequestField(idx, 'value', e.target.value)}
                />
              </td>
              <td className="action">
                {row.isCustom && (
                  <Button
                    danger
                    icon={<DeleteOutlined />}
                    onClick={() => deleteRequestField(idx)}
                  />
                )}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={{ margin: '20px 0' }} />

      <div className="title-client-data">
        <h4>Client Data</h4>
        <Button type="primary" icon={<PlusOutlined />} onClick={onAddClientData}>
          Add
        </Button>
      </div>
      <table className="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Value</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {clientDataArr.map((row, idx) => (
            <tr key={idx}>
              <td>
                <Input
                  value={row.key}
                  onChange={(e) => updateClientData(idx, 'key', e.target.value)}
                />
              </td>
              <td>
                <Input
                  value={row.value}
                  onChange={(e) => updateClientData(idx, 'value', e.target.value)}
                />
              </td>
              <td className="action">
                <Button danger icon={<DeleteOutlined />} onClick={() => deleteClientData(idx)} />
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default DataSourceConfigDialogRequestOperation;
