// packages/cyoda-sass-react/src/components/TrinoEditTable/TrinoEditTable.tsx
import React, { useMemo } from 'react';
import { Input, Checkbox } from 'antd';
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { arrayMove, SortableContext, sortableKeyboardCoordinates, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faAlignJustify, faEye } from '@fortawesome/free-solid-svg-icons';
import type { SqlField, SqlTable } from '../../types';
import { getAllFields } from '../../utils/helpers';
import './TrinoEditTable.css';

interface TrinoEditTableProps {
  table: SqlTable;
  fieldsName?: string;
  basePropPath?: string;
  allFields?: SqlField[];
  onFieldsChange?: (fields: SqlField[]) => void;
}

interface SortableRowProps {
  field: SqlField;
  index: number;
  isExistArray: boolean;
  basePropPath: string;
  fieldsName: string;
  allFields: SqlField[];
  onHide: (field: SqlField) => void;
  onFieldChange: (index: number, field: SqlField) => void;
  table: SqlTable;
}

const SortableRow: React.FC<SortableRowProps> = ({
  field,
  index,
  isExistArray,
  basePropPath,
  fieldsName,
  allFields,
  onHide,
  onFieldChange,
  table,
}) => {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
  } = useSortable({ id: field.fieldName || `field-${index}` });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
  };

  // Validate field name
  const validateFieldName = (row: SqlField): string | undefined => {
    if (row.flatten) return undefined;
    const fieldNames = allFields.filter((el) => !el.hidden).filter((el) => el.fieldName === row.fieldName);
    if (fieldNames.length > 1) {
      return 'The "Field Name" field must be unique';
    }
    return undefined;
  };

  const getPropPath = (idx: number) => {
    return `${basePropPath}.${fieldsName}.${idx}`;
  };

  const handleFieldNameChange = (value: string) => {
    onFieldChange(index, { ...field, fieldName: value });
  };

  const handleFlattenChange = (checked: boolean) => {
    onFieldChange(index, { ...field, flatten: checked });
  };

  const isNotData = field.fieldCategory !== 'DATA';

  if (field.hidden) {
    return null;
  }

  return (
    <div ref={setNodeRef} style={style}>
      <div className={`row-container ${isNotData ? 'not-data' : ''}`}>
        <div className="cell col1">
          <FontAwesomeIcon
            className="handle"
            icon={faAlignJustify}
            {...attributes}
            {...listeners}
          />
          <FontAwesomeIcon
            className="eye"
            icon={faEye}
            onClick={() => onHide(field)}
          />
        </div>
        <div className="cell cell-item col2">
          <div style={{ width: '100%' }}>
            <Input
              value={field.fieldName}
              onChange={(e) => handleFieldNameChange(e.target.value)}
              status={validateFieldName(field) ? 'error' : ''}
            />
            {validateFieldName(field) && (
              <div style={{ color: '#ff4d4f', fontSize: '12px', marginTop: '4px' }}>
                {validateFieldName(field)}
              </div>
            )}
          </div>
        </div>
        <div className="cell col3">
          <span>{field.fieldKey || field.fieldName}</span>
        </div>
        <div className="cell col4">
          <span>{field.fieldType || field.dataType}</span>
        </div>
        {isExistArray && (
          <div className="cell col5">
            {field.isArray && (
              <Checkbox
                checked={field.flatten}
                onChange={(e) => handleFlattenChange(e.target.checked)}
              />
            )}
          </div>
        )}
      </div>

      {isExistArray && field.flatten && field.arrayFields && (
        <div className="expand-row">
          <TrinoEditTable
            table={{ ...field, arrayFields: field.arrayFields } as any}
            fieldsName="arrayFields"
            basePropPath={`${getPropPath(index)}.arrayFields`}
            allFields={allFields}
            onFieldsChange={(newFields) => {
              onFieldChange(index, { ...field, arrayFields: newFields });
            }}
          />
        </div>
      )}
    </div>
  );
};

const TrinoEditTable: React.FC<TrinoEditTableProps> = ({
  table,
  fieldsName = 'fields',
  basePropPath = '',
  allFields: providedAllFields,
  onFieldsChange,
}) => {
  const fields = table[fieldsName as keyof SqlTable] as SqlField[] || [];
  
  // Calculate all fields if not provided
  const allFields = useMemo(() => {
    return providedAllFields || getAllFields(fields);
  }, [providedAllFields, fields]);

  // Check if any field is an array
  const isExistArray = useMemo(() => {
    return fields.some((el) => el.isArray);
  }, [fields]);

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  const handleDragEnd = (event: any) => {
    const { active, over } = event;

    if (active.id !== over.id) {
      const oldIndex = fields.findIndex((f) => (f.fieldName || `field-${fields.indexOf(f)}`) === active.id);
      const newIndex = fields.findIndex((f) => (f.fieldName || `field-${fields.indexOf(f)}`) === over.id);

      const newFields = arrayMove(fields, oldIndex, newIndex);
      
      // Update the table object
      (table[fieldsName as keyof SqlTable] as SqlField[]) = newFields;
      
      if (onFieldsChange) {
        onFieldsChange(newFields);
      }
    }
  };

  const handleHideField = (field: SqlField) => {
    field.hidden = true;
    if (onFieldsChange) {
      onFieldsChange([...fields]);
    }
  };

  const handleFieldChange = (index: number, updatedField: SqlField) => {
    const newFields = [...fields];
    newFields[index] = updatedField;
    (table[fieldsName as keyof SqlTable] as SqlField[]) = newFields;
    
    if (onFieldsChange) {
      onFieldsChange(newFields);
    }
  };

  return (
    <div className="trino-edit-table">
      <div className="table-container">
        <div className="row-container">
          <div className="header col1"></div>
          <div className="header col2">Field Name</div>
          <div className="header col3">Field Key</div>
          <div className="header col4">Data Type</div>
          {isExistArray && <div className="header col5">Flatten</div>}
        </div>

        <DndContext
          sensors={sensors}
          collisionDetection={closestCenter}
          onDragEnd={handleDragEnd}
        >
          <SortableContext
            items={fields.map((f, i) => f.fieldName || `field-${i}`)}
            strategy={verticalListSortingStrategy}
          >
            {fields.map((field, index) => (
              <SortableRow
                key={field.fieldName || `field-${index}`}
                field={field}
                index={index}
                isExistArray={isExistArray}
                basePropPath={basePropPath}
                fieldsName={fieldsName}
                allFields={allFields}
                onHide={handleHideField}
                onFieldChange={handleFieldChange}
                table={table}
              />
            ))}
          </SortableContext>
        </DndContext>
      </div>
    </div>
  );
};

export default TrinoEditTable;

// .old_project /packages/cyoda-sass/src/views/Trino/TrinoEdit/TrinoEditTable.vue
<template>
  <div class="trino-edit-table">
    <div class="table-container" style="width: 100%">
      <div class="row-container">
        <div class="header col1"></div>
        <div class="header col2">Field Name</div>
        <div class="header col3">Field Key</div>
        <div class="header col4">Data Type</div>
        <div v-if="isExistArray" class="header col5">Flatten</div>
      </div>
      <draggable
        v-model="fields"
        @end="onEndDrag"
        handle=".handle"
        item-key="fieldKey">
        <template #item="{element: row, index}">
          <div v-show="!row.hidden">
            <div class="row-container" :class="{'not-data': row.fieldCategory !== 'DATA'}">
              <div class="cell col1">
                <font-awesome-icon class="handle" icon="align-justify"/>
                <font-awesome-icon class="eye" @click="hideColumn(row)" icon="eye"/>
              </div>
              <div class="cell cell-item col2">
                <el-form-item
                  label-width="auto"
                  :prop="`${getPropPath(index)}.fieldName`"
                  :error="validateFieldName(row)"
                  :show-message="!!validateFieldName(row)"
                >
                  <el-input v-model="row.fieldName"/>
                </el-form-item>
              </div>
              <div class="cell col3"><span>{{ row.fieldKey }}</span></div>
              <div class="cell col4"><span>{{ row.dataType }}</span></div>
              <div v-if="isExistArray" class="cell col5">
                <el-checkbox v-if="row.isArray" v-model="row.flatten" size="large"/>
              </div>
            </div>

            <div class="expand-row" v-if="isExistArray && row.flatten">
              <TrinoEditTable :table="row" fields-name="arrayFields" :basePropPath="`${getPropPath(index)}.arrayFields`"
                              :tableIndex="0" :allFields="allFields"/>
            </div>
          </div>
        </template>
      </draggable>
    </div>
  </div>
</template>

<script setup lang="ts">
import {computed, reactive, ref, watch} from "vue";
import draggable from "vuedraggable";
import {FontAwesomeIcon} from "@fortawesome/vue-fontawesome";

const props = defineProps({
  fieldsName: {
    default: 'fields',
  },
  basePropPath: {
    default: '',
  },
  table: {
    default: () => {
      return {}
    }
  },
  allFields: {
    default: () => {
      return []
    }
  },
  isExistFlatten: {
    default: false
  }
})

const isExistArray = computed(() => {
  return fields.value.some((el) => el.isArray);
})

const fields = ref([]);

watch(() => props.fieldsName, (value) => {
  fields.value = props.table[value] || [];
}, {immediate: true});

function onEndDrag() {
  Object.assign(props.table[props.fieldsName], fields.value);
}

let form = reactive({
  filter: "",
  currentPage: 1,
  pageSize: 10
});

function validateFieldName(row: any) {
  if (row.flatten) return;
  const fieldNames = props.allFields.filter((el) => !el.hidden).filter((el) => el.fieldName === row.fieldName);
  if (fieldNames.length > 1) {
    return 'The "Field Name" field must be unique';
  }
}

function getPropPath(index) {
  return `${props.basePropPath}.${props.fieldsName}.${index}`
}

function hideColumn(row) {
  row.hidden = true;
}


</script>

<style lang="scss">
.trino-edit-table {
  .table-container {
    .col1 {
      width: 70px;
      display: flex;
      justify-content: center;
      gap: 10px;
    }

    .col2 {
      flex: 1;
    }

    .col3 {
      word-break: break-all;
    }

    .col3, .col4 {
      width: 25%;
    }

    .col5 {
      width: 80px;
      display: flex;
      justify-content: center;
    }

    .header {
      background-color: #4b5d7a;
      color: #fff;
      text-align: left;
      padding: 5px;
      border: 0.5px solid #ebeef5;
    }

    .row-container {
      display: flex;
      width: 100%;

      .cell {
        padding: 5px;
        border: 0.5px solid #ebeef5;
        //display: table-cell;
        display: flex;
        align-items: center;
      }

      .cell-item {
        padding: 5px;
      }

      .el-form-item {
        margin-bottom: 0;
      }

      .el-checkbox.el-checkbox--large {
        height: 30px;
      }

      .el-input--large .el-input__inner {
        --el-input-inner-height: 30px;
      }

      .el-form-item--large .el-form-item__error {
        position: unset;
      }
    }
  }

  .handle, .eye {
    cursor: pointer;
    transition: all 0.5s;

    &:hover {
      opacity: 0.5;
    }
  }

  .not-data{
    background-color: #f3f3f3;
  }

  .expand-row {
    border: 0.5px solid #ebeef5;
    padding: 16px;
  }
}
</style>
