// .old_project /packages/processing-manager/src/components/PmTransitionDetail/Events/EventsTable.vue
<template>
  <div class="card">
    <div class="card-header">Transaction Events</div>
    <div class="card-body" v-loading="isLoading">
      <el-table border :data="tableData" style="width: 100%">
        <el-table-column prop="createTime" label="Create Time" width="170"> </el-table-column>
        <el-table-column prop="doneTime" label="Done Time" width="170"> </el-table-column>
        <el-table-column prop="errorTime" label="Error Time" width="170"> </el-table-column>
        <el-table-column prop="totalTimeMillis" label="Total Time(ms)" width="170" />
        <el-table-column prop="queueName" label="Queue" width="400" />
        <el-table-column prop="shardId" label="Shard" width="100" />
        <el-table-column prop="status" label="Status" width="200" />
        <el-table-column prop="timeUUID" label="Time UUID" width="330">
          <template v-slot="scope">
            <router-link :to="onEventView(scope)" type="text" size="small">{{ scope.row.timeUUID }}</router-link>
          </template>
        </el-table-column>
        <el-table-column prop="entityClassName" label="Entity Class" width="350" />
        <el-table-column prop="entityId" label="Entity ID" width="330" />
        <el-table-column prop="entityHasErrors" label="Has Errors" width="150">
          <template v-slot:default="{ row }">
            {{ $filters.boolean(row) }}
          </template>
        </el-table-column>
        <el-table-column prop="errorEventTimeUUID" label="Error Event Time UUID" width="330" />
        <el-table-column prop="coreDataClassName" label="Core Event Data Class" width="350" />
        <el-table-column prop="versionCheckResult" label="Client Event Data Class" width="350" />
      </el-table>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from "vue-router";

import moment from "moment";

const props = defineProps({ isLoading: { default: false }, tableData: { default: () => [] } });
const route = useRoute();

function convertTime(mkTime: number) {
  return moment(mkTime).format("YYYY-MM-DD HH:mm:ss.SSS");
}

function onEventView({ row }: { row: any }) {
  return `/processing-ui/nodes/${route.params.name}/event-view?queue=${row.queueName}&shard=${row.shardId}&timeUUID=${row.timeUUID}`;
}
</script>

// react-project/packages/processing-manager-react/src/components/transition-detail/EventsTable.tsx
/**
 * Events Table Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionDetail/Events/EventsTable.vue
 */

import React from 'react';
import { Card, Table, Spin } from 'antd';
import { Link, useParams } from 'react-router-dom';
import type { ColumnsType } from 'antd/es/table';

interface EventRow {
  createTime: string;
  doneTime: string;
  errorTime: string;
  totalTimeMillis: number;
  queueName: string;
  shardId: string;
  status: string;
  timeUUID: string;
  entityClassName: string;
  entityId: string;
  entityHasErrors: boolean;
  errorEventTimeUUID: string;
  coreDataClassName: string;
  versionCheckResult: string;
}

interface EventsTableProps {
  tableData: EventRow[];
  isLoading?: boolean;
}

export const EventsTable: React.FC<EventsTableProps> = ({ tableData, isLoading = false }) => {
  const { name } = useParams<{ name: string }>();

  const columns: ColumnsType<EventRow> = [
    {
      title: 'Create Time',
      dataIndex: 'createTime',
      key: 'createTime',
      width: 170,
    },
    {
      title: 'Done Time',
      dataIndex: 'doneTime',
      key: 'doneTime',
      width: 170,
    },
    {
      title: 'Error Time',
      dataIndex: 'errorTime',
      key: 'errorTime',
      width: 170,
    },
    {
      title: 'Total Time(ms)',
      dataIndex: 'totalTimeMillis',
      key: 'totalTimeMillis',
      width: 170,
    },
    {
      title: 'Queue',
      dataIndex: 'queueName',
      key: 'queueName',
      width: 400,
    },
    {
      title: 'Shard',
      dataIndex: 'shardId',
      key: 'shardId',
      width: 100,
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      width: 200,
    },
    {
      title: 'Time UUID',
      dataIndex: 'timeUUID',
      key: 'timeUUID',
      width: 330,
      render: (timeUUID: string, record: EventRow) => (
        <Link
          to={`/nodes/${name}/event-view?queue=${record.queueName}&shard=${record.shardId}&timeUUID=${timeUUID}`}
        >
          {timeUUID}
        </Link>
      ),
    },
    {
      title: 'Entity Class',
      dataIndex: 'entityClassName',
      key: 'entityClassName',
      width: 350,
    },
    {
      title: 'Entity ID',
      dataIndex: 'entityId',
      key: 'entityId',
      width: 330,
    },
    {
      title: 'Has Errors',
      dataIndex: 'entityHasErrors',
      key: 'entityHasErrors',
      width: 150,
      render: (hasErrors: boolean) => (hasErrors ? 'Yes' : 'No'),
    },
    {
      title: 'Error Event Time UUID',
      dataIndex: 'errorEventTimeUUID',
      key: 'errorEventTimeUUID',
      width: 330,
    },
    {
      title: 'Core Event Data Class',
      dataIndex: 'coreDataClassName',
      key: 'coreDataClassName',
      width: 350,
    },
    {
      title: 'Client Event Data Class',
      dataIndex: 'versionCheckResult',
      key: 'versionCheckResult',
      width: 350,
    },
  ];

  return (
    <Card title="Transaction Events">
      <Spin spinning={isLoading}>
        <Table
          columns={columns}
          dataSource={tableData}
          rowKey="timeUUID"
          bordered
          pagination={false}
          scroll={{ x: 'max-content' }}
        />
      </Spin>
    </Card>
  );
};

export default EventsTable;
