// .old_project /packages/processing-manager/src/components/PmTransitionDetail/TransitionDetailStatistics.vue
<template>
  <div class="card">
    <div class="card-header">Statistics</div>
    <div class="card-body">
      <ul>
        <li class="name">Transaction ID</li>
        <li>{{ transactionInfoView.id }}</li>
        <li class="name">Transaction Status</li>
        <li>{{ transactionInfoView.status }}</li>
        <li class="name">Transaction Submit Node Id</li>
        <li>{{ transactionInfoView.transactionSubmitNodeId }}</li>
        <li class="name">User</li>
        <li>{{ transactionInfoView.owner }}</li>
        <li class="name">Shard(uuid)</li>
        <li>{{ shardUUID }}</li>
        <li class="name">Consistency Time</li>
        <li>{{ $filters.dateTime(transactionInfoView.transactionConsistencyTime) }}</li>
        <li class="name">Create time</li>
        <li>{{ $filters.dateTime(transactionInfoView.createTime) }}</li>
        <li class="name">Submit time</li>
        <li>{{ $filters.dateTime(transactionInfoView.submitTime) }}</li>
        <li class="name">Finish time</li>
        <li>{{ $filters.dateTime(transactionInfoView.finishTime) }}</li>
        <li class="name">Prepare duration</li>
        <li>{{ $filters.countdown(transactionInfoView.prepareTimeMillis) }}</li>
        <li class="name">Process duration</li>
        <li>{{ $filters.countdown(transactionInfoView.processTimeMillis) }}</li>
        <li class="name">Second Phase Finished Flag</li>
        <li>{{ $filters.boolean(transactionInfoView.secondPhaseFinished) }}</li>
        <li class="name">Transaction Succeeded Flag</li>
        <li>{{ $filters.boolean(transactionInfoView.transactionSucceeded) }}</li>
        <li class="name">Parent Transactions</li>
        <li>
          <template v-for="(parentTransactionId, index) in parentTransactionIds"> {{ index + 1 }}) {{ parentTransactionId }}<br /> </template>
        </li>
      </ul>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from "vue-router";
import { ref } from "vue";
import {useProcessingStore} from "../../stores/processing";

const route = useRoute();
const processingStore = useProcessingStore();
function transactionsView(value) {
  return processingStore.transactionsView(value);
}

let transactionInfoView = ref({});

const shardString = ref<string>("");

const shardUUID = ref<string>("");

let parentTransactionIds = ref([]);

loadData();

async function loadData() {
  const { data } = await transactionsView({
    id: route.params.transactionId
  });
  transactionInfoView.value = data.transactionInfoView;
  shardString.value = data.shardString;
  shardUUID.value = data.shardUUID;
  parentTransactionIds.value = data.parentTransactionIds;
}
</script>

<style scoped lang="scss">
.card-body ul {
  list-style: none;
  margin: 0;
  padding: 0;

  li.name {
    font-weight: bold;
    margin-top: 10px;
  }
}
</style>

// react-project/packages/processing-manager-react/src/components/transition-detail/TransitionDetailStatistics.tsx
/**
 * Transition Detail Statistics Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionDetail/TransitionDetailStatistics.vue
 */

import React, { useEffect, useState } from 'react';
import { Card } from 'antd';
import { useParams } from 'react-router-dom';
import { useTransactionsView } from '../../hooks';
import dayjs from 'dayjs';
import './TransitionDetailStatistics.scss';

const formatDateTime = (value: number | null | undefined) => {
  if (!value) return '';
  return dayjs(value).format('YYYY-MM-DD HH:mm:ss');
};

const formatCountdown = (value: number | null | undefined) => {
  if (!value) return '';
  const seconds = Math.floor(value / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  return `${hours}h ${minutes % 60}m ${seconds % 60}s`;
};

const formatBoolean = (value: boolean | null | undefined) => {
  return value ? 'Yes' : 'No';
};

export const TransitionDetailStatistics: React.FC = () => {
  const { transactionId } = useParams<{ transactionId: string }>();
  const [transactionInfoView, setTransactionInfoView] = useState<any>({});
  const [shardUUID, setShardUUID] = useState<string>('');
  const [parentTransactionIds, setParentTransactionIds] = useState<string[]>([]);

  const { data, isLoading } = useTransactionsView({ id: transactionId });

  useEffect(() => {
    if (data) {
      setTransactionInfoView(data.transactionInfoView || {});
      setShardUUID(data.shardUUID || '');
      setParentTransactionIds(data.parentTransactionIds || []);
    }
  }, [data]);

  return (
    <Card title="Statistics" loading={isLoading} className="transition-detail-statistics">
      <ul>
        <li className="name">Transaction ID</li>
        <li>{transactionInfoView.id}</li>
        <li className="name">Transaction Status</li>
        <li>{transactionInfoView.status}</li>
        <li className="name">Transaction Submit Node Id</li>
        <li>{transactionInfoView.transactionSubmitNodeId}</li>
        <li className="name">User</li>
        <li>{transactionInfoView.owner}</li>
        <li className="name">Shard(uuid)</li>
        <li>{shardUUID}</li>
        <li className="name">Consistency Time</li>
        <li>{formatDateTime(transactionInfoView.transactionConsistencyTime)}</li>
        <li className="name">Create time</li>
        <li>{formatDateTime(transactionInfoView.createTime)}</li>
        <li className="name">Submit time</li>
        <li>{formatDateTime(transactionInfoView.submitTime)}</li>
        <li className="name">Finish time</li>
        <li>{formatDateTime(transactionInfoView.finishTime)}</li>
        <li className="name">Prepare duration</li>
        <li>{formatCountdown(transactionInfoView.prepareTimeMillis)}</li>
        <li className="name">Process duration</li>
        <li>{formatCountdown(transactionInfoView.processTimeMillis)}</li>
        <li className="name">Second Phase Finished Flag</li>
        <li>{formatBoolean(transactionInfoView.secondPhaseFinished)}</li>
        <li className="name">Transaction Succeeded Flag</li>
        <li>{formatBoolean(transactionInfoView.transactionSucceeded)}</li>
        <li className="name">Parent Transactions</li>
        <li>
          {parentTransactionIds.map((parentTransactionId, index) => (
            <React.Fragment key={index}>
              {index + 1}) {parentTransactionId}
              <br />
            </React.Fragment>
          ))}
        </li>
      </ul>
    </Card>
  );
};

export default TransitionDetailStatistics;
