// .old_project /packages/statemachine/src/components/ProcessesList.vue
<template>
  <div id="processes-list" class="processes-list">
    <div class="title">
      <h2>Processes</h2>
      <div class="buttons">
        <el-button @click="onAddNew" type="primary">
          <font-awesome-icon :icon="['fas', 'plus']"/>
          Create new process
        </el-button>
      </div>
    </div>

    <el-table v-loading="isLoading" :data="tableData" border style="width: 100%">
      <el-table-column sortable prop="name" label="Name" width="300">
        <template v-slot:default="{ row }">
          <RouterLink :to="processLink(row)">
            <el-link type="primary">
              {{ row.name }}
            </el-link>
          </RouterLink>
        </template>
      </el-table-column>
      <el-table-column sortable prop="persisted" label="Persisted" width="150">
        <template v-slot:default="{ row }">
          <StateComponent :state="row.persisted"/>
        </template>
      </el-table-column>
      <el-table-column sortable prop="isTemplate" label="Template" width="150">
        <template v-slot:default="{ row }">
          <StateComponent :state="row.isTemplate"/>
        </template>
      </el-table-column>

      <el-table-column sortable prop="description" label="Description"/>

      <el-table-column label="Actions" width="180">
        <template v-slot:default="{ row }">
          <el-button @click="onClickCopy(row)" type="primary" size="default">
            <font-awesome-icon :icon="['fas', 'copy']"/>
          </el-button>
          <el-button @click="onClickDelete(row)" type="danger" size="default">
            <font-awesome-icon :icon="['fas', 'trash']"/>
          </el-button>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>

<script setup lang="ts">
import {useStatemachineStore} from "../stores/statemachine";
import {computed, ref, onMounted} from "vue";
import StateComponent from "../components/States/StateComponent.vue";
import StateAutomatedComponent from "../components/States/StateAutomatedComponent.vue";
import {useRoute, useRouter} from "vue-router";
import {ElMessageBox} from "element-plus";
import axios from "@cyoda/ui-lib/src/plugins/axios";
import {getPersistedType} from "../helpers/HelperData";
import HelperProcesses from "@cyoda/ui-lib/src/helpers/HelperProcesses.ts";

const statemachineStore = useStatemachineStore();
const isLoading = ref(null);

const props = defineProps({
  workflowId: {
    default: null,
  },
  persistedType: {
    default: "",
  },
  entityClassName: {
    default: "",
  }
})

const processesList = ref([]);
const router = useRouter();
const route = useRoute();

onMounted(async () => {
  loadProcessesList();
})

async function loadProcessesList() {
  const {data} = await statemachineStore.getProcessesList(props.entityClassName);
  processesList.value = data;
}

const tableData = computed(() => {
  return processesList.value;
});

function onAddNew() {
  router.push(`/statemachine/process/new?workflowId=${props.workflowId}&persistedType=persisted&entityClassName=${props.entityClassName}&workflowPersistedType=${props.persistedType}`);
}

function processLink(row) {
  return `/statemachine/process/${row.id.persistedId || row.id.runtimeId}?persistedType=${getPersistedType(row.persisted)}&entityClassName=${route.query.entityClassName}&workflowId=${props.workflowId}&workflowPersistedType=${props.persistedType}`;
}

async function onClickCopy(row) {
  try {
    isLoading.value = true;
    const {data} = await statemachineStore.getProcesses(getPersistedType(row.persisted), row.id.persistedId);
    const dataForm = HelperProcesses.format(data);
    delete dataForm.id;
    dataForm.name = `[ DUPLICATE ] ${dataForm.name}`;
    await statemachineStore.postProcesses(getPersistedType(row.persisted), dataForm);
    await loadProcessesList();
  } finally {
    isLoading.value = false;
  }
}

function onClickDelete(row) {
  ElMessageBox.confirm(`Are you sure you want to delete process "${row.name}"?`, "Delete confirmation", {
    callback: async (action) => {
      if (action === "confirm") {
        try {
          isLoading.value = true;
          await statemachineStore.deleteProcesses(getPersistedType(row.persisted), row.id.persistedId);
          await loadProcessesList();
        } finally {
          isLoading.value = false;
        }
      }
    }
  });
}
</script>

<style scoped lang="scss">
.processes-list {
  .title {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
}
</style>

// react-project/packages/statemachine-react/src/components/ProcessesList.tsx
/**
 * Processes List Component
 * Display and manage processes for a workflow
 * Migrated from: .old_project/packages/statemachine/src/components/ProcessesList.vue
 */

import React, { useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Table, Button, Space, Tooltip, Modal, message } from 'antd';
import { PlusOutlined, CopyOutlined, DeleteOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import { useProcessesList, useDeleteProcess, useCopyProcess } from '../hooks/useStatemachine';
import { StateIndicator } from './StateIndicator';
import type { PersistedType } from '../types';

const { confirm } = Modal;

interface ProcessesListProps {
  workflowId: string;
  persistedType: PersistedType;
  entityClassName: string;
}

interface ProcessRow {
  key: string;
  id: string;
  name: string;
  description: string;
  persisted: boolean;
  isTemplate: boolean;
}

export const ProcessesList: React.FC<ProcessesListProps> = ({
  workflowId,
  persistedType,
  entityClassName,
}) => {
  const navigate = useNavigate();
  
  // Queries
  const { data: processes = [], isLoading, refetch } = useProcessesList(entityClassName);

  // Mutations
  const deleteProcessMutation = useDeleteProcess();
  const copyProcessMutation = useCopyProcess();
  
  // Table data
  const tableData = useMemo<ProcessRow[]>(() => {
    return processes.map((process: any) => ({
      key: process.id?.persistedId || process.id?.runtimeId || process.id,
      id: process.id?.persistedId || process.id?.runtimeId || process.id,
      name: process.name,
      description: process.description || '',
      persisted: process.persisted !== undefined ? process.persisted : true,
      isTemplate: process.isTemplate || false,
    }));
  }, [processes]);
  
  // Handlers
  const handleAddNew = () => {
    navigate(
      `/process/new?workflowId=${workflowId}&persistedType=persisted&entityClassName=${entityClassName}&workflowPersistedType=${persistedType}`
    );
  };

  const handleViewProcess = (record: ProcessRow) => {
    const processPersistedType = record.persisted ? 'persisted' : 'transient';
    navigate(
      `/process/${record.id}?persistedType=${processPersistedType}&entityClassName=${entityClassName}&workflowId=${workflowId}&workflowPersistedType=${persistedType}`
    );
  };

  const handleCopy = async (record: ProcessRow) => {
    try {
      const processPersistedType = record.persisted ? 'persisted' : 'transient';
      const newProcessId = await copyProcessMutation.mutateAsync({
        persistedType: processPersistedType,
        processId: record.id,
      });

      message.success('Process copied successfully');
      refetch();

      // Navigate to the new process
      navigate(
        `/process/${newProcessId}?persistedType=${processPersistedType}&entityClassName=${entityClassName}&workflowId=${workflowId}&workflowPersistedType=${persistedType}`
      );
    } catch (error) {
      message.error('Failed to copy process');
    }
  };
  
  const handleDelete = (record: ProcessRow) => {
    confirm({
      title: 'Delete confirmation',
      content: 'Are you sure you want to delete this process?',
      okText: 'Delete',
      okType: 'danger',
      cancelText: 'Cancel',
      onOk: async () => {
        try {
          const processPersistedType = record.persisted ? 'persisted' : 'transient';
          await deleteProcessMutation.mutateAsync({
            persistedType: processPersistedType,
            processId: record.id,
          });
          message.success('Process deleted successfully');
          refetch();
        } catch (error) {
          message.error('Failed to delete process');
        }
      },
    });
  };
  
  // Table columns
  const columns: ColumnsType<ProcessRow> = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      width: 300,
      sorter: (a, b) => a.name.localeCompare(b.name),
      render: (name: string, record) => (
        <a onClick={() => handleViewProcess(record)}>{name}</a>
      ),
    },
    {
      title: 'Persisted',
      dataIndex: 'persisted',
      key: 'persisted',
      width: 150,
      sorter: (a, b) => Number(a.persisted) - Number(b.persisted),
      render: (persisted: boolean) => <StateIndicator state={persisted} />,
    },
    {
      title: 'Template',
      dataIndex: 'isTemplate',
      key: 'isTemplate',
      width: 150,
      sorter: (a, b) => Number(a.isTemplate) - Number(b.isTemplate),
      render: (isTemplate: boolean) => <StateIndicator state={isTemplate} />,
    },
    {
      title: 'Description',
      dataIndex: 'description',
      key: 'description',
      ellipsis: true,
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 180,
      render: (_: any, record: ProcessRow) => (
        <Space size="small">
          <Tooltip title="Copy">
            <Button
              type="primary"
              size="small"
              icon={<CopyOutlined />}
              onClick={() => handleCopy(record)}
              loading={copyProcessMutation.isPending}
            />
          </Tooltip>
          <Tooltip title="Delete">
            <Button
              danger
              size="small"
              icon={<DeleteOutlined />}
              onClick={() => handleDelete(record)}
              loading={deleteProcessMutation.isPending}
            />
          </Tooltip>
        </Space>
      ),
    },
  ];
  
  return (
    <div id="processes-list" className="processes-list">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <h2>Processes</h2>
        <Button type="primary" icon={<PlusOutlined />} onClick={handleAddNew}>
          Create new process
        </Button>
      </div>
      
      <Table
        columns={columns}
        dataSource={tableData}
        loading={isLoading}
        bordered
        pagination={false}
      />
    </div>
  );
};

export default ProcessesList;
