// .old_project /packages/statemachine/src/components/TransitionsList.vue
<template>
  <div id="transitions-list" class="transitions-list">
    <div class="title">
      <h2>Transitions</h2>
      <div class="buttons">
        <el-button v-if="!isRuntime" @click="onAddNew" type="primary">
          <font-awesome-icon :icon="['fas', 'plus']"/>
          Create new transition
        </el-button>
        <el-button v-if="!isRuntime" @click="onShowState" type="primary">
          <font-awesome-icon :icon="['fas', 'rectangle-list']"/>
          List of states
        </el-button>
      </div>
    </div>

    <el-table v-loading="isLoading" :data="tableData" border style="width: 100%">
      <el-table-column prop="index" label="№" width="50">
        <template #default="{row}">
          <RouterLink :to="transitionLink(row)">
            <el-link type="primary">{{ row.index }}</el-link>
          </RouterLink>
        </template>
      </el-table-column>
      <el-table-column sortable prop="active" label="Active" width="150">
        <template v-slot:default="{ row }">
          <StateComponent :state="row.active"/>
        </template>
      </el-table-column>
      <el-table-column sortable prop="persisted" label="Persisted" width="150">
        <template v-slot:default="{ row }">
          <StateComponent :state="row.persisted"/>
        </template>
      </el-table-column>
      <el-table-column sortable prop="automated" label="Automated" width="150">
        <template v-slot:default="{ row }">
          <StateAutomatedComponent :state="row.automated"/>
        </template>
      </el-table-column>
      <el-table-column sortable prop="name" label="Transition">
        <template v-slot:default="{ row }">
          <RouterLink :to="transitionLink(row)">
            <el-link type="primary">{{ row.name }}</el-link>
          </RouterLink>
        </template>
      </el-table-column>
      <el-table-column sortable prop="startStateName" label="Start state">
        <template v-slot:default="{ row }">
          <template v-if="row.startStateName.toLowerCase()==='none' || !row.persisted">
            {{ row.startStateName }}
          </template>
          <RouterLink v-else :to="stateLink(row, 'startStateId')">
            <el-link type="primary">{{ row.startStateName }}</el-link>
          </RouterLink>
        </template>
      </el-table-column>
      <el-table-column sortable prop="endStateName" label="End state">
        <template v-slot:default="{ row }">
          <template v-if="row.persisted">
            <RouterLink :to="stateLink(row, 'endStateId')">
              <el-link type="primary">{{ row.endStateName }}</el-link>
            </RouterLink>
          </template>
          <template v-else>
            {{ row.endStateName }}
          </template>
        </template>
      </el-table-column>
      <el-table-column v-if="!isRuntime" label="Transition Actions" width="180">
        <template v-slot:default="{ row }">
          <el-button @click="onClickCopy(row)" type="primary" size="default">
            <font-awesome-icon :icon="['fas', 'copy']"/>
          </el-button>
          <el-button @click="onClickDelete(row)" type="danger" size="default">
            <font-awesome-icon :icon="['fas', 'trash']"/>
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <StatesListPopUp v-if="!isRuntime" ref="statesListPopUpRef" :persistedType="persistedType"
                     :workflowId="workflowId"/>
  </div>
</template>

<script setup lang="ts">
import {useStatemachineStore} from "../stores/statemachine";
import {computed, ref, onMounted, onBeforeUnmount} from "vue";
import StateComponent from "../components/States/StateComponent.vue";
import StateAutomatedComponent from "../components/States/StateAutomatedComponent.vue";
import {useRouter} from "vue-router";
import {ElMessageBox} from "element-plus";
import {getPersistedType} from "../helpers/HelperData";
import StatesListPopUp from "./StatesListPopUp.vue";
import eventBus from "@cyoda/ui-lib/src/plugins/eventBus";

const statemachineStore = useStatemachineStore();
const isLoading = ref(null);
const statesListPopUpRef = ref(null);

const props = defineProps({
  workflowId: {
    default: null,
  },
  persistedType: {
    default: "",
  },
  entityClassName: {
    default: "",
  }
})

const transitionsList = ref([]);
const router = useRouter();

onMounted(() => {
  loadTransitionsList();
  eventBus.$on('transitions:reload', loadTransitionsList);
})

onBeforeUnmount(() => {
  eventBus.$off('transitions:reload', loadTransitionsList);
})

async function loadTransitionsList() {
  isLoading.value = true;
  try {
    const {data} = await statemachineStore.getTransitionsList(props.persistedType, props.workflowId);
    transitionsList.value = data.Data;
  } finally {
    isLoading.value = false;
  }
}

const tableData = computed(() => {
  return transitionsList.value.map((el, index) => {
    return {
      index: index + 1,
      ...el
    }
  })
});

function onAddNew() {
  router.push(`/statemachine/transition/new?workflowId=${props.workflowId}&persistedType=${props.persistedType}&entityClassName=${props.entityClassName}`);
}

function transitionLink(row) {
  const workflowId = row.workflowId || props.workflowId;
  return `/statemachine/transition/${row.id}?workflowId=${workflowId}&persistedType=${getPersistedType(row.persisted)}&entityClassName=${props.entityClassName}`;
}

function stateLink(row, stateField) {
  const workflowId = row.workflowId || props.workflowId;
  return `/statemachine/state/${row[stateField]}?workflowId=${workflowId}&persistedType=${getPersistedType(row.persisted)}&entityClassName=${props.entityClassName}`;
}

function onShowState() {
  statesListPopUpRef.value.dialogVisible = true;
}

async function onClickCopy(row) {
  try {
    isLoading.value = true;
    const {data} = await statemachineStore.getTransition(props.persistedType, props.workflowId, row.id);
    const dataForm = data.Data;
    delete dataForm.id;
    dataForm.name = `[ DUPLICATE ] ${dataForm.name}`;
    await statemachineStore.postTransition(props.persistedType, props.workflowId, dataForm);
    await loadTransitionsList();
  } finally {
    isLoading.value = false;
  }
}

function onClickDelete(row) {
  ElMessageBox.confirm("Are you sure you want to delete transition?", "Delete confirmation", {
    callback: async (action) => {
      if (action === "confirm") {
        try {
          isLoading.value = true;
          await statemachineStore.deleteTransition(props.persistedType, props.workflowId, row.id);
          await loadTransitionsList();
          eventBus.$emit('workflow:reload');
        } finally {
          isLoading.value = false;
        }
      }
    }
  });
}

const isRuntime = computed(() => {
  return props.persistedType === 'runtime';
});
</script>

<style scoped lang="scss">
.transitions-list {
  .title {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
}
</style>

// react-project/packages/statemachine-react/src/components/TransitionsList.tsx
/**
 * Transitions List Component
 * Display and manage transitions for a workflow
 * Migrated from: .old_project/packages/statemachine/src/components/TransitionsList.vue
 */

import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Table, Button, Space, Tooltip, Modal, message } from 'antd';
import { PlusOutlined, CopyOutlined, DeleteOutlined, UnorderedListOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import { useTransitionsList, useDeleteTransition, useCopyTransition } from '../hooks/useStatemachine';
import { StatesListModal } from './StatesListModal';
import { StateIndicator } from './StateIndicator';
import type { PersistedType } from '../types';

const { confirm } = Modal;

interface TransitionsListProps {
  workflowId: string;
  persistedType: PersistedType;
  entityClassName: string;
}

interface TransitionRow {
  key: string;
  index: number;
  id: string;
  name: string;
  active: boolean;
  persisted: boolean;
  automated: boolean;
  startStateName: string;
  startStateId: string;
  endStateName: string;
  endStateId: string;
}

export const TransitionsList: React.FC<TransitionsListProps> = ({
  workflowId,
  persistedType,
  entityClassName,
}) => {
  const navigate = useNavigate();
  const isRuntime = persistedType === 'runtime';
  const [statesModalVisible, setStatesModalVisible] = useState(false);

  // Queries
  const { data: transitions = [], isLoading, refetch } = useTransitionsList(persistedType, workflowId);

  // Mutations
  const deleteTransitionMutation = useDeleteTransition();
  const copyTransitionMutation = useCopyTransition();
  
  // Table data
  const tableData = useMemo<TransitionRow[]>(() => {
    return transitions.map((transition: any, index: number) => ({
      key: transition.id,
      index: index + 1,
      id: transition.id,
      name: transition.name,
      active: transition.active !== undefined ? transition.active : true,
      persisted: transition.persisted !== undefined ? transition.persisted : true,
      automated: transition.automated || false,
      startStateName: transition.startStateName || transition.fromState || 'None',
      startStateId: transition.startStateId || transition.fromState,
      endStateName: transition.endStateName || transition.toState || 'None',
      endStateId: transition.endStateId || transition.toState,
    }));
  }, [transitions]);
  
  // Handlers
  const handleAddNew = () => {
    navigate(
      `/transition/new?workflowId=${workflowId}&persistedType=${persistedType}&entityClassName=${entityClassName}`
    );
  };

  const handleShowStates = () => {
    setStatesModalVisible(true);
  };

  const handleViewTransition = (record: TransitionRow) => {
    navigate(
      `/transition/${record.id}?workflowId=${workflowId}&persistedType=${persistedType}&entityClassName=${entityClassName}`
    );
  };

  const handleCopy = async (record: TransitionRow) => {
    try {
      const newTransitionId = await copyTransitionMutation.mutateAsync({
        persistedType,
        workflowId,
        transitionId: record.id,
      });

      message.success('Transition copied successfully');
      refetch();

      // Navigate to the new transition
      navigate(
        `/transition/${newTransitionId}?workflowId=${workflowId}&persistedType=${persistedType}&entityClassName=${entityClassName}`
      );
    } catch (error) {
      message.error('Failed to copy transition');
    }
  };
  
  const handleDelete = (record: TransitionRow) => {
    confirm({
      title: 'Delete confirmation',
      content: 'Are you sure you want to delete this transition?',
      okText: 'Delete',
      okType: 'danger',
      cancelText: 'Cancel',
      onOk: async () => {
        try {
          await deleteTransitionMutation.mutateAsync({
            persistedType,
            workflowId,
            transitionId: record.id,
          });
          message.success('Transition deleted successfully');
          refetch();
        } catch (error) {
          message.error('Failed to delete transition');
        }
      },
    });
  };
  
  const handleViewState = (record: TransitionRow, stateType: 'start' | 'end') => {
    const stateId = stateType === 'start' ? record.startStateId : record.endStateId;
    if (!stateId || stateId.toLowerCase() === 'none') return;

    navigate(
      `/state/${stateId}?workflowId=${workflowId}&persistedType=${persistedType}&entityClassName=${entityClassName}`
    );
  };
  
  // Table columns
  const columns: ColumnsType<TransitionRow> = [
    {
      title: '№',
      dataIndex: 'index',
      key: 'index',
      width: 50,
      render: (index: number, record) => (
        <a onClick={() => handleViewTransition(record)}>{index}</a>
      ),
    },
    {
      title: 'Active',
      dataIndex: 'active',
      key: 'active',
      width: 150,
      sorter: (a, b) => Number(a.active) - Number(b.active),
      render: (active: boolean) => <StateIndicator state={active} />,
    },
    {
      title: 'Persisted',
      dataIndex: 'persisted',
      key: 'persisted',
      width: 150,
      sorter: (a, b) => Number(a.persisted) - Number(b.persisted),
      render: (persisted: boolean) => <StateIndicator state={persisted} />,
    },
    {
      title: 'Automated',
      dataIndex: 'automated',
      key: 'automated',
      width: 150,
      sorter: (a, b) => Number(a.automated) - Number(b.automated),
      render: (automated: boolean) => <StateIndicator state={automated} type="automated" />,
    },
    {
      title: 'Transition',
      dataIndex: 'name',
      key: 'name',
      sorter: (a, b) => a.name.localeCompare(b.name),
      render: (name: string, record) => (
        <a onClick={() => handleViewTransition(record)}>{name}</a>
      ),
    },
    {
      title: 'Start state',
      dataIndex: 'startStateName',
      key: 'startStateName',
      sorter: (a, b) => a.startStateName.localeCompare(b.startStateName),
      render: (name: string, record) => {
        if (name.toLowerCase() === 'none' || !record.persisted) {
          return <span>{name}</span>;
        }
        return <a onClick={() => handleViewState(record, 'start')}>{name}</a>;
      },
    },
    {
      title: 'End state',
      dataIndex: 'endStateName',
      key: 'endStateName',
      sorter: (a, b) => a.endStateName.localeCompare(b.endStateName),
      render: (name: string, record) => {
        if (!record.persisted) {
          return <span>{name}</span>;
        }
        return <a onClick={() => handleViewState(record, 'end')}>{name}</a>;
      },
    },
    ...(!isRuntime
      ? [
          {
            title: 'Transition Actions',
            key: 'actions',
            width: 180,
            render: (_: any, record: TransitionRow) => (
              <Space size="small">
                <Tooltip title="Copy">
                  <Button
                    type="primary"
                    size="small"
                    icon={<CopyOutlined />}
                    onClick={() => handleCopy(record)}
                    loading={copyTransitionMutation.isPending}
                  />
                </Tooltip>
                <Tooltip title="Delete">
                  <Button
                    danger
                    size="small"
                    icon={<DeleteOutlined />}
                    onClick={() => handleDelete(record)}
                    loading={deleteTransitionMutation.isPending}
                  />
                </Tooltip>
              </Space>
            ),
          },
        ]
      : []),
  ];
  
  return (
    <div id="transitions-list" className="transitions-list">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <h2>Transitions</h2>
        {!isRuntime && (
          <Space>
            <Button type="primary" icon={<PlusOutlined />} onClick={handleAddNew}>
              Create new transition
            </Button>
            <Button type="primary" icon={<UnorderedListOutlined />} onClick={handleShowStates}>
              List of states
            </Button>
          </Space>
        )}
      </div>
      
      <Table
        columns={columns}
        dataSource={tableData}
        loading={isLoading}
        bordered
        pagination={false}
      />

      <StatesListModal
        visible={statesModalVisible}
        onClose={() => setStatesModalVisible(false)}
        workflowId={workflowId}
        persistedType={persistedType}
        entityClassName={entityClassName}
      />
    </div>
  );
};

export default TransitionsList;
