// react-project/packages/statemachine-react/src/components/CriteriaList.tsx
/**
 * Criteria List Component
 * Display and manage criteria for a workflow
 * Migrated from: .old_project/packages/statemachine/src/components/CriteriaList.vue
 */

import React, { useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { Table, Button, Space, Tooltip, Modal, message } from 'antd';
import { PlusOutlined, CopyOutlined, DeleteOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import { useCriteriaList, useDeleteCriteria, useCopyCriteria } from '../hooks/useStatemachine';
import { StateIndicator } from './StateIndicator';
import type { PersistedType } from '../types';

const { confirm } = Modal;

interface CriteriaListProps {
  workflowId: string;
  persistedType: PersistedType;
  entityClassName: string;
}

interface CriteriaRow {
  key: string;
  id: string;
  name: string;
  description: string;
  persisted: boolean;
}

export const CriteriaList: React.FC<CriteriaListProps> = ({
  workflowId,
  persistedType,
  entityClassName,
}) => {
  const navigate = useNavigate();
  
  // Queries
  const { data: criteriaList = [], isLoading, refetch } = useCriteriaList(entityClassName);

  // Mutations
  const deleteCriteriaMutation = useDeleteCriteria();
  const copyCriteriaMutation = useCopyCriteria();
  
  // Table data
  const tableData = useMemo<CriteriaRow[]>(() => {
    return criteriaList.map((criteria: any) => ({
      key: criteria.id,
      id: criteria.id,
      name: criteria.name || criteria.id,
      description: criteria.description || '',
      persisted: criteria.persisted !== undefined ? criteria.persisted : true,
    }));
  }, [criteriaList]);
  
  // Handlers
  const handleAddNew = () => {
    navigate(
      `/criteria/new?persistedType=persisted&entityClassName=${entityClassName}&workflowPersistedType=${persistedType}&workflowId=${workflowId}`
    );
  };

  const handleViewCriteria = (record: CriteriaRow) => {
    const criteriaPersistedType = record.persisted ? 'persisted' : 'transient';
    navigate(
      `/criteria/${record.id}?persistedType=${criteriaPersistedType}&entityClassName=${entityClassName}&workflowPersistedType=${persistedType}&workflowId=${workflowId}`
    );
  };

  const handleCopy = async (record: CriteriaRow) => {
    try {
      const criteriaPersistedType = record.persisted ? 'persisted' : 'transient';
      const newCriteriaId = await copyCriteriaMutation.mutateAsync({
        persistedType: criteriaPersistedType,
        criteriaId: record.id,
      });

      message.success('Criteria copied successfully');
      refetch();

      // Navigate to the new criteria
      navigate(
        `/criteria/${newCriteriaId}?persistedType=${criteriaPersistedType}&entityClassName=${entityClassName}&workflowPersistedType=${persistedType}&workflowId=${workflowId}`
      );
    } catch (error) {
      message.error('Failed to copy criteria');
    }
  };
  
  const handleDelete = (record: CriteriaRow) => {
    confirm({
      title: 'Delete confirmation',
      content: 'Are you sure you want to delete this criteria?',
      okText: 'Delete',
      okType: 'danger',
      cancelText: 'Cancel',
      onOk: async () => {
        try {
          const criteriaPersistedType = record.persisted ? 'persisted' : 'transient';
          await deleteCriteriaMutation.mutateAsync({
            persistedType: criteriaPersistedType,
            criteriaId: record.id,
          });
          message.success('Criteria deleted successfully');
          refetch();
        } catch (error) {
          message.error('Failed to delete criteria');
        }
      },
    });
  };
  
  // Table columns
  const columns: ColumnsType<CriteriaRow> = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      width: 300,
      sorter: (a, b) => a.name.localeCompare(b.name),
      render: (name: string, record) => (
        <a onClick={() => handleViewCriteria(record)}>{name}</a>
      ),
    },
    {
      title: 'Persisted',
      dataIndex: 'persisted',
      key: 'persisted',
      width: 150,
      sorter: (a, b) => Number(a.persisted) - Number(b.persisted),
      render: (persisted: boolean) => <StateIndicator state={persisted} />,
    },
    {
      title: 'Description',
      dataIndex: 'description',
      key: 'description',
      ellipsis: true,
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 180,
      render: (_: any, record: CriteriaRow) => (
        <Space size="small">
          <Tooltip title="Copy">
            <Button
              type="primary"
              size="small"
              icon={<CopyOutlined />}
              onClick={() => handleCopy(record)}
              loading={copyCriteriaMutation.isPending}
            />
          </Tooltip>
          <Tooltip title="Delete">
            <Button
              danger
              size="small"
              icon={<DeleteOutlined />}
              onClick={() => handleDelete(record)}
              loading={deleteCriteriaMutation.isPending}
            />
          </Tooltip>
        </Space>
      ),
    },
  ];
  
  return (
    <div id="criteria-list" className="criteria-list">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <h2>Custom criteria</h2>
        <Button type="primary" icon={<PlusOutlined />} onClick={handleAddNew}>
          Create new criterion
        </Button>
      </div>
      
      <Table
        columns={columns}
        dataSource={tableData}
        loading={isLoading}
        bordered
        pagination={false}
      />
    </div>
  );
};

export default CriteriaList;

// .old_project /packages/statemachine/src/components/CriteriaList.vue
<template>
  <div id="criteria-list" class="criteria-list">
    <div class="title">
      <h2>Custom criteria</h2>
      <div class="buttons">
        <el-button @click="onAddNew" type="primary">
          <font-awesome-icon :icon="['fas', 'plus']"/>
          Create new criterion
        </el-button>
      </div>
    </div>

    <el-table v-loading="isLoading" :data="tableData" border style="width: 100%">
      <el-table-column sortable prop="name" label="Name" width="300">
        <template v-slot:default="{ row }">
          <RouterLink :to="criteriaLink(row)">
            <el-link type="primary">
              {{ row.name || row.id }}
            </el-link>
          </RouterLink>
        </template>
      </el-table-column>
      <el-table-column sortable prop="persisted" label="Persisted" width="150">
        <template v-slot:default="{ row }">
          <StateComponent :state="row.persisted"/>
        </template>
      </el-table-column>

      <el-table-column sortable prop="description" label="Description"/>

      <el-table-column label="Actions" width="180">
        <template v-slot:default="{ row }">
          <el-button @click="onClickCopy(row)" type="primary" size="default">
            <font-awesome-icon :icon="['fas', 'copy']"/>
          </el-button>
          <el-button @click="onClickDelete(row)" type="danger" size="default">
            <font-awesome-icon :icon="['fas', 'trash']"/>
          </el-button>
        </template>
      </el-table-column>
    </el-table>
  </div>
</template>

<script setup lang="ts">
import {useStatemachineStore} from "../stores/statemachine";
import {computed, ref, onMounted} from "vue";
import StateComponent from "../components/States/StateComponent.vue";
import StateAutomatedComponent from "../components/States/StateAutomatedComponent.vue";
import {useRoute, useRouter} from "vue-router";
import {ElMessageBox} from "element-plus";
import axios from "@cyoda/ui-lib/src/plugins/axios";
import {getPersistedType} from "../helpers/HelperData";

const statemachineStore = useStatemachineStore();
const isLoading = ref(null);

const props = defineProps({
  persistedType: {
    default: "",
  },
  entityClassName: {
    default: "",
  },
  workflowId: {
    default: "",
  }
})

const criteriaList = ref([]);
const router = useRouter();
const route = useRoute();

onMounted(async () => {
  loadCriteriaList();
})

async function loadCriteriaList() {
  const {data} = await statemachineStore.getCriteriaList(props.entityClassName);
  criteriaList.value = data;
}

const tableData = computed(() => {
  return criteriaList.value;
});

function onAddNew() {
  router.push(`/statemachine/criteria/new?persistedType=persisted&entityClassName=${route.query.entityClassName}&workflowPersistedType=${props.persistedType}&workflowId=${props.workflowId}`);
}

function criteriaLink(row) {
  return `/statemachine/criteria/${row.id}?persistedType=${getPersistedType(row.persisted)}&entityClassName=${route.query.entityClassName}&workflowPersistedType=${props.persistedType}&workflowId=${props.workflowId}`;
}

async function onClickCopy(row) {
  try {
    isLoading.value = true;
    const {data} = await statemachineStore.getCriteria(getPersistedType(row.persisted), row.id);
    const dataForm = data;
    delete dataForm.id;
    dataForm.name = `[ DUPLICATE ] ${dataForm.name}`;
    await statemachineStore.postCriteria(getPersistedType(row.persisted), dataForm);
    await loadCriteriaList();
  } finally {
    isLoading.value = false;
  }
}

function onClickDelete(row) {
  ElMessageBox.confirm(`Are you sure you want to delete process "${row.name}"?`, "Delete confirmation", {
    callback: async (action) => {
      if (action === "confirm") {
        try {
          isLoading.value = true;
          await statemachineStore.deleteCriteria(getPersistedType(row.persisted), row.id);
          await loadCriteriaList();
        } finally {
          isLoading.value = false;
        }
      }
    }
  });
}
</script>

<style scoped lang="scss">
.criteria-list {
  .title {
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
}
</style>
