// react-project/packages/tableau-react/src/components/ReportTableGroup.tsx
/**
 * ReportTableGroup Component
 * Migrated from: .old_project/packages/http-api/src/components/ReportTable/ReportTableGroup.vue
 */

import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { Table } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useQuery } from '@tanstack/react-query';
import { axios } from '@cyoda/http-api-react';
import ReportTableRows from './ReportTableRows';
import HelperReportTable, { type ReportGroup, type WrappedEntityModel } from '../utils/HelperReportTable';
import type { ConfigDefinition } from '../types';
import { HelperStorage } from '@cyoda/ui-lib-react';
import './ReportTableGroup.scss';

interface ReportTableGroupProps {
  tableLinkGroup: string;
  showHeader?: boolean;
  displayGroupType: 'in' | 'out';
  configDefinition: ConfigDefinition;
  lazyLoading: boolean;
  smallPagination?: boolean;
  onRowClick?: (row: any) => void;
}

interface TableDataRow {
  key: string;
  group: string;
  _link_rows: string;
  _link_groups: string | null;
  isNext: boolean;
  [key: string]: any;
}

const STORAGE_KEY = 'ReportTableGroup';

const ReportTableGroup: React.FC<ReportTableGroupProps> = ({
  tableLinkGroup,
  showHeader = true,
  displayGroupType,
  configDefinition,
  lazyLoading,
  smallPagination = false,
  onRowClick,
}) => {
  const storage = useMemo(() => new HelperStorage(), []);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(() => storage.get<number>(STORAGE_KEY, 5) || 5);
  const [selectedRowKey, setSelectedRowKey] = useState<string | null>(null);
  const [expandedRowKeys, setExpandedRowKeys] = useState<string[]>([]);

  // Load groups data
  const { data: groups, isLoading } = useQuery({
    queryKey: ['reportGroups', tableLinkGroup],
    queryFn: async () => {
      if (!tableLinkGroup) return null;
      const { data } = await axios.get<ReportGroup>(tableLinkGroup);
      return data;
    },
    enabled: !!tableLinkGroup,
  });

  // Calculate table columns
  const tableColumns = useMemo(() => {
    if (!groups || Object.keys(groups).length === 0) return [];

    const columns: ColumnsType<TableDataRow> = [
      {
        title: 'Group',
        dataIndex: 'group',
        key: 'group',
        width: 350,
      },
    ];

    const additionalColumns = HelperReportTable.getHeaderHistoryGroupColumns(groups);
    additionalColumns.forEach((col) => {
      columns.push({
        title: col.label,
        dataIndex: col.prop,
        key: col.prop,
        width: 350,
      });
    });

    return columns;
  }, [groups]);

  // Calculate table data
  const tableData = useMemo((): TableDataRow[] => {
    if (!groups || Object.keys(groups).length === 0) return [];

    return groups._embedded.wrappedEntityModels.slice(0, groups.page.size).map((model, index) => {
      const formattedRow = HelperReportTable.formatGroupRow(model);
      return {
        ...formattedRow,
        key: `group-${index}`,
      };
    });
  }, [groups]);

  // Handle row click
  const handleRowClick = useCallback(
    (record: TableDataRow) => {
      if (!record.isNext && displayGroupType === 'out') {
        setSelectedRowKey(record.key);
        onRowClick?.(record);
      }
    },
    [displayGroupType, onRowClick]
  );

  // Handle page size change
  useEffect(() => {
    storage.set(STORAGE_KEY, pageSize);
  }, [pageSize, storage]);

  // Expandable row render
  const expandedRowRender = useCallback(
    (record: TableDataRow) => {
      // If it has nested groups, render another ReportTableGroup
      if (record.isNext && record._link_groups) {
        return (
          <div className="inner-group-table">
            <ReportTableGroup
              tableLinkGroup={record._link_groups}
              showHeader={false}
              displayGroupType={displayGroupType}
              configDefinition={configDefinition}
              lazyLoading={lazyLoading}
              smallPagination={smallPagination}
            />
          </div>
        );
      }

      // If displayGroupType is 'in', render rows directly
      if (displayGroupType === 'in' && record._link_rows) {
        return (
          <ReportTableRows
            tableLinkRows={record._link_rows}
            lazyLoading={lazyLoading}
            configDefinition={configDefinition}
          />
        );
      }

      return null;
    },
    [displayGroupType, configDefinition, lazyLoading, smallPagination]
  );

  // Determine if row is expandable
  const isRowExpandable = useCallback(
    (record: TableDataRow) => {
      if (tableData.length === 0) return false;
      const firstRow = tableData[0];
      return firstRow.isNext || displayGroupType === 'in';
    },
    [tableData, displayGroupType]
  );

  // Calculate max height for table
  const [maxHeight, setMaxHeight] = useState(500);

  useEffect(() => {
    const resize = () => {
      const headerHeight = document.querySelector('header.sticky')?.clientHeight || 0;
      let height = window.innerHeight - headerHeight - 100;
      if (height < 150) height = 200;
      setMaxHeight(height);
    };

    resize();
    window.addEventListener('resize', resize);
    return () => window.removeEventListener('resize', resize);
  }, []);

  // Pagination config
  const paginationConfig = smallPagination
    ? {
        simple: true,
        current: currentPage,
        pageSize: pageSize,
        total: tableData.length,
        onChange: (page: number, size: number) => {
          setCurrentPage(page);
          setPageSize(size);
        },
      }
    : {
        current: currentPage,
        pageSize: pageSize,
        total: tableData.length,
        showSizeChanger: true,
        showTotal: (total: number) => `Total ${total} items`,
        onChange: (page: number, size: number) => {
          setCurrentPage(page);
          setPageSize(size);
        },
      };

  return (
    <div className="report-table-group">
      <Table
        columns={tableColumns}
        dataSource={tableData}
        loading={isLoading}
        bordered
        size="small"
        showHeader={showHeader}
        scroll={{ y: maxHeight }}
        pagination={paginationConfig}
        expandable={{
          expandedRowRender: isRowExpandable(tableData[0]) ? expandedRowRender : undefined,
          expandedRowKeys: expandedRowKeys,
          onExpandedRowsChange: (keys) => setExpandedRowKeys(keys as string[]),
        }}
        onRow={(record) => ({
          onClick: () => handleRowClick(record),
          className: selectedRowKey === record.key && displayGroupType === 'out' ? 'selected-row' : '',
        })}
      />
    </div>
  );
};

export default ReportTableGroup;

// .old_project /packages/http-api/src/components/ReportTable/ReportTableGroup.vue
<template>
  <data-tables
    :show-header="showHeader"
    :table-props="{
      border: true,
      size: 'mini',
      maxHeight: maxHeight
    }"
    :pagination-props="paginationProps"
    class="ab-style report-table-group"
    :data="tableData"
    ref="groupTableRef"
    size="small"
    @row-click="rowClick"
    :highlight-current-row="displayGroupType === 'out'"
    style="width: 100%"
    v-model:pageSize="form.pageSize"
    v-model:currentPage="form.currentPage"
  >
    <el-table-column v-if="tableData.length > 0 && (tableData[0].isNext || displayGroupType === 'in')" type="expand">
      <template #default="props">
        <ReportTableGroup v-if="props.row.isNext" :displayGroupType="displayGroupType" :lazyLoading="lazyLoading"
                          class="inner-group-table" :show-header="false" :configDefinition="configDefinition"
                          :tableLinkGroup="props.row._link_groups"/>
        <ReportTableRows v-else-if="displayGroupType === 'in'" :lazyLoading="lazyLoading"
                         :configDefinition="configDefinition" :tableLinkRows="props.row._link_rows"/>
      </template>
    </el-table-column>
    <el-table-column v-for="tableColumn in tableColumns" :key="tableColumn.label" :label="tableColumn.label"
                     :prop="tableColumn.prop" min-width="350px"></el-table-column>
  </data-tables>
</template>

<script setup lang="ts">
import {ref, computed, watch, onBeforeUnmount, reactive, onMounted} from "vue";

import axios from "@cyoda/ui-lib/src/plugins/axios";
import type {ReportGroup} from "@cyoda/ui-lib/src/types/types";
import ReportTableRows from "./ReportTableRows.vue";
import HelperReportTable from "../../helpers/HelperReportTable";
import type {ReportTableTableDataRow} from "./ReportTable";
import eventBus from "@cyoda/ui-lib/src/plugins/eventBus";
import HelperStorage from "@cyoda/cobi/src/helpers/HelperStorage";

const STORAGE_KEY = 'ReportTableGroup';

const helperStorage = new HelperStorage();
const form = reactive({
  currentPage: 1,
  pageSize: helperStorage.get(STORAGE_KEY, 5)
});

const props = defineProps({
  tableLinkGroup: {default: ""},
  showHeader: {default: true},
  displayGroupType: {default: ""},
  configDefinition: {
    default: () => {
      return {};
    }
  },
  lazyLoading: {default: false},
  smallPagination: {default: false},
});
const tableColumns = computed(() => {
  let columns: Array<{
    label: string;
    prop: string
  }> = [];
  if (Object.keys(groups.value).length > 0) {
    columns.push({
      label: "group",
      prop: "group"
    });
    columns = columns.concat(HelperReportTable.getHeaderHistoryGroupColumns(groups.value));
  }
  return columns;
});
const tableData = computed(() => {
  if (Object.keys(groups.value).length > 0) {
    return groups.value._embedded.wrappedEntityModels.slice(0, groups.value.page.size).map((el) => {
      let row = {
        group: `Group - ${el.content.groupValues.join(" | ")}`,
        _link_rows: el._links["/report/{id}/group_rows/{group_json_base64}"].href,
        _link_groups: (el._links["/report/{id}/{grouping_version}/groups/{parent_group_json_base64}"] && el._links["/report/{id}/{grouping_version}/groups/{parent_group_json_base64}"].href) || null,
        isNext: el.content.isNext
      };

      row = {
        ...row,
        ...HelperReportTable.getHeaderHistoryGroupSummaryData(el.content.summary)
      };
      return row;
    });
  } else {
    return [];
  }
});

const groupTableRef = ref(null);

let groups = ref({});

const paginationProps = computed(() => {
  let data = undefined;
  if (props.smallPagination) {
    data = {
      small: false,
      layout: 'pager'
    }
  }
  return data;
});

async function loadGroups(link: string) {
  const {data} = await axios.get<ReportGroup>(link);
  groups.value = data;
}

eventBus.$on("report-group-rows:row-click", onSelectedRow);

onBeforeUnmount(() => {
  eventBus.$off("report-group-rows:row-click", onSelectedRow);
});

function onSelectedRow() {
  groupTableRef.value.elTableRef.setCurrentRow();
}

watch(
  () => props.tableLinkGroup,
  (val: string) => {
    if (val) {
      loadGroups(val);
    }
  },
  {immediate: true}
);

async function rowClick(row: ReportTableTableDataRow) {
  if (!row.isNext && props.displayGroupType === "out") {
    eventBus.$emit("report-group-rows:row-click", JSON.parse(JSON.stringify(row)));
    groupTableRef.value.elTableRef.setCurrentRow(row);
  }
}

const maxHeight = ref(500);
onMounted(() => {
  resize();
})

function resize() {
  const headerHeight = document.querySelector('header.sticky')?.clientHeight || 0;
  let height = window.innerHeight - headerHeight - 100;
  if (height < 150) height = 200;
  maxHeight.value = height;
}

window.addEventListener('resize', resize);

function resetGroup(){
  groups.value={};
}

defineExpose({resetGroup});
</script>
