// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/DataLineage/DataLineage.vue
<template>
  <el-row :gutter="20">
    <el-col :span="6">
      <DataLineageFilter :filter="filter" />
    </el-col>
    <el-col :span="18">
      <DataLineageTransactions :requestClass="requestClass" :id="id" :transactionsData="transactionsDataComputed" />
    </el-col>
  </el-row>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";

import * as api from "../../../api";
import DataLineageFilter from "./DataLineageFilter.vue";
import DataLineageTransactions from "./DataLineageTransactions.vue";
import moment from "moment";
import { Transaction } from "../../../types/types";
import { Filter } from "./types";
import _ from "lodash";

const props = defineProps({
  requestClass: {
    default: ""
  },
  id: {
    default: ""
  }
});
const transactionsDataComputed = computed(() => {
  let transactionsDataValue: Transaction[] = JSON.parse(JSON.stringify(transactionsData.value));
  if (filter.value.dateFrom) {
    const dateFrom = moment(filter.value.dateFrom).format("X");
    transactionsDataValue = transactionsDataValue.filter((el) => {
      return moment(el.dateTime, "DD-MM-YYYY HH:mm:ss.SSS").format("X") >= dateFrom;
    });
  }
  if (filter.value.dateTo) {
    const dateTo = moment(filter.value.dateTo).format("X");
    transactionsDataValue = transactionsDataValue.filter((el) => {
      return moment(el.dateTime, "DD-MM-YYYY HH:mm:ss.SSS").format("X") <= dateTo;
    });
  }
  return transactionsDataValue;
});

let transactionsData = ref([]);

let filter = ref({
  dateFrom: "",
  dateTo: ""
});

(async function () {
  let { data } = await api.getEntityTransactions(props.requestClass, props.id);
  data = _.sortBy(data, [
    (el) => {
      return moment(el.dateTime, "DD-MM-YYYY HH:mm:ss.SSS").format("X");
    }
  ]).reverse();
  transactionsData.value = data;
})();
</script>

// react-project/packages/ui-lib-react/src/components/DataLineage/DataLineage.tsx
import React, { useState, useEffect } from 'react'
import { Row, Col } from 'antd'
import { DataLineageFilter } from '../DataLineageFilter'
import { DataLineageTransactions, Transaction } from '../DataLineageTransactions'
import dayjs from 'dayjs'
import './DataLineage.scss'

export interface DataLineageFilter {
  dateFrom: string
  dateTo: string
}

export interface DataLineageProps {
  requestClass?: string
  id?: string
  onLoadTransactions?: (requestClass: string, id: string) => Promise<Transaction[]>
  className?: string
}

/**
 * DataLineage Component
 * Main data lineage view with filter and transactions
 */
export const DataLineage: React.FC<DataLineageProps> = ({
  requestClass = '',
  id = '',
  onLoadTransactions,
  className = ''
}) => {
  const [transactionsData, setTransactionsData] = useState<Transaction[]>([])
  const [filter, setFilter] = useState<DataLineageFilter>({
    dateFrom: '',
    dateTo: ''
  })

  useEffect(() => {
    const loadData = async () => {
      if (onLoadTransactions && requestClass && id) {
        const data = await onLoadTransactions(requestClass, id)
        // Sort by date descending
        const sorted = [...data].sort((a, b) => {
          const dateA = dayjs(a.dateTime, 'DD-MM-YYYY HH:mm:ss.SSS')
          const dateB = dayjs(b.dateTime, 'DD-MM-YYYY HH:mm:ss.SSS')
          return dateB.unix() - dateA.unix()
        })
        setTransactionsData(sorted)
      }
    }
    loadData()
  }, [requestClass, id, onLoadTransactions])

  const filteredTransactions = transactionsData.filter((transaction) => {
    const transactionDate = dayjs(transaction.dateTime, 'DD-MM-YYYY HH:mm:ss.SSS')
    
    if (filter.dateFrom) {
      const dateFrom = dayjs(filter.dateFrom)
      if (transactionDate.isBefore(dateFrom)) {
        return false
      }
    }
    
    if (filter.dateTo) {
      const dateTo = dayjs(filter.dateTo)
      if (transactionDate.isAfter(dateTo)) {
        return false
      }
    }
    
    return true
  })

  return (
    <div className={`data-lineage ${className}`}>
      <Row gutter={20}>
        <Col span={6}>
          <DataLineageFilter
            filter={filter}
            onFilterChange={setFilter}
          />
        </Col>
        <Col span={18}>
          <DataLineageTransactions
            requestClass={requestClass}
            id={id}
            transactionsData={filteredTransactions}
          />
        </Col>
      </Row>
    </div>
  )
}
