// packages/cobi-react/src/pages/DataSourceConfig/components/DialogConnection/DialogConnectionBlobStorage.tsx
import React from 'react';
import { Form, Input } from 'antd';

interface DialogConnectionBlobStorageProps {
  connectionDetailsDto: any;
  onChange?: (values: any) => void;
}

const DialogConnectionBlobStorage: React.FC<DialogConnectionBlobStorageProps> = ({
  connectionDetailsDto,
  onChange,
}) => {
  const handleChange = (field: string, value: any) => {
    if (onChange) {
      onChange({ ...connectionDetailsDto, [field]: value });
    }
  };

  return (
    <div className="dialog-connection-blob-storage">
      <Form.Item
        label="Name"
        name="name"
        rules={[{ required: true, message: 'Please input connection name' }]}
      >
        <Input
          value={connectionDetailsDto.name}
          onChange={(e) => handleChange('name', e.target.value)}
          placeholder="Enter connection name"
        />
      </Form.Item>
    </div>
  );
};

export default DialogConnectionBlobStorage;

// .old_project /packages/cobi/src/components/DataSourceConfig/DialogConnection/DialogConnectionBlobStorage.vue
<template>
  <div class="dialog-connection-workflow">
    <el-form-item label="Name" prop="name">
      <el-input v-model.trim="connectionDetailsDto.name" />
    </el-form-item>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  connectionDetailsDto: {
    default: () => {
      return {};
    }
  }
});
</script>
