// .old_project /packages/processing-manager/src/components/PmTransitionVersions/TransitionVersionsAggregated.vue
<template>
  <div class="card">
    <div class="card-header">Aggregated by transaction view</div>
    <div class="card-body">
      <el-table :data="tableData" style="width: 100%">
        <el-table-column type="expand">
          <template v-slot:default="props">
            <el-table :data="props.row.subTable" style="width: 100%">
              <el-table-column prop="colType" label="Column type"/>
              <el-table-column prop="colTimeMillis" label="Column time">
                <template v-slot:default="scopeCol">
                  {{ $filters.dateTime(scopeCol.row.colTimeMillis) }}
                </template>
              </el-table-column>
            </el-table>
          </template>
        </el-table-column>
        <el-table-column label="Version(time based)" width="320px" prop="version"/>
        <el-table-column label="Transaction Id" prop="transactionId">
          <template v-slot:default="scope">
            <router-link
              :to="`/processing-ui/nodes/${route.params.name}/transaction/${scope.row.transactionId}`">
              {{ scope.row.transactionId }}
            </router-link>
          </template>
        </el-table-column>
        <el-table-column label="Action Type" prop="actionType"></el-table-column>
      </el-table>
    </div>
  </div>
</template>

<script setup lang="ts">
import {useRoute} from "vue-router";
import {computed} from "vue";

const route = useRoute();
const props = defineProps({rows: {default: () => []}});
const tableData = computed(() => {
  const data: any[] = [];
  props.rows.forEach((el) => {
    let existRow = data.find((elExist) => elExist.transactionId === el.transactionId);
    if (!existRow) {
      existRow = {
        actionType: el.actionType,
        transactionId: el.transactionId,
        version: el.version,
        subTable: []
      };
      data.push(existRow);
    }

    existRow.subTable.push({
      colTimeMillis: el.colTimeMillis,
      colType: el.colType
    });
  });
  return data;
});
</script>

// react-project/packages/processing-manager-react/src/components/versions/TransitionVersionsAggregated.tsx
/**
 * Transition Versions Aggregated Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionVersions/TransitionVersionsAggregated.vue
 */

import React, { useMemo } from 'react';
import { Card, Table } from 'antd';
import { Link, useParams } from 'react-router-dom';
import dayjs from 'dayjs';
import type { ColumnsType } from 'antd/es/table';

interface VersionRow {
  version: string;
  transactionId: string;
  actionType: string;
  colType: string;
  colTimeMillis: number;
}

interface AggregatedRow {
  version: string;
  transactionId: string;
  actionType: string;
  subTable: Array<{
    colType: string;
    colTimeMillis: number;
  }>;
}

interface TransitionVersionsAggregatedProps {
  rows: VersionRow[];
}

export const TransitionVersionsAggregated: React.FC<TransitionVersionsAggregatedProps> = ({
  rows = [],
}) => {
  const { name } = useParams<{ name: string }>();

  const tableData = useMemo(() => {
    const data: AggregatedRow[] = [];
    rows.forEach((el) => {
      let existRow = data.find((elExist) => elExist.transactionId === el.transactionId);
      if (!existRow) {
        existRow = {
          actionType: el.actionType,
          transactionId: el.transactionId,
          version: el.version,
          subTable: [],
        };
        data.push(existRow);
      }

      existRow.subTable.push({
        colTimeMillis: el.colTimeMillis,
        colType: el.colType,
      });
    });
    return data;
  }, [rows]);

  const expandedRowRender = (record: AggregatedRow) => {
    const columns: ColumnsType<any> = [
      {
        title: 'Column type',
        dataIndex: 'colType',
        key: 'colType',
      },
      {
        title: 'Column time',
        dataIndex: 'colTimeMillis',
        key: 'colTimeMillis',
        render: (colTimeMillis: number) => dayjs(colTimeMillis).format('YYYY-MM-DD HH:mm:ss'),
      },
    ];

    return <Table columns={columns} dataSource={record.subTable} pagination={false} rowKey="colType" />;
  };

  const columns: ColumnsType<AggregatedRow> = [
    {
      title: 'Version(time based)',
      dataIndex: 'version',
      key: 'version',
      width: 320,
    },
    {
      title: 'Transaction Id',
      dataIndex: 'transactionId',
      key: 'transactionId',
      render: (transactionId: string) => (
        <Link to={`/nodes/${name}/transaction/${transactionId}`}>{transactionId}</Link>
      ),
    },
    {
      title: 'Action Type',
      dataIndex: 'actionType',
      key: 'actionType',
    },
  ];

  return (
    <Card title="Aggregated by transaction view">
      <Table
        columns={columns}
        dataSource={tableData}
        expandable={{ expandedRowRender }}
        rowKey="transactionId"
      />
    </Card>
  );
};

export default TransitionVersionsAggregated;
