// .old_project /packages/processing-manager/src/components/PmTransitionVersions/TransitionVersionsSorted.vue
<template>
  <div class="card">
    <div class="card-header">Sorted by column's time view</div>
    <div class="card-body">
      <el-table :data="tableData" style="width: 100%">
        <el-table-column label="Version(time based)" width="320px" prop="version"/>
        <el-table-column label="Transaction Id" width="320px" prop="transactionId">
          <template v-slot:default="scope">
            <router-link
              :to="`/processing-ui/nodes/${route.params.name}/transaction/${scope.row.transactionId}`">
              {{ scope.row.transactionId }}
            </router-link>
          </template>
        </el-table-column>
        <el-table-column label="Action Type" prop="actionType"></el-table-column>
        <el-table-column prop="colType" label="Column type"/>
        <el-table-column prop="colTimeMillis" label="Column time">
          <template v-slot:default="scopeCol">
            {{ $filters.dateTime(scopeCol.row.colTimeMillis) }}
          </template>
        </el-table-column>
      </el-table>
    </div>
  </div>
</template>

<script setup lang="ts">
import {useRoute} from "vue-router";
import {computed} from "vue";

const route = useRoute();
const props = defineProps({rows: {default: () => []}});
const tableData = computed(() => {
  return props.rows;
});
</script>

<style scoped lang="scss">
.card-body ul {
  list-style: none;
  margin: 0;
  padding: 0;

  li.name {
    font-weight: bold;
    margin-top: 10px;
  }
}
</style>

// react-project/packages/processing-manager-react/src/components/versions/TransitionVersionsSorted.tsx
/**
 * Transition Versions Sorted Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionVersions/TransitionVersionsSorted.vue
 */

import React from 'react';
import { Card, Table } from 'antd';
import { Link, useParams } from 'react-router-dom';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';
import './TransitionVersionsSorted.scss';

interface VersionRow {
  version: string;
  transactionId: string;
  actionType: string;
  colType: string;
  colTimeMillis: number;
}

interface TransitionVersionsSortedProps {
  rows: VersionRow[];
}

export const TransitionVersionsSorted: React.FC<TransitionVersionsSortedProps> = ({
  rows = [],
}) => {
  const { name } = useParams<{ name: string }>();

  const columns: ColumnsType<VersionRow> = [
    {
      title: 'Version(time based)',
      dataIndex: 'version',
      key: 'version',
      width: 320,
    },
    {
      title: 'Transaction Id',
      dataIndex: 'transactionId',
      key: 'transactionId',
      width: 320,
      render: (transactionId: string) => (
        <Link to={`/nodes/${name}/transaction/${transactionId}`}>{transactionId}</Link>
      ),
    },
    {
      title: 'Action Type',
      dataIndex: 'actionType',
      key: 'actionType',
    },
    {
      title: 'Column type',
      dataIndex: 'colType',
      key: 'colType',
    },
    {
      title: 'Column time',
      dataIndex: 'colTimeMillis',
      key: 'colTimeMillis',
      render: (colTimeMillis: number) => dayjs(colTimeMillis).format('YYYY-MM-DD HH:mm:ss'),
    },
  ];

  return (
    <Card title="Sorted by column's time view" className="transition-versions-sorted">
      <Table
        columns={columns}
        dataSource={rows}
        rowKey={(row, index) => `${row.transactionId}-${index}`}
      />
    </Card>
  );
};

export default TransitionVersionsSorted;
