// .old_project /packages/tasks/src/views/tasks/index/TasksFilter.vue
<template>
  <div class="tasks-filters">
    <el-form label-position="top" class="demo-form-inline">
      <el-row :gutter="20">
        <el-col :span="8">
          <el-form-item label="By Status">
            <el-select clearable class="full-width" v-model="filter.status_id" placeholder="-- Select --">
              <el-option v-for="item in optionsStatus" :key="item.key" :label="item.value" :value="item.key"> </el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="8">
          <el-form-item label="By Assignee">
            <el-select clearable class="full-width" v-model="filter.assignee_id" placeholder="-- Select --">
              <el-option v-for="item in optionsAssignee" :key="item.name" :label="item.name" :value="item.name"> </el-option>
            </el-select>
          </el-form-item>
        </el-col>
        <el-col :span="8">
          <el-form-item label="By Priority">
            <el-select clearable class="full-width" v-model="filter.priority_id" placeholder="-- Select --">
              <el-option v-for="item in optionsPriority" :key="item.key" :label="item.value" :value="item.key"> </el-option>
            </el-select>
          </el-form-item>
        </el-col>
      </el-row>
    </el-form>
    <hr />
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";

import type { TaskFilterType } from "../types";
import HelperDictionary from "@cyoda/ui-lib/src/helpers/HelperDictionary";
import HelperStorage from "@cyoda/ui-lib/src/helpers/HelperStorage";

const helperStorage = new HelperStorage();

const defaultFilter: TaskFilterType = {
  status_id: undefined,
  assignee_id: undefined,
  priority_id: undefined,
};

const emit = defineEmits(["changeFilter"]);

let filter = ref(defaultFilter);

let optionsStatus = ref(HelperDictionary.statuses);

let optionsAssignee = ref(HelperDictionary.users);

let optionsPriority = ref(HelperDictionary.priorities);
filter.value = helperStorage.get("TasksFilter", defaultFilter);
applyFilter(filter.value);
function applyFilter(filter: TaskFilterType) {
  helperStorage.set("TasksFilter", filter);
  emit("changeFilter", filter);
}

watch(
  filter,
  (val: any) => {
    applyFilter(val);
  },
  { deep: true }
);
</script>

<style lang="scss">
.tasks-filters {
  .el-form-item__label {
    margin-bottom: 0;
    padding-bottom: 0;
    font-size: 14px;
  }
}
</style>

// packages/tasks-react/src/components/TasksFilter.tsx
/**
 * TasksFilter Component
 * Filter controls for tasks list
 * Migrated from: .old_project/packages/tasks/src/views/tasks/index/TasksFilter.vue
 */

import React, { useEffect, memo, useCallback, useMemo } from 'react';
import { Form, Select, Row, Col, Divider } from 'antd';
import { HelperStorage, HelperDictionary } from '@cyoda/ui-lib-react';
import type { TaskFilterType } from '../types';
import './TasksFilter.scss';

const { Option } = Select;

interface TasksFilterProps {
  onChangeFilter: (filter: TaskFilterType) => void;
}

const defaultFilter: TaskFilterType = {
  status_id: undefined,
  assignee_id: undefined,
  priority_id: undefined,
};

const helperStorage = new HelperStorage();

export const TasksFilter: React.FC<TasksFilterProps> = memo(({ onChangeFilter }) => {
  const [form] = Form.useForm();

  // Load saved filter from storage
  useEffect(() => {
    const savedFilter = helperStorage.get<TaskFilterType>('TasksFilter', defaultFilter);
    form.setFieldsValue(savedFilter);
    onChangeFilter(savedFilter);
  }, [form, onChangeFilter]);

  const handleValuesChange = useCallback((_: any, allValues: TaskFilterType) => {
    console.log('🔍 Filter values changed:', allValues);
    helperStorage.set('TasksFilter', allValues);
    onChangeFilter(allValues);
  }, [onChangeFilter]);

  // Memoize options to prevent re-creating on every render
  const optionsStatus = useMemo(() => HelperDictionary.statuses || [], []);
  const optionsAssignee = useMemo(() => HelperDictionary.users || [], []);
  const optionsPriority = useMemo(() => HelperDictionary.priorities || [], []);

  return (
    <div className="tasks-filters" role="search" aria-label="Filter tasks">
      <Form
        form={form}
        layout="vertical"
        onValuesChange={handleValuesChange}
        initialValues={defaultFilter}
        aria-label="Task filters form"
      >
        <Row gutter={20}>
          <Col span={8}>
            <Form.Item label="By Status" name="status_id">
              <Select
                placeholder="-- Select --"
                allowClear
                aria-label="Filter by status"
                aria-describedby="status-filter-description"
                classNames={{ popup: { root: 'tasks-filter-dropdown' } }}
                styles={{ popup: { root: { minWidth: '300px' } } }}
              >
                {optionsStatus.map((item: any) => (
                  <Option key={item.key} value={item.key}>
                    {item.value}
                  </Option>
                ))}
              </Select>
            </Form.Item>
            <span id="status-filter-description" className="sr-only">
              Filter tasks by their current status
            </span>
          </Col>
          <Col span={8}>
            <Form.Item label="By Assignee" name="assignee_id">
              <Select
                placeholder="-- Select --"
                allowClear
                aria-label="Filter by assignee"
                aria-describedby="assignee-filter-description"
                classNames={{ popup: { root: 'tasks-filter-dropdown' } }}
                styles={{ popup: { root: { minWidth: '300px' } } }}
              >
                {optionsAssignee.map((item: any) => (
                  <Option key={item.name} value={item.name}>
                    {item.name}
                  </Option>
                ))}
              </Select>
            </Form.Item>
            <span id="assignee-filter-description" className="sr-only">
              Filter tasks by assigned user
            </span>
          </Col>
          <Col span={8}>
            <Form.Item label="By Priority" name="priority_id">
              <Select
                placeholder="-- Select --"
                allowClear
                aria-label="Filter by priority"
                aria-describedby="priority-filter-description"
                classNames={{ popup: { root: 'tasks-filter-dropdown' } }}
                styles={{ popup: { root: { minWidth: '300px' } } }}
              >
                {optionsPriority.map((item: any) => (
                  <Option key={item.key} value={item.key}>
                    {item.value}
                  </Option>
                ))}
              </Select>
            </Form.Item>
            <span id="priority-filter-description" className="sr-only">
              Filter tasks by priority level
            </span>
          </Col>
        </Row>
      </Form>
      <Divider />
    </div>
  );
});
TasksFilter.displayName = 'TasksFilter';
