// packages/statemachine-react/src/components/FilterBuilder/FilterBuilderGroup.tsx
import React from 'react';
import { Button, Radio, Dropdown, Space, Modal } from 'antd';
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import FilterBuilderCondition from './FilterBuilderCondition';
import HelperFilter, { type GroupCondition, type Condition } from './HelperFilter';
import './FilterBuilder.scss';

interface FilterBuilderGroupProps {
  condition: GroupCondition;
  cols: Array<{ alias: string; type: string }>;
  level?: number;
  readOnly?: boolean;
  showErrors?: boolean;
  className?: string;
  onChange: (condition: GroupCondition) => void;
  onRemove?: () => void;
}

const FilterBuilderGroup: React.FC<FilterBuilderGroupProps> = ({
  condition,
  cols,
  level = 0,
  readOnly = false,
  showErrors = false,
  className = '',
  onChange,
  onRemove,
}) => {
  const handleOperatorChange = (e: any) => {
    onChange({
      ...condition,
      operator: e.target.value,
    });
  };

  const handleAddGroup = () => {
    const newConditions = [...condition.conditions, HelperFilter.getGroup()];
    onChange({
      ...condition,
      conditions: newConditions,
    });
  };

  const handleAddCondition = () => {
    const newCondition = HelperFilter.getCondition();
    const groupIndex = condition.conditions.findIndex((c) =>
      HelperFilter.isGroupCondition(c)
    );

    let newConditions;
    if (groupIndex !== -1) {
      newConditions = [...condition.conditions];
      newConditions.splice(groupIndex, 0, newCondition);
    } else {
      newConditions = [...condition.conditions, newCondition];
    }

    onChange({
      ...condition,
      conditions: newConditions,
    });
  };

  const handleRemoveCondition = (index: number) => {
    const newConditions = condition.conditions.filter((_, i) => i !== index);
    onChange({
      ...condition,
      conditions: newConditions,
    });
  };

  const handleConditionChange = (index: number, newCondition: Condition | GroupCondition) => {
    const newConditions = [...condition.conditions];
    newConditions[index] = newCondition;
    onChange({
      ...condition,
      conditions: newConditions,
    });
  };

  const handleRemoveGroup = () => {
    Modal.confirm({
      title: 'Confirm!',
      content: 'Do you really want to delete group?',
      onOk: () => {
        if (onRemove) {
          onRemove();
        }
      },
    });
  };

  const menuItems: MenuProps['items'] = [
    {
      key: 'group',
      label: 'Add new group',
      onClick: handleAddGroup,
    },
    {
      key: 'condition',
      label: 'Add new condition',
      onClick: handleAddCondition,
    },
  ];

  return (
    <div className={`builder-condition-group ${level === 0 ? 'first' : ''} ${className}`}>
      <div className="group-actions" style={{ marginBottom: '16px' }}>
        <Space>
          <Radio.Group
            value={condition.operator}
            onChange={handleOperatorChange}
            disabled={readOnly}
            buttonStyle="solid"
          >
            <Radio.Button value="AND">Match All</Radio.Button>
            <Radio.Button value="OR">Match Any</Radio.Button>
          </Radio.Group>

          {!readOnly && (
            <Dropdown menu={{ items: menuItems }} trigger={['click']}>
              <Button type="primary" shape="circle" icon={<PlusOutlined />} />
            </Dropdown>
          )}

          {level > 0 && !readOnly && (
            <Button
              type="primary"
              danger
              shape="circle"
              icon={<DeleteOutlined />}
              onClick={handleRemoveGroup}
            />
          )}
        </Space>
      </div>

      <div className="group-conditions">
        {condition.conditions.map((childCondition, index) => {
          const isLast = !condition.conditions[index + 1];
          const innerFieldsClass = `inner-fields ${isLast ? 'last' : ''}`;

          if (HelperFilter.isGroupCondition(childCondition)) {
            return (
              <FilterBuilderGroup
                key={`group-${level}-${index}`}
                condition={childCondition}
                cols={cols}
                level={level + 1}
                readOnly={readOnly}
                showErrors={showErrors}
                className={innerFieldsClass}
                onChange={(newCondition) => handleConditionChange(index, newCondition)}
                onRemove={() => handleRemoveCondition(index)}
              />
            );
          } else {
            return (
              <FilterBuilderCondition
                key={`condition-${level}-${index}`}
                condition={childCondition}
                cols={cols}
                readOnly={readOnly}
                showErrors={showErrors}
                className={innerFieldsClass}
                isLast={isLast}
                onChange={(newCondition) => handleConditionChange(index, newCondition)}
                onRemove={() => handleRemoveCondition(index)}
              />
            );
          }
        })}
      </div>
    </div>
  );
};

export default FilterBuilderGroup;

// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/FilterBuilder/FilterBuilderGroup.vue
<template>
  <div
    :key="cols"
    class="builder-condition-group"
    :class="{
      'wrap-actions': level > 0,
      first: level === 0
    }"
  >
    <div class="group-actions">
      <el-radio-group :disabled="readOnly" v-model="condition.operator">
        <el-radio-button v-for="groupConditionType in groupConditionTypes" :key="groupConditionType.key"
                         :label="groupConditionType.key">{{ groupConditionType.label }}
        </el-radio-button>
      </el-radio-group>

      <el-dropdown v-if="!readOnly" class="button-add" trigger="click">
        <el-button type="info" circle>
          <font-awesome-icon icon="plus"/>
        </el-button>
        <template #dropdown>
          <el-dropdown-menu>
            <el-dropdown-item @click.native="onNewGroup">Add new group</el-dropdown-item>
            <el-dropdown-item @click.native="onNewCondition">Add new condition</el-dropdown-item>
          </el-dropdown-menu>
        </template>
      </el-dropdown>
      <el-button class="button-delete" v-if="level > 0" @click="onRemoveGroup" type="danger" circle>
        <font-awesome-icon icon="trash"/>
      </el-button>
    </div>
    <component :level="level + 1" v-for="(childCondition, index) in condition.conditions" :readOnly="readOnly"
               :showErrors="showErrors" :builderId="builderId" :key="`${index}${level + 1}`"
               :class="{ 'inner-fields': true, last: !condition.conditions[index + 1] }"
               :is="getConditionComponent(index)" :condition="childCondition" :cols="cols"
               @remove="onRemove(index)"></component>
  </div>
</template>

<script setup lang="ts">
import {ElMessageBox} from "element-plus";
import {ref, watch} from "vue";

import HelperFilter from "./HelperFilter";
import FilterBuilderCondition from "./FilterBuilderCondition.vue";
import FilterBuilderGroup from "./FilterBuilderGroup.vue";

const props = defineProps({
  builderId: {default: ""},
  readOnly: {default: false},
  condition: {
    default: () => {
      return {};
    }
  },
  level: {
    default: 0
  },
  cols: {
    default: () => []
  },
  showErrors: {default: false}
});

let groupConditionTypes = ref([
  {
    "@bean": "com.cyoda.core.conditions.GroupCondition",
    key: "AND",
    label: "Match All"
  },
  {
    "@bean": "com.cyoda.core.conditions.GroupCondition",
    key: "OR",
    label: "Match Any"
  }
]);

function onNewGroup() {
  props.condition.conditions.push(HelperFilter.getGroup());
}

function onNewCondition() {
  let isExistGroupCondition = props.condition.conditions.findIndex((el) => {
    return el["@bean"].indexOf("GroupCondition") !== -1;
  });
  if (isExistGroupCondition !== -1) {
    props.condition.conditions.splice(isExistGroupCondition, 0, HelperFilter.getCondition());
  } else {
    props.condition.conditions.push(HelperFilter.getCondition());
  }
}

function onRemove(index: number) {
  props.condition.conditions.splice(index, 1);
}

const emit = defineEmits(["remove"]);

function onRemoveGroup(index: number) {
  ElMessageBox.confirm("Do you really want to delete group?", "Confirm!", {
    callback: async (action: string) => {
      if (action === "confirm") {
        emit("remove");
      }
    }
  });
}

function getConditionComponent(index: number) {
  if (isGroup(index)) {
    return FilterBuilderGroup;
  } else {
    return FilterBuilderCondition;
  }
}

function isGroup(index: number) {
  let condition = props.condition.conditions[index];
  if (condition) {
    if (condition["@bean"].indexOf("GroupCondition") !== -1) {
      return true;
    }
  }
  return false;
}

watch(() => props.cols, () => {
  const allFields = props.cols.map((el) => el.alias);
  props.condition.conditions = props.condition.conditions.filter((el, index) => {
    if (!isGroup(index)) {
      return allFields.includes(el.fieldName);
    }
    return true;
  });
});
</script>

<style lang="scss">
.builder-condition-group {
  position: relative;

  &:before {
    content: "";
    height: 40px;
    border-color: #e0e0e0;
    border-style: dotted;
    border-width: 0 0 2px 2px;
    left: 10px;
    position: absolute;
    width: 10px;
    top: -18px;
  }

  &:after {
    height: calc(100% - 17px);
    top: 17px;
    content: "";
    border-color: #e0e0e0;
    border-style: dotted;
    border-width: 0 0 0 2px;
    width: 10px;
    left: 10px;
    position: absolute;
  }

  &.first:before {
    display: none;
  }

  &.first:after {
    display: none;
  }

  .button-add {
    margin-left: 10px;
  }

  .button-delete {
    margin-left: 10px !important;
  }

  .wrap-actions,
  .inner-fields {
    padding-left: 20px;
  }

  .group-actions {
    margin-top: 20px;
    margin-bottom: 20px;

    /*&.first:before {*/
    /*  display: none;*/
    /*}*/
  }

  .builder-condition-group:last-child.wrap-actions.inner-fields:after {
    display: none;
  }

  .el-date-editor.el-input,
  .el-date-editor.el-input__inner {
    width: 100% !important;
  }

  .el-select {
    width: 100% !important;
  }

  .el-input-number {
    width: 100% !important;
  }
}
</style>
