// packages/cobi-react/src/components/DataMapper/FilterBuilder/FilterBuilderGroup.tsx
import React from 'react';
import { Button, Radio, Dropdown, Modal } from 'antd';
import { PlusOutlined, DeleteOutlined } from '@ant-design/icons';
import type { MenuProps } from 'antd';
import { FilterGroup, FilterCondition, ColumnInfo, GROUP_CONDITION_TYPES } from './types';
import { HelperFilter } from './helpers';
import FilterBuilderCondition from './FilterBuilderCondition';
import './FilterBuilderGroup.css';

interface FilterBuilderGroupProps {
  condition: FilterGroup;
  cols: ColumnInfo[];
  level?: number;
  showErrors?: boolean;
  readOnly?: boolean;
  onRemove?: () => void;
  onChange: () => void;
}

const FilterBuilderGroup: React.FC<FilterBuilderGroupProps> = ({
  condition,
  cols,
  level = 0,
  showErrors = false,
  readOnly = false,
  onRemove,
  onChange,
}) => {
  // Handle operator change
  const handleOperatorChange = (e: any) => {
    condition.operator = e.target.value;
    onChange();
  };

  // Add new group
  const handleNewGroup = () => {
    condition.conditions.push(HelperFilter.getGroup());
    onChange();
  };

  // Add new condition
  const handleNewCondition = () => {
    const isExistGroupCondition = condition.conditions.findIndex((el) =>
      HelperFilter.isGroup(el)
    );
    if (isExistGroupCondition !== -1) {
      condition.conditions.splice(isExistGroupCondition, 0, HelperFilter.getCondition());
    } else {
      condition.conditions.push(HelperFilter.getCondition());
    }
    onChange();
  };

  // Remove condition/group at index
  const handleRemoveCondition = (index: number) => {
    condition.conditions.splice(index, 1);
    onChange();
  };

  // Remove this group
  const handleRemoveGroup = () => {
    Modal.confirm({
      title: 'Confirm!',
      content: 'Do you really want to delete group?',
      onOk: onRemove,
    });
  };

  // Check if condition at index is a group
  const isGroup = (index: number): boolean => {
    const cond = condition.conditions[index];
    return cond ? HelperFilter.isGroup(cond) : false;
  };

  // Dropdown menu items
  const menuItems: MenuProps['items'] = [
    {
      key: 'group',
      label: 'Add new group',
      onClick: handleNewGroup,
    },
    {
      key: 'condition',
      label: 'Add new condition',
      onClick: handleNewCondition,
    },
  ];

  return (
    <div
      className={`builder-condition-group ${level > 0 ? 'wrap-actions' : ''} ${
        level === 0 ? 'first' : ''
      }`}
    >
      <div className="group-actions">
        <Radio.Group
          value={condition.operator}
          onChange={handleOperatorChange}
          disabled={readOnly}
          buttonStyle="solid"
        >
          {GROUP_CONDITION_TYPES.map((gct) => (
            <Radio.Button key={gct.key} value={gct.key}>
              {gct.label}
            </Radio.Button>
          ))}
        </Radio.Group>

        {!readOnly && (
          <Dropdown menu={{ items: menuItems }} trigger={['click']}>
            <Button
              type="primary"
              shape="circle"
              icon={<PlusOutlined />}
              className="button-add"
            />
          </Dropdown>
        )}

        {level > 0 && (
          <Button
            type="primary"
            danger
            shape="circle"
            icon={<DeleteOutlined />}
            onClick={handleRemoveGroup}
            className="button-delete"
          />
        )}
      </div>

      {condition.conditions.map((childCondition, index) => {
        const isLast = !condition.conditions[index + 1];
        const className = `inner-fields ${isLast ? 'last' : ''}`;

        if (isGroup(index)) {
          return (
            <div key={`${index}-${level + 1}`} className={className}>
              <FilterBuilderGroup
                condition={childCondition as FilterGroup}
                cols={cols}
                level={level + 1}
                showErrors={showErrors}
                readOnly={readOnly}
                onRemove={() => handleRemoveCondition(index)}
                onChange={onChange}
              />
            </div>
          );
        } else {
          return (
            <div key={`${index}-${level + 1}`} className={className}>
              <FilterBuilderCondition
                condition={childCondition as FilterCondition}
                cols={cols}
                showErrors={showErrors}
                readOnly={readOnly}
                isLast={isLast}
                onRemove={() => handleRemoveCondition(index)}
                onChange={onChange}
              />
            </div>
          );
        }
      })}
    </div>
  );
};

export default FilterBuilderGroup;

// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/FilterBuilder/FilterBuilderGroup.vue
<template>
  <div
    :key="cols"
    class="builder-condition-group"
    :class="{
      'wrap-actions': level > 0,
      first: level === 0
    }"
  >
    <div class="group-actions">
      <el-radio-group :disabled="readOnly" v-model="condition.operator">
        <el-radio-button v-for="groupConditionType in groupConditionTypes" :key="groupConditionType.key"
                         :label="groupConditionType.key">{{ groupConditionType.label }}
        </el-radio-button>
      </el-radio-group>

      <el-dropdown v-if="!readOnly" class="button-add" trigger="click">
        <el-button type="info" circle>
          <font-awesome-icon icon="plus"/>
        </el-button>
        <template #dropdown>
          <el-dropdown-menu>
            <el-dropdown-item @click.native="onNewGroup">Add new group</el-dropdown-item>
            <el-dropdown-item @click.native="onNewCondition">Add new condition</el-dropdown-item>
          </el-dropdown-menu>
        </template>
      </el-dropdown>
      <el-button class="button-delete" v-if="level > 0" @click="onRemoveGroup" type="danger" circle>
        <font-awesome-icon icon="trash"/>
      </el-button>
    </div>
    <component :level="level + 1" v-for="(childCondition, index) in condition.conditions" :readOnly="readOnly"
               :showErrors="showErrors" :builderId="builderId" :key="`${index}${level + 1}`"
               :class="{ 'inner-fields': true, last: !condition.conditions[index + 1] }"
               :is="getConditionComponent(index)" :condition="childCondition" :cols="cols"
               @remove="onRemove(index)"></component>
  </div>
</template>

<script setup lang="ts">
import {ElMessageBox} from "element-plus";
import {ref, watch} from "vue";

import HelperFilter from "./HelperFilter";
import FilterBuilderCondition from "./FilterBuilderCondition.vue";
import FilterBuilderGroup from "./FilterBuilderGroup.vue";

const props = defineProps({
  builderId: {default: ""},
  readOnly: {default: false},
  condition: {
    default: () => {
      return {};
    }
  },
  level: {
    default: 0
  },
  cols: {
    default: () => []
  },
  showErrors: {default: false}
});

let groupConditionTypes = ref([
  {
    "@bean": "com.cyoda.core.conditions.GroupCondition",
    key: "AND",
    label: "Match All"
  },
  {
    "@bean": "com.cyoda.core.conditions.GroupCondition",
    key: "OR",
    label: "Match Any"
  }
]);

function onNewGroup() {
  props.condition.conditions.push(HelperFilter.getGroup());
}

function onNewCondition() {
  let isExistGroupCondition = props.condition.conditions.findIndex((el) => {
    return el["@bean"].indexOf("GroupCondition") !== -1;
  });
  if (isExistGroupCondition !== -1) {
    props.condition.conditions.splice(isExistGroupCondition, 0, HelperFilter.getCondition());
  } else {
    props.condition.conditions.push(HelperFilter.getCondition());
  }
}

function onRemove(index: number) {
  props.condition.conditions.splice(index, 1);
}

const emit = defineEmits(["remove"]);

function onRemoveGroup(index: number) {
  ElMessageBox.confirm("Do you really want to delete group?", "Confirm!", {
    callback: async (action: string) => {
      if (action === "confirm") {
        emit("remove");
      }
    }
  });
}

function getConditionComponent(index: number) {
  if (isGroup(index)) {
    return FilterBuilderGroup;
  } else {
    return FilterBuilderCondition;
  }
}

function isGroup(index: number) {
  let condition = props.condition.conditions[index];
  if (condition) {
    if (condition["@bean"].indexOf("GroupCondition") !== -1) {
      return true;
    }
  }
  return false;
}

watch(() => props.cols, () => {
  const allFields = props.cols.map((el) => el.alias);
  props.condition.conditions = props.condition.conditions.filter((el, index) => {
    if (!isGroup(index)) {
      return allFields.includes(el.fieldName);
    }
    return true;
  });
});
</script>

<style lang="scss">
.builder-condition-group {
  position: relative;

  &:before {
    content: "";
    height: 40px;
    border-color: #e0e0e0;
    border-style: dotted;
    border-width: 0 0 2px 2px;
    left: 10px;
    position: absolute;
    width: 10px;
    top: -18px;
  }

  &:after {
    height: calc(100% - 17px);
    top: 17px;
    content: "";
    border-color: #e0e0e0;
    border-style: dotted;
    border-width: 0 0 0 2px;
    width: 10px;
    left: 10px;
    position: absolute;
  }

  &.first:before {
    display: none;
  }

  &.first:after {
    display: none;
  }

  .button-add {
    margin-left: 10px;
  }

  .button-delete {
    margin-left: 10px !important;
  }

  .wrap-actions,
  .inner-fields {
    padding-left: 20px;
  }

  .group-actions {
    margin-top: 20px;
    margin-bottom: 20px;

    /*&.first:before {*/
    /*  display: none;*/
    /*}*/
  }

  .builder-condition-group:last-child.wrap-actions.inner-fields:after {
    display: none;
  }

  .el-date-editor.el-input,
  .el-date-editor.el-input__inner {
    width: 100% !important;
  }

  .el-select {
    width: 100% !important;
  }

  .el-input-number {
    width: 100% !important;
  }
}
</style>
