// .old_project /packages/cyoda-ui-lib/src/components-library/templates/BaseLayout/BaseLayout.vue
<template>
  <div class="app-wrapper">
    <div class="app-content">
      <div>
        <header class="sticky">
          <slot name="header"></slot>
        </header>
        <main class="main">
          <slot name="main"></slot>
        </main>
        <footer>
          <slot name="footer"></slot>
        </footer>
      </div>
    </div>
    <div class="app-overlaping-components">
      <portal-target name="modal" />
      <slot name="portals"></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from "vue";

import _ from "lodash";

let resizeWindowThrottle = ref(_.throttle(resizeWindow));

let header=null;
let main=null;
onMounted(() => {
  header = document.querySelector("header.sticky");
  main = document.querySelector("main.main");
  window.addEventListener("resize", resizeWindowThrottle.value);
  resizeWindowThrottle.value();
});

onBeforeUnmount(() => {
  window.removeEventListener("resize", resizeWindowThrottle.value);
});

function resizeWindow() {
  if(!header || !main) return;
  const headerHeight = header.offsetHeight;
  main.setAttribute("style", `padding-top: ${headerHeight + 10}px`);
}
</script>

<style lang="scss">
body {
  position: relative;
}

.app-wrapper {
  position: static;
}
</style>

<style lang="scss" scoped>
.app-content {

  > * {
    min-height: 100%;
    display: flex;
    flex-direction: column;

    > * {
      flex: 0 1 auto;
    }

    .main {
      flex: 1 0 auto;
    }
  }
}

header {
  background: rgb(255, 255, 255);
  border-bottom: 2px solid #e8e8e8;

  &:not(:empty) {
    padding: 16px;
  }

  &.sticky {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 10;
  }
}

.sticky + .main {
  padding-top: 75px;
}

main {
  padding: 16px;
}

footer {
  &:not(:empty) {
    padding: 16px;
  }
}
</style>

// react-project/packages/ui-lib-react/src/components/BaseLayout/BaseLayout.tsx
import React, { useEffect, useRef, useCallback } from 'react'
import { throttle } from 'lodash'
import './BaseLayout.scss'

export interface BaseLayoutProps {
  header?: React.ReactNode
  main?: React.ReactNode
  footer?: React.ReactNode
  portals?: React.ReactNode
  className?: string
}

/**
 * BaseLayout Component
 * Main application layout with sticky header and responsive padding
 * 
 * Migrated from Vue: .old_project/packages/cyoda-ui-lib/src/components-library/templates/BaseLayout/BaseLayout.vue
 */
export const BaseLayout: React.FC<BaseLayoutProps> = ({
  header,
  main,
  footer,
  portals,
  className = ''
}) => {
  const headerRef = useRef<HTMLElement>(null)
  const mainRef = useRef<HTMLElement>(null)

  const resizeWindow = useCallback(() => {
    if (!headerRef.current || !mainRef.current) return
    
    const headerHeight = headerRef.current.offsetHeight
    mainRef.current.style.paddingTop = `${headerHeight + 10}px`
  }, [])

  useEffect(() => {
    // Create throttled resize handler
    const resizeWindowThrottle = throttle(resizeWindow, 100)

    // Initial resize
    resizeWindowThrottle()

    // Add event listener
    window.addEventListener('resize', resizeWindowThrottle)

    // Cleanup
    return () => {
      window.removeEventListener('resize', resizeWindowThrottle)
      resizeWindowThrottle.cancel()
    }
  }, [resizeWindow])

  return (
    <div className={`app-wrapper ${className}`}>
      <div className="app-content">
        <div>
          <header className="sticky" ref={headerRef}>
            {header}
          </header>
          <main className="main" ref={mainRef}>
            {main}
          </main>
          <footer>
            {footer}
          </footer>
        </div>
      </div>
      <div className="app-overlaping-components">
        {/* Portal target for modals - will be implemented with React Portal */}
        <div id="modal-portal-target" />
        {portals}
      </div>
    </div>
  )
}
