// .old_project /packages/cyoda-ui-lib/src/components-library/elements/ErrorHandler/ErrorHandler.vue
<template>
  <div>
    <ErrorHandlerNotification v-if="isShowErrorNotification" @open="onOpen"/>
    <ErrorHandlerTable ref="errorHandlerTableRef" @detailView="onDetailView" @export="onExport" @exportAll="onExportAll"
                       @clearErrors="onClearErrors"/>
    <ErrorHandlerDetailView @export="onExport" ref="errorHandlerDetailViewRef"/>
  </div>
</template>

<script setup lang="ts">
import {ElMessageBox, ElMessage, ElLink} from "element-plus";
import {useRoute, useRouter} from "vue-router";
import {ref, computed, watch, onMounted, getCurrentInstance, h, nextTick} from "vue";

import ErrorHandlerNotification from "./ErrorHandlerNotification.vue";
import ErrorHandlerTable from "./ErrorHandlerTable.vue";

import moment from "moment";
import ErrorHandlerDetailView from "./ErrorHandlerDetailView.vue";
import FileSaver from "file-saver";
import {VersionPlatform} from "../../../types/types";
import HelperContent from "@cyoda/cobi/src/helpers/HelperContent";
import _ from "lodash";
import useErrorHandlerStore from "../../../stores/error-handler";

const route = useRoute();
const router = useRouter();
const errorHandlerStore = useErrorHandlerStore();
const errors = computed(() => {
  return errorHandlerStore.errors;
});
const platformVersion = computed(() => {
  return platform.value.version || "-";
});
const isShowErrorNotification = computed(() => {
  return errors.value.length > 0;
});

function addError(value) {
  return errorHandlerStore.addError(value);
}

function clearErrors() {
  return errorHandlerStore.clearErrors();
}

const errorHandlerTableRef = ref(null);

const errorHandlerDetailViewRef = ref(null);

let platform = ref({});

let uiVersion = ref(import.meta.env.VITE_APP_UI_VERSION!);

let ignoreErrors = ref(["Request failed with status code", "canceled"]);

onMounted(async () => {
  if (import.meta.env.MODE === "production" || true) {
    const app = getCurrentInstance().appContext.app;
    app.config.errorHandler = (err: Error, vm: Vue, info: string) => {
      if (ignoreErrors.value.some((ignoreErr) => err.message.toLowerCase().includes(ignoreErr.toLowerCase()))) {
        console.error(err);
        return;
      }

      ElMessage.error({
        message: h("p", null, [
          h("span", null, "Page may be not work correctly. Please send error to developer. "),
          h(
            ElLink,
            {
              onClick: onOpen
            },
            "Open debug tool"
          )
        ])
      });

      addError({
        message: err.message,
        info,
        stack: err.stack,
        createdAt: moment().format("x"),
        pageUrl: window.location.href,
        uiVersion: uiVersion.value
      });

      console.error(err);
    };

    await router.isReady();
    if (route.query.error) {
      const test: any = null;
      test.filter((el) => el);
    }
  }
});

function onOpen() {
  errorHandlerTableRef.value.isVisible = true;
}

function onDetailView(error) {
  errorHandlerDetailViewRef.value.open(error);
}

async function onExport(error) {
  const data = prepareDataForExport(error);
  const message = error.message
    .toLowerCase()
    .replaceAll(" ", "_")
    .replaceAll(/[^a-zA-Z0-9]/g, "_")
    .replaceAll(/_+/g, "_")
    .replace(/_$/, "");
  const file = new File([HelperContent.prettyContent(JSON.stringify(data))], `file_${moment().format("YYYY-MM-DD HH:mm:ss")}_platform_v${platformVersion.value}_UI_v${uiVersion.value}_error_${message}.json`, {type: "text/plain;charset=utf-8"});
  FileSaver.saveAs(file);
}

async function onExportAll() {
  const groupedData = _.groupBy(errors.value, (el) => {
    return el.message;
  });

  const errorsKeys = Object.keys(groupedData)
    .map((el: any) => {
      return _.maxBy(groupedData[el], (elMax: any) => parseInt(elMax.createdAt, 10));
    })
    .reverse();

  const data = errorsKeys.map((error) => prepareDataForExport(error));
  const file = new File([HelperContent.prettyContent(JSON.stringify(data))], `file_${moment().format("YYYY-MM-DD HH:mm:ss")}_platform_v${platformVersion.value}_UI_v${uiVersion.value}_all_errors.json`, {type: "text/plain;charset=utf-8"});
  FileSaver.saveAs(file);
}

function prepareDataForExport(error) {
  const eventsCount = errors.value.filter((el) => el.message === error.message).length;
  return {
    eventsCount,
    ...error,
    createdAt: moment(parseInt(error.createdAt, 10))
  };
}

function onClearErrors() {
  ElMessageBox.confirm("Do you really want to delete All error on UI and close that window?", "Confirm!", {
    callback: async (action) => {
      if (action === "confirm") {
        errorHandlerTableRef.value.isVisible = false;
        clearErrors();
      }
    }
  });
}

watch(
  isShowErrorNotification,
  (value: boolean) => {
    if (value) {
      document.body.classList.add("error-handler");
    } else {
      document.body.classList.remove("error-handler");
    }
  },
  {immediate: true}
);
</script>

// packages/ui-lib-react/src/components/ErrorHandler/ErrorHandler.tsx
import React, { useState, useEffect, useMemo } from 'react'
import { message } from 'antd'
import moment from 'moment'
import FileSaver from 'file-saver'
import { ErrorNotification } from '../ErrorNotification'
import { ErrorTable } from '../ErrorTable'
import { ErrorDetailView } from '../ErrorDetailView'
import { useErrorHandler, ErrorData } from '../../contexts/ErrorHandlerContext'

export interface ErrorHandlerProps {
  /** UI version for error reports */
  uiVersion?: string
  /** Platform version for error reports */
  platformVersion?: string
  /** Error messages to ignore (won't be tracked) */
  ignoreErrors?: string[]
  /** Whether to enable global error handling */
  enableGlobalHandler?: boolean
}

/**
 * ErrorHandler Component
 * Main error handling component that provides error tracking, notification, and debugging tools
 * 
 * Migrated from Vue: .old_project/packages/cyoda-ui-lib/src/components-library/elements/ErrorHandler/ErrorHandler.vue
 */
export const ErrorHandler: React.FC<ErrorHandlerProps> = ({
  uiVersion = import.meta.env.VITE_APP_UI_VERSION || '-',
  platformVersion = '-',
  ignoreErrors = ['Request failed with status code', 'canceled'],
  enableGlobalHandler = true
}) => {
  const { errors, addError, clearErrors } = useErrorHandler()
  const [tableVisible, setTableVisible] = useState(false)
  const [detailVisible, setDetailVisible] = useState(false)
  const [selectedError, setSelectedError] = useState<ErrorData | null>(null)

  // Count of events for the selected error
  const eventsCount = useMemo(() => {
    if (!selectedError) return 0
    return errors.filter(e => e.message === selectedError.message).length
  }, [errors, selectedError])

  // Setup global error handler
  useEffect(() => {
    if (!enableGlobalHandler) return

    const handleError = (event: ErrorEvent) => {
      const error = event.error

      // Check if error should be ignored
      if (ignoreErrors.some(ignoreErr => 
        error?.message?.toLowerCase().includes(ignoreErr.toLowerCase())
      )) {
        console.error(error)
        return
      }

      // Show error message to user
      message.error({
        content: (
          <span>
            Page may not work correctly. Please send error to developer.{' '}
            <a onClick={() => setTableVisible(true)}>Open debug tool</a>
          </span>
        ),
        duration: 5
      })

      // Add error to store
      addError({
        message: error?.message || 'Unknown error',
        info: event.type,
        stack: error?.stack,
        createdAt: moment().format('x'),
        pageUrl: window.location.href,
        uiVersion
      })

      console.error(error)
    }

    window.addEventListener('error', handleError)
    return () => window.removeEventListener('error', handleError)
  }, [enableGlobalHandler, ignoreErrors, uiVersion, addError])

  const handleOpenTable = () => {
    setTableVisible(true)
  }

  const handleCloseTable = () => {
    setTableVisible(false)
  }

  const handleDetailView = (error: ErrorData) => {
    setSelectedError(error)
    setDetailVisible(true)
  }

  const handleCloseDetail = () => {
    setDetailVisible(false)
    setSelectedError(null)
  }

  const prepareDataForExport = (error: ErrorData) => {
    return {
      message: error.message,
      info: error.info,
      stack: error.stack,
      createdAt: error.createdAt,
      pageUrl: error.pageUrl,
      uiVersion: error.uiVersion,
      platformVersion
    }
  }

  const handleExport = (error: ErrorData) => {
    const data = prepareDataForExport(error)
    const sanitizedMessage = error.message
      .toLowerCase()
      .replaceAll(' ', '_')
      .replaceAll(/[^a-zA-Z0-9]/g, '_')
      .replaceAll(/_+/g, '_')
      .replace(/_$/, '')

    const fileName = `file_${moment().format('YYYY-MM-DD_HH-mm-ss')}_platform_v${platformVersion}_UI_v${uiVersion}_error_${sanitizedMessage}.json`
    const content = JSON.stringify(data, null, 2)
    const file = new File([content], fileName, { type: 'text/plain;charset=utf-8' })
    FileSaver.saveAs(file)
  }

  const handleExportAll = () => {
    const allData = errors.map(error => prepareDataForExport(error))
    const fileName = `all_errors_${moment().format('YYYY-MM-DD_HH-mm-ss')}_platform_v${platformVersion}_UI_v${uiVersion}.json`
    const content = JSON.stringify(allData, null, 2)
    const file = new File([content], fileName, { type: 'text/plain;charset=utf-8' })
    FileSaver.saveAs(file)
  }

  const handleClearErrors = () => {
    clearErrors()
    setTableVisible(false)
    message.success('All errors cleared')
  }

  return (
    <div className="error-handler">
      <ErrorNotification
        visible={errors.length > 0}
        onClick={handleOpenTable}
      />
      <ErrorTable
        errors={errors}
        visible={tableVisible}
        onClose={handleCloseTable}
        onDetailView={handleDetailView}
        onExport={handleExport}
        onExportAll={handleExportAll}
        onClearErrors={handleClearErrors}
      />
      <ErrorDetailView
        error={selectedError}
        visible={detailVisible}
        onClose={handleCloseDetail}
        onExport={handleExport}
        eventsCount={eventsCount}
      />
    </div>
  )
}
