// react-project/packages/processing-manager-react/src/components/transition-detail/EventsFilter.tsx
/**
 * Events Filter Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionDetail/Events/EventsFilter.vue
 */

import React, { useState, useEffect, forwardRef, useImperativeHandle } from 'react';
import { Card, Form, Select, Button, Row, Col } from 'antd';
import {
  useEntitiesListPossible,
  useTransactionEventStatusesList,
  useProcessingQueues,
} from '../../hooks';
import './EventsFilter.scss';

interface FilterValues {
  queue: string;
  status: string;
  entityClass: string;
  hasErrors: boolean;
  sort: string;
}

interface EventsFilterProps {
  isLoading?: boolean;
  onChange?: (values: FilterValues) => void;
}

export interface EventsFilterRef {
  form: FilterValues;
}

export const EventsFilter = forwardRef<EventsFilterRef, EventsFilterProps>(
  ({ isLoading = false, onChange }, ref) => {
    const [form, setForm] = useState<FilterValues>({
      queue: '',
      status: '',
      entityClass: '',
      hasErrors: false,
      sort: 'ASC',
    });

    const { data: entityClassesData } = useEntitiesListPossible();
    const { data: statusesData } = useTransactionEventStatusesList();
    const { data: queuesData } = useProcessingQueues();

    const entityClassOptions = entityClassesData?.map((el: string) => ({
      label: el,
      value: el,
    })) || [];

    const transactionStatusOptions = statusesData?.map((el: string) => ({
      label: el,
      value: el,
    })) || [];

    const queueOptions = queuesData || [];

    useImperativeHandle(ref, () => ({
      form,
    }));

    const handleSubmit = () => {
      onChange?.(form);
    };

    const handleFieldChange = (field: keyof FilterValues, value: any) => {
      setForm((prev) => ({ ...prev, [field]: value }));
    };

    return (
      <Card title="Filter">
        <Form layout="vertical" className="events-filter">
          <Row gutter={20} className="wrap-row">
            <Col span={12}>
              <Form.Item label="Queue">
                <Select
                  showSearch
                  allowClear
                  value={form.queue}
                  onChange={(value) => handleFieldChange('queue', value || '')}
                  options={queueOptions.map((q) => ({ value: q, label: q }))}
                />
              </Form.Item>
            </Col>
            <Col span={12}>
              <Form.Item label="Entity class">
                <Select
                  showSearch
                  allowClear
                  value={form.entityClass}
                  onChange={(value) => handleFieldChange('entityClass', value || '')}
                  options={entityClassOptions}
                />
              </Form.Item>
            </Col>
            <Col span={6}>
              <Form.Item label="Transaction Status">
                <Select
                  showSearch
                  allowClear
                  value={form.status}
                  onChange={(value) => handleFieldChange('status', value || '')}
                  options={transactionStatusOptions}
                />
              </Form.Item>
            </Col>
            <Col span={6}>
              <Form.Item label="Has error">
                <Select
                  value={form.hasErrors}
                  onChange={(value) => handleFieldChange('hasErrors', value)}
                  options={[
                    { label: 'True', value: true },
                    { label: 'False', value: false },
                  ]}
                  placeholder="Please select"
                />
              </Form.Item>
            </Col>
            <Col span={6}>
              <Form.Item label="Sort">
                <Select
                  value={form.sort}
                  onChange={(value) => handleFieldChange('sort', value)}
                  options={[
                    { label: 'Asc', value: 'ASC' },
                    { label: 'Desc', value: 'DESC' },
                  ]}
                  placeholder="Sort"
                />
              </Form.Item>
            </Col>
            <Col span={6} className="action-item">
              <Button type="primary" onClick={handleSubmit} loading={isLoading}>
                Load
              </Button>
            </Col>
          </Row>
        </Form>
      </Card>
    );
  }
);

EventsFilter.displayName = 'EventsFilter';

export default EventsFilter;

// .old_project /packages/processing-manager/src/components/PmTransitionDetail/Events/EventsFilter.vue
<template>
  <div class="card">
    <div class="card-header">Filter</div>
    <div class="card-body">
      <el-form class="events-filter" label-position="top">
        <el-row class="wrap-row" :gutter="20">
          <el-col :span="12">
            <el-form-item label="Queue">
              <el-select clearable filterable v-model="form.queue">
                <el-option v-for="queue in queueOptions" :key="queue" :label="queue" :value="queue"> </el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="Entity class">
              <el-select clearable filterable v-model="form.entityClass">
                <el-option v-for="entityClass in entityClassOptions" :key="entityClass.value" :label="entityClass.label" :value="entityClass.value"> </el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item label="Transaction Status">
              <el-select filterable clearable v-model="form.status">
                <el-option v-for="transactionStatus in transactionStatusData" :key="transactionStatus.label" :label="transactionStatus.label" :value="transactionStatus.value"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item label="Has error">
              <el-select v-model="form.hasErrors" placeholder="Please select">
                <el-option label="True" :value="true" />
                <el-option label="False" :value="false" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item label="Sort">
              <el-select v-model="form.sort" placeholder="Sort">
                <el-option label="Asc" value="ASC" />
                <el-option label="Desc" value="DESC" />
              </el-select>
            </el-form-item>
          </el-col>
          <el-col class="action-item" :span="6">
            <el-button @click="onSubmit" :loading="isLoading" type="primary">Load</el-button>
          </el-col>
        </el-row>
      </el-form>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";
import {useProcessingStore} from "../../../stores/processing";

interface DictionaryItem {
  label: string;
  value: string;
}

const emit = defineEmits(["change"]);
const props = defineProps({ isLoading: { default: false } });
const processingStore = useProcessingStore();
function entitiesListPossible() {
  return processingStore.entitiesListPossible();
}

function loadTransactionsStatuses() {
  return processingStore.loadTransactionsStatuses();
}

function processingQueues() {
  return processingStore.processingQueues();
}

function loadTransactionEventStatusesList() {
  return processingStore.loadTransactionEventStatusesList();
}

let actionTypeOptions = ref(["ALL", "READ", "UPDATE", "REMOVE"]);

let entityClassOptions = ref([]);

let transactionStatusData = ref([]);

let queueOptions = ref([]);
loadEntityClass();
loadStatuses();
loadProcessingQueues();

async function loadProcessingQueues() {
  const { data } = await processingQueues();
  queueOptions.value = data;
}

async function loadEntityClass() {
  const { data } = await entitiesListPossible();

  entityClassOptions.value = data.map((el: string) => ({
    label: el,
    value: el
  }));
}

async function loadStatuses(): Promise<void> {
  const { data } = await loadTransactionEventStatusesList();
  transactionStatusData.value = data.map((el: any) => ({
    label: el,
    value: el
  }));
}

let form = ref({
  queue: "",
  status: "",
  entityClass: "",
  hasErrors: false,
  sort: "ASC"
});

function onSubmit() {
  emit("change", form.value);
}

defineExpose({ form });
</script>

<style lang="scss">
.events-filter {
  .el-form-item__label {
    margin-bottom: 0 !important;
    padding-bottom: 0 !important;
  }

  .wrap-row {
    position: relative;

    .action-item {
      position: relative;
      left: 0;
      top: 22px;
    }
  }
}
</style>
