// packages/cobi-react/src/components/DataToClipboard/DataToClipboard.tsx
import React from 'react';
import { Button, message } from 'antd';
import { CopyOutlined } from '@ant-design/icons';
import './DataToClipboard.css';

interface DataToClipboardProps {
  value: string;
}

const DataToClipboard: React.FC<DataToClipboardProps> = ({ value }) => {
  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(value);
      message.success('Copied to clipboard!');
    } catch (err) {
      message.error('Failed to copy to clipboard');
    }
  };

  return (
    <span className="data-to-clipboard">
      <code>{value}</code>
      <Button
        type="link"
        size="small"
        icon={<CopyOutlined />}
        onClick={handleCopy}
        title="Copy to clipboard"
      />
    </span>
  );
};

export default DataToClipboard;

// .old_project /packages/cobi/src/components/DataToClipboard/DataToClipboard.vue
<template>
  <span class="data-to-clipboard">
    <span>
      {{ value }}
    </span>
    <span class="icon">
      <font-awesome-icon @click="onCopy" :icon="['fas', 'copy']" />
    </span>
  </span>
</template>

<script setup lang="ts">
import { ElNotification } from "element-plus";

const props = defineProps({
  value: {
    default: ""
  }
});

async function onCopy() {
  try {
    await navigator.clipboard.writeText(props.value);
    ElNotification({
      title: "Success",
      message: "Data was copied",
      type: "success"
    });
  } catch (e) {
    ElNotification({
      type: "error",
      title: "Error",
      message: "Sorry, data could not be copied"
    });
  }
}
</script>

<style lang="scss">
.data-to-clipboard {
  display: inline-flex;

  .icon {
    margin-left: 5px;

    svg {
      transition: all 0.5s;
      opacity: 0.5;
      cursor: pointer;
    }

    svg:hover {
      opacity: 1;
    }
  }
}
</style>
