// packages/processing-manager-react/src/components/network-info/NetworkInfoServer.tsx
/**
 * Network Info Server Component
 * Migrated from @cyoda/http-api/src/components/NetworkInfoServer/NetworkInfoServer.vue
 */

import React from 'react';
import { Spin } from 'antd';
import { useNetworkServerInfo } from '../../hooks/usePlatformCommon';
import './NetworkInfoServer.scss';

interface ServerInfo {
  type: string;
  id: string;
  nodeType: string;
  host: string;
  port: number;
  running: boolean;
  binded: boolean;
}

export const NetworkInfoServer: React.FC = () => {
  const { data: serverInfo, isLoading } = useNetworkServerInfo();

  if (isLoading) {
    return <Spin />;
  }

  const info = serverInfo as ServerInfo;

  return (
    <div className="network-info-server">
      <div>
        <h1 className="label">Server</h1>
        <div className="wrap-box">
          <div className="title">
            <span className="type-class">TYPE:</span>&nbsp;
            <span className="green">{info?.type || '-'}</span>
          </div>
          <div className="row-flex">
            <div>
              <strong>Id:</strong><br/>
              {info?.id || '-'}
            </div>
            <div>
              <strong>Node Type:</strong><br/>
              {info?.nodeType || '-'}
            </div>
            <div>
              <strong>Host:</strong><br/>
              {info?.host || '-'}
            </div>
            <div>
              <strong>Port:</strong><br/>
              {info?.port || '-'}
            </div>
            <div>
              <strong>Running:</strong><br/>
              {info?.running ? 'Yes' : 'No'}
            </div>
            <div>
              <strong>Binded:</strong><br/>
              {info?.binded ? 'Yes' : 'No'}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default NetworkInfoServer;

// .old_project /packages/http-api/src/components/NetworkInfoServer/NetworkInfoServer.vue
<template>
  <div class="network-info-server">
    <div>
      <h1 class="label">Server</h1>
      <div class="wrap-box">
        <div class="title">
          <span class="type-class">Type:</span>&nbsp;
          <span class="green">{{ serverInfo.type }}</span>
        </div>
        <div class="row-flex">
          <div>
            <strong>id:</strong><br/>
            {{ serverInfo.id || "-" }}
          </div>
          <div>
            <strong>Node Type:</strong><br/>
            {{ serverInfo.nodeType || "-" }}
          </div>
          <div>
            <strong>Host:</strong><br/>
            {{ serverInfo.host || "-" }}
          </div>
          <div>
            <strong>Port:</strong><br/>
            {{ serverInfo.port || "-" }}
          </div>
          <div>
            <strong>Running:</strong><br/>
            {{ $filters.boolean(serverInfo.running) }}
          </div>
          <div>
            <strong>Binded:</strong><br/>
            {{ $filters.boolean(serverInfo.binded) }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import {ref} from "vue";

import * as api from "@cyoda/ui-lib/src/api";

let serverInfo = ref({});
const props = defineProps({
  getNetInfoServerRequestFn: {
    default: null
  }
})

function getNetInfoServerRequest() {
  if (props.getNetInfoServerRequestFn) return props.getNetInfoServerRequestFn();
  return api.getNetInfoServer();
}

loadData();

async function loadData() {
  const {data} = await getNetInfoServerRequest();
  serverInfo.value = data;
}

defineExpose({getNetInfoServerRequest});
</script>

<style lang="scss">
.network-info-server {
  h1.label {
    font-size: 22px;
    margin-bottom: 10px;
    padding-left: 0;
  }

  .title {
    margin-bottom: 10px;
  }

  .row-flex {
    display: flex;
    justify-content: space-between;
  }

  .green {
    color: #148751;
    font-weight: bold;
  }

  .type-class {
    text-transform: uppercase;
    color: #595959;
    font-size: 14px;
    font-family: "Work Sans", sans-serif;
    font-weight: 500;
  }
}
</style>
