// react-project/packages/ui-lib-react/src/components/GraphicalStateMachinePanel/GraphicalStateMachinePanel.tsx
import React from 'react'
import { Button, Space } from 'antd'
import { EyeOutlined, EyeInvisibleOutlined } from '@ant-design/icons'
import './GraphicalStateMachinePanel.scss'

export interface GraphicalStateMachinePanelProps {
  showProcesses?: boolean
  showListOfTransitions?: boolean
  showCriteria?: boolean
  showTitles?: boolean
  showEdgesTitles?: boolean
  onToggleListOfTransitions?: () => void
  onToggleProcesses?: () => void
  onToggleCriteria?: () => void
  onToggleTitles?: () => void
  onToggleEdgesTitles?: () => void
  onResetPositions?: () => void
  className?: string
}

/**
 * GraphicalStateMachinePanel Component
 * Control panel for toggling visibility of state machine elements
 */
export const GraphicalStateMachinePanel: React.FC<GraphicalStateMachinePanelProps> = ({
  showProcesses = true,
  showListOfTransitions = true,
  showCriteria = true,
  showTitles = true,
  showEdgesTitles = false,
  onToggleListOfTransitions,
  onToggleProcesses,
  onToggleCriteria,
  onToggleTitles,
  onToggleEdgesTitles,
  onResetPositions,
  className = ''
}) => {
  return (
    <div className={`graphical-state-machine-panel ${className}`}>
      <Space wrap>
        <Button onClick={onToggleListOfTransitions}>
          {showListOfTransitions ? <EyeOutlined /> : <EyeInvisibleOutlined />}
          List of transitions
        </Button>
        <Button onClick={onToggleProcesses}>
          {showProcesses ? <EyeOutlined /> : <EyeInvisibleOutlined />}
          processes
        </Button>
        <Button onClick={onToggleCriteria}>
          {showCriteria ? <EyeOutlined /> : <EyeInvisibleOutlined />}
          criteria
        </Button>
        <Button onClick={onToggleTitles}>
          {showTitles ? <EyeOutlined /> : <EyeInvisibleOutlined />}
          states
        </Button>
        <Button onClick={onToggleEdgesTitles}>
          {showEdgesTitles ? <EyeOutlined /> : <EyeInvisibleOutlined />}
          transitions titles
        </Button>
        <Button onClick={onResetPositions} type="default" danger>
          Reset positions
        </Button>
      </Space>
    </div>
  )
}

// .old_project /packages/cyoda-ui-lib/src/components-library/patterns/GraphicalStatemachinePanel/GraphicalStatemachinePanel.vue
<template>
  <div>
    <el-button @click="emit('toggleListOfTransitions')">
      <font-awesome-icon :icon="showListOfTransitions?'eye':'eye-slash'"/>
      List of transitions
    </el-button>
    <el-button @click="emit('toggleProcesses')">
      <font-awesome-icon :icon="showProcesses?'eye':'eye-slash'"/>
      processes
    </el-button>
    <el-button @click="emit('toggleCriteria')">
      <font-awesome-icon :icon="showCriteria?'eye':'eye-slash'"/>
      criteria
    </el-button>
    <el-button @click="emit('toggleTitles')">
      <font-awesome-icon :icon="showTitles?'eye':'eye-slash'"/>
      states
    </el-button>
    <el-button @click="emit('toggleEdgesTitles')">
      <font-awesome-icon :icon="showEdgesTitles?'eye':'eye-slash'"/>
      transitions titles
    </el-button>
    <el-button @click="emit('resetPositions')" type="warning"> Reset positions</el-button>
  </div>
</template>

<script setup lang="ts">
const props = defineProps({
  showProcesses: {type: Boolean, default: true},
  showListOfTransitions: {type: Boolean, default: true},
  showCriteria: {type: Boolean, default: true},
  showTitles: {type: Boolean, default: true},
  showEdgesTitles: {type: Boolean, default: false}
});
const emit = defineEmits(['toggleListOfTransitions', 'toggleProcesses', 'toggleCriteria', 'toggleTitles', 'toggleEdgesTitles', 'resetPositions']);
</script>

<style lang="scss" scoped>
button {
  margin: 8px;
}
</style>
