// .old_project /packages/processing-manager/src/components/PmTransitionStateMachine/TransitionStateMachineTable.vue
<template>
  <div class="card">
    <div class="card-body">
      <data-tables :data="stateMachineEvents" style="width: 100%">
        <el-table-column label="State Machine Event Type" prop="event.type" />
        <el-table-column label="Transaction Id" width="320px" prop="event.transactionId">
          <template v-slot:default="scope">
            <router-link :to="`/processing-ui/nodes/${route.params.name}/transaction/${scope.row.event.transactionId}`">
              {{ scope.row.event.transactionId }}
            </router-link>
          </template>
        </el-table-column>
        <el-table-column label="Current State" prop="event.state" />
        <el-table-column label="Message" prop="message" />
      </data-tables>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRoute } from "vue-router";

const route=useRoute();
const props = defineProps({ stateMachineEvents: { default: () => [] } });
</script>

// react-project/packages/processing-manager-react/src/components/transition/TransitionStateMachineTable.tsx
/**
 * Transition State Machine Table Component
 * Displays state machine events
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionStateMachine/TransitionStateMachineTable.vue
 */

import React from 'react';
import { Card, Table } from 'antd';
import { Link, useParams } from 'react-router-dom';
import type { ColumnsType } from 'antd/es/table';

interface StateMachineEvent {
  event: {
    type: string;
    transactionId: string;
    state: string;
  };
  message: string;
}

interface TransitionStateMachineTableProps {
  stateMachineEvents: StateMachineEvent[];
}

export const TransitionStateMachineTable: React.FC<TransitionStateMachineTableProps> = ({
  stateMachineEvents = [],
}) => {
  const { name } = useParams<{ name: string }>();

  const columns: ColumnsType<StateMachineEvent> = [
    {
      title: 'State Machine Event Type',
      dataIndex: ['event', 'type'],
      key: 'type',
    },
    {
      title: 'Transaction Id',
      dataIndex: ['event', 'transactionId'],
      key: 'transactionId',
      width: 320,
      render: (transactionId: string) => (
        <Link to={`/nodes/${name}/transaction/${transactionId}`}>
          {transactionId}
        </Link>
      ),
    },
    {
      title: 'Current State',
      dataIndex: ['event', 'state'],
      key: 'state',
    },
    {
      title: 'Message',
      dataIndex: 'message',
      key: 'message',
    },
  ];

  return (
    <Card>
      <Table
        columns={columns}
        dataSource={stateMachineEvents}
        rowKey={(record) => record.event.transactionId}
        bordered
        pagination={{
          pageSizeOptions: ['5', '10', '15', '20', '50'],
          defaultPageSize: 10,
          showSizeChanger: true,
        }}
      />
    </Card>
  );
};

export default TransitionStateMachineTable;
