// .old_project /packages/statemachine/src/components/RangeCondition.vue
<template>
  <el-row>
    <el-col>
      <el-button :disabled="!form.entityClassName" @click="onOpenDialog" type="primary">
        Add New Range Column Definition
        <font-awesome-icon icon="plus"/>
      </el-button>

      <CyodaModellingPopUp @change="onChangeModellingPopUp" :onlyRange="true" :limit="1"
                           :checked="configDefinitionColRanges" ref="cyodaModellingPopUpRef"
                           :requestClass="form.entityClassName"/>
    </el-col>
    <el-col>
      <h2>Range Settings</h2>
      <el-form :inline="true">
        <el-form-item label="Range Order">
          <el-select v-model="form.rangeOrder" placeholder="Range Order" style="width: 100px">
            <el-option key="ASC" label="ASC" value="ASC"/>
            <el-option key="DESC" label="DESC" value="DESC"/>
          </el-select>
        </el-form-item>
      </el-form>
      <div class="filter-builder-condition" v-if="Object.keys(form.rangeCondition).length > 0">
        <FilterBuilderCondition :disableRemove="true" :conditionTypesKeysAvailable="conditionTypesKeysAvailable"
                                :condition="form.rangeCondition" builderId="RangeCondition"
                                :disableColumn="true" :cols="colsRange"/>
      </div>
    </el-col>
  </el-row>
</template>

<script setup lang="ts">
import FilterBuilderCondition
  from "@cyoda/ui-lib/src/components-library/patterns/FilterBuilder/FilterBuilderCondition.vue";
import CyodaModellingPopUp from "@cyoda/ui-lib/src/components-library/patterns/CyodaModelling/CyodaModellingPopUp.vue";
import HelperReportDefinition from "@cyoda/http-api/src/helpers/HelperReportDefinition";
import {computed, ref} from "vue";
import type {ColDef} from "@cyoda/ui-lib/src/types/types";
import HelperFilter from "@cyoda/ui-lib/src/components-library/patterns/FilterBuilder/HelperFilter";

const conditionTypesKeysAvailable = HelperReportDefinition.rangeConditionTypes;

const props = defineProps({
  form: {},
})

const cyodaModellingPopUpRef = ref(null);
const configDefinitionColRanges = ref([]);

const colsRange = computed(() => {
  return configDefinitionColRanges.value.map((el) => {
    return {
      colType: "colDef",
      alias: el.fullPath,
      typeShort: el.colType.split(".").pop() || "",
      type: el.colType,
      "@bean": "com.cyoda.core.reports.columns.ReportSimpleColumn"
    };
  });
});


function onOpenDialog() {
  cyodaModellingPopUpRef.value.dialogVisible = true;
}

function onChangeModellingPopUp(data: ColDef[]) {
  configDefinitionColRanges.value = data;
  if (data && data.length > 0) {
    props.form.rangeCondition.fieldName = data[0].fullPath;
  } else {
    props.form.rangeCondition = HelperFilter.getCondition();
  }
}
</script>

<style scoped lang="scss">
.builder-condition-row {
  &::after, &::before {
    display: none;
  }
}
</style>

// packages/statemachine-react/src/components/RangeCondition/RangeCondition.tsx
/**
 * Range Condition Component
 * Advanced filtering component for instances with range conditions
 * Migrated from: .old_project/packages/statemachine/src/components/RangeCondition.vue
 */

import React, { useState, useRef, useMemo, useCallback } from 'react';
import { Row, Col, Button, Form, Select, Alert } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import { ModellingPopUp } from '@cyoda/ui-lib-react';
import type { ModellingPopUpRef } from '@cyoda/ui-lib-react';
import { FilterBuilderCondition } from '@cyoda/cobi-react';
import type { FilterCondition, ColumnInfo } from '@cyoda/cobi-react';
import './RangeCondition.css';
import './RangeCondition.scss';

export interface RangeConditionForm {
  entityClassName: string;
  rangeOrder: 'ASC' | 'DESC';
  rangeCondition: FilterCondition;
}

interface RangeConditionProps {
  form: RangeConditionForm;
  onChange: (form: RangeConditionForm) => void;
  disabled?: boolean;
}

// Range condition types (from HelperReportDefinition.rangeConditionTypes)
// Range condition types that work with stream reports
// Based on HelperReportDefinition.rangeConditionTypes from the old Vue project
const RANGE_CONDITION_TYPES_KEYS = [
  'EQUALS',
  'LESS_THAN',
  'GREATER_THAN',
  'GREATER_OR_EQUAL',
  'BETWEEN',
  'NOT_EQUAL',
  'LESS_OR_EQUAL',
  'BETWEEN_INCLUSIVE',
];

export const RangeCondition: React.FC<RangeConditionProps> = ({
  form,
  onChange,
  disabled = false,
}) => {
  const modellingPopUpRef = useRef<ModellingPopUpRef>(null);
  const [configDefinitionColRanges, setConfigDefinitionColRanges] = useState<any[]>([]);

  // Initialize colsRange from existing condition
  React.useEffect(() => {
    if (form.rangeCondition?.fieldName && configDefinitionColRanges.length === 0) {
      // Extract type from the condition if available
      const colType = form.rangeCondition.value?.['@type'] || 'java.lang.String';
      setConfigDefinitionColRanges([{
        fullPath: form.rangeCondition.fieldName,
        colType: colType,
      }]);
    }
  }, [form.rangeCondition?.fieldName]);

  // Convert selected columns to ColumnInfo format for FilterBuilderCondition
  const colsRange = useMemo<ColumnInfo[]>(() => {
    return configDefinitionColRanges.map((el) => ({
      alias: el.fullPath,
      typeShort: el.colType?.split('.').pop() || 'String',
      type: el.colType || 'java.lang.String',
      label: el.fullPath,
    }));
  }, [configDefinitionColRanges]);

  const handleOpenDialog = () => {
    if (modellingPopUpRef.current) {
      modellingPopUpRef.current.open();
    }
  };

  const handleChangeModellingPopUp = useCallback((data: any[]) => {
    setConfigDefinitionColRanges(data);

    if (data && data.length > 0) {
      // Update the rangeCondition with the selected field
      const updatedForm = {
        ...form,
        rangeCondition: {
          ...form.rangeCondition,
          '@bean': 'com.cyoda.core.conditions.EqualsCondition',
          fieldName: data[0].fullPath,
        },
      };
      onChange(updatedForm);
    } else {
      // Clear the rangeCondition
      const updatedForm = {
        ...form,
        rangeCondition: {
          '@bean': '',
          fieldName: '',
          operation: '',
          value: {
            '@type': '',
            value: '',
          },
        },
      };
      onChange(updatedForm);
    }
  }, [form, onChange]);

  const handleRangeOrderChange = (value: 'ASC' | 'DESC') => {
    const updatedForm = {
      ...form,
      rangeOrder: value,
    };
    onChange(updatedForm);
  };

  const handleConditionChange = () => {
    // Trigger onChange to notify parent of condition changes
    onChange({ ...form });
  };

  const handleConditionRemove = () => {
    // Clear the condition
    setConfigDefinitionColRanges([]);
    const updatedForm = {
      ...form,
      rangeCondition: {
        '@bean': '',
        fieldName: '',
        operation: '',
        value: {
          '@type': '',
          value: '',
        },
      },
    };
    onChange(updatedForm);
  };

  const hasRangeCondition = form.rangeCondition && form.rangeCondition['@bean'];

  return (
    <div className="range-condition" data-testid="range-condition">
      <Row gutter={[16, 16]}>
        <Col span={24}>
          <Button
            type="primary"
            icon={<PlusOutlined />}
            onClick={handleOpenDialog}
            disabled={disabled || !form.entityClassName}
          >
            Add New Range Column Definition
          </Button>

          {!form.entityClassName && (
            <Alert
              message="Please select an entity class first"
              type="info"
              showIcon
              style={{ marginTop: 16 }}
            />
          )}

          <ModellingPopUp
            ref={modellingPopUpRef}
            requestClass={form.entityClassName}
            checked={configDefinitionColRanges}
            onChange={handleChangeModellingPopUp}
            onlyRange={true}
            limit={1}
          />
        </Col>

        <Col span={24}>
          <h3>Range Settings</h3>
          <Form layout="inline">
            <Form.Item label="Range Order">
              <Select
                value={form.rangeOrder}
                onChange={handleRangeOrderChange}
                style={{ width: 100 }}
                disabled={disabled}
                classNames={{ popup: { root: 'range-condition-dropdown' } }}
                styles={{ popup: { root: { minWidth: '150px' } } }}
              >
                <Select.Option value="ASC">ASC</Select.Option>
                <Select.Option value="DESC">DESC</Select.Option>
              </Select>
            </Form.Item>
          </Form>

          {hasRangeCondition && colsRange.length > 0 && (
            <div className="filter-builder-condition" style={{ marginTop: 16 }}>
              <FilterBuilderCondition
                condition={form.rangeCondition}
                cols={colsRange}
                showErrors={false}
                disableRemove={true}
                disableColumn={true}
                readOnly={disabled}
        conditionTypesKeysAvailable={RANGE_CONDITION_TYPES_KEYS}
                onRemove={handleConditionRemove}
                onChange={handleConditionChange}
              />
            </div>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default RangeCondition;
