// .old_project /packages/tasks/src/views/tasks/index/BulkUpdateForm.vue
<template>
  <div class="bulk-update-form">
    <el-form ref="formRef" :inline="true" :model="form">
      <el-form-item label="Priority">
        <el-select :disabled="isLoading" clearable v-model="form.priority" placeholder="-- Select --">
          <el-option v-for="item in optionsPriority" :key="item.key" :label="item.value" :value="item.key"> </el-option>
        </el-select>
      </el-form-item>
      <el-form-item label="Assigned To">
        <el-select :disabled="isLoading" clearable v-model="form.assignee" placeholder="-- Select --">
          <el-option v-for="item in optionsAssignee" :key="item.name" :label="item.name" :value="item.name"> </el-option>
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button :loading="isLoading" type="primary" @click="onSubmit">Submit</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>

<script setup lang="ts">
import { ElNotification, ElMessageBox } from "element-plus";
import { ref } from "vue";

import HelperDictionary from "@cyoda/ui-lib/src/helpers/HelperDictionary";
import {useTasksStore} from "../../../stores/tasks";

const props = defineProps({
  multipleSelection: {
    default: () => {
      return {};
    }
  }
});
const emit=defineEmits(['updated']);
const tasksStore = useTasksStore();
function updateTask(value) {
  return tasksStore.updateTask(value);
}

let form = ref({
  priority: "",
  assignee: ""
});

let optionsAssignee = ref(HelperDictionary.users);

let optionsPriority = ref(HelperDictionary.priorities);

const isLoading = ref<boolean>(false);

function onSubmit() {
  ElMessageBox.confirm("Do you really want to update task(s)?", "Confirm", {
    callback: async (action) => {
      if (action === "confirm") {
        isLoading.value = true;
        try {
          await Promise.all(
            props.multipleSelection.map((el) => {
              if (form.value.priority) {
                el.task.priority = form.value.priority;
              }
              if (form.value.assignee) {
                el.task.assignee = form.value.assignee;
              }
              return updateTask({
                transition: "AMEND",
                task: el.task
              });
            })
          );
          emit("updated");
          ElNotification({
            title: "Success",
            message: "Bulk updates is done!",
            type: "success"
          });
        } finally {
          isLoading.value = false;
        }
      }
    }
  });
}
</script>

<style lang="scss">
.bulk-update-form {
  margin-top: 15px;

  .el-form-item__content{
    width: 220px;
  }
}
</style>

// react-project/packages/tasks-react/src/components/BulkUpdateForm.tsx
/**
 * BulkUpdateForm Component
 * Form for bulk updating multiple tasks
 * Migrated from: .old_project/packages/tasks/src/views/tasks/index/BulkUpdateForm.vue
 */

import React, { useState } from 'react';
import { Form, Select, Button, Modal, message } from 'antd';
import { HelperDictionary } from '@cyoda/ui-lib-react';
import { useUpdateTask } from '../hooks/useTasks';
import type { TableRow } from '../types';

const { Option } = Select;

interface BulkUpdateFormProps {
  multipleSelection: TableRow[];
  onUpdated: () => void;
}

export const BulkUpdateForm: React.FC<BulkUpdateFormProps> = ({
  multipleSelection,
  onUpdated,
}) => {
  const [form] = Form.useForm();
  const [isLoading, setIsLoading] = useState(false);
  const updateTaskMutation = useUpdateTask();

  const optionsAssignee = HelperDictionary.users || [];
  const optionsPriority = HelperDictionary.priorities || [];

  const handleSubmit = () => {
    const values = form.getFieldsValue();

    // Check if at least one field is filled
    if (!values.priority && !values.assignee) {
      message.warning('Please select at least one field to update');
      return;
    }

    Modal.confirm({
      title: 'Confirm',
      content: `Do you really want to update ${multipleSelection.length} task(s)?`,
      onOk: async () => {
        setIsLoading(true);
        try {
          // Update all selected tasks
          await Promise.all(
            multipleSelection.map((row) => {
              const updatedTask = { ...row.task };

              // Apply updates
              if (values.priority) {
                updatedTask.priority = values.priority;
              }
              if (values.assignee) {
                updatedTask.assignee = values.assignee;
              }

              return updateTaskMutation.mutateAsync({
                transition: 'AMEND',
                task: updatedTask,
              });
            })
          );

          message.success('Bulk updates completed successfully!');
          form.resetFields();
          onUpdated();
        } catch (error) {
          message.error('Failed to update tasks');
          console.error('Bulk update error:', error);
        } finally {
          setIsLoading(false);
        }
      },
    });
  };

  return (
    <div className="bulk-update-form" style={{ marginTop: 15 }}>
      <Form form={form} layout="inline">
        <Form.Item label="Priority" name="priority">
          <Select
            placeholder="-- Select --"
            allowClear
            disabled={isLoading}
            style={{ width: 220 }}
          >
            {optionsPriority.map((item: any) => (
              <Option key={item.key} value={item.key}>
                {item.value}
              </Option>
            ))}
          </Select>
        </Form.Item>

        <Form.Item label="Assigned To" name="assignee">
          <Select
            placeholder="-- Select --"
            allowClear
            disabled={isLoading}
            style={{ width: 220 }}
          >
            {optionsAssignee.map((item: any) => (
              <Option key={item.name} value={item.name}>
                {item.name}
              </Option>
            ))}
          </Select>
        </Form.Item>

        <Form.Item>
          <Button type="primary" onClick={handleSubmit} loading={isLoading}>
            Submit
          </Button>
        </Form.Item>
      </Form>
    </div>
  );
};
