// .old_project /packages/tasks/src/views/tasks/index/TasksGrid.vue
<template>
  <div class="tasks-grid">
    <div>
      <h2>Tasks</h2>
    </div>
    <div class="wrap-table">
      <el-table ref="multipleTableRef" v-loading="loading" :data="tableData"
                :pagination-props="{ pageSizes: [5, 10, 15, 20, 25] }" @selection-change="handleSelectionChange"
                style="width: 100%">
        <el-table-column type="selection" width="55"></el-table-column>
        <el-table-column sortable prop="title" label="Title" width="180"></el-table-column>
        <el-table-column sortable prop="state" label="Status" width="180"></el-table-column>
        <el-table-column sortable sort-by="priority_id" prop="priority_name" label="Priority" width="180">
          <template v-slot:default="scope">
            {{ scope.row.priority_name }}
            <font-awesome-icon :style="{ color: priorityArrowColor(scope.row.priority) }"
                               :icon="priorityArrow(scope.row.priority)"/>
          </template>
        </el-table-column>
        <el-table-column sortable sort-by="assigned_to_id" prop="assigned_to_name"
                         label="Assigned To"></el-table-column>
        <el-table-column sortable sort-by="timestamp" prop="timestamp_name" label="Created"></el-table-column>
        <el-table-column label="Operations">
          <template v-slot:default="scope">
            <el-tooltip class="item" effect="dark" content="Edit" placement="top">
              <el-button @click="onView(scope.row)" size="default" type="warning" rel="tooltip" data-original-title=""
                         title="">
                <font-awesome-icon icon="pencil-alt"/>
              </el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <BulkUpdateForm v-if="multipleSelection.length > 0" @updated="onUpdatedBulk"
                      :multipleSelection="multipleSelection"/>

      <el-pagination @size-change="onSizeChange" @current-change="onCurrentChange" class="wrap-pagination"
                     :page-size="currentPageSize" :current-page="currentPage" :pager-count="5" :page-sizes="[5, 10, 20]"
                     layout="prev, pager, next, sizes, total" :total="totalRows"></el-pagination>
    </div>
    <TasksNotifications/>
  </div>
</template>

<script setup lang="ts">
import {useRouter} from "vue-router";
import {ref, computed, watch, onBeforeUnmount} from "vue";


import type {TableRow, Task, TasksRequestParams} from "../types";
import BulkUpdateForm from "./BulkUpdateForm.vue";
import {ElTable} from "element-plus";
import HelperDictionary from "@cyoda/ui-lib/src/helpers/HelperDictionary";
import HelperFormat from "@cyoda/ui-lib/src/helpers/HelperFormat";
import HelperConstants from "@cyoda/ui-lib/src/helpers/HelperConstants";
import eventBus from "@cyoda/ui-lib/src/plugins/eventBus";
import {useTasksStore} from "../../../stores/tasks";

const props = defineProps({
  filter: {
    default: () => ({})
  },
  isApplyRealData: {
    default: false
  }
});
const tasksStore = useTasksStore();
const router = useRouter();
const tableData = computed(() => {
  return tasks.value.map(
    (el: Task): TableRow => ({
      title: el.title,
      id: el.id,
      state: HelperFormat.toLowerCase(el.state),
      priority: el.priority,
      priority_name: HelperDictionary.getLabel("priorities", el.priority),
      assigned_to_name: el.assignee,

      timestamp: 0,
      timestamp_name: HelperFormat.date(el.createdDatetime),
      agent_event: el.message,
      task: el
    })
  );
})

const multipleTableRef = ref(null);


function loadTasksPerPage(params: TasksRequestParams) {
  return tasksStore.getTasksPerPage(params);
}

const loading = ref<boolean>(false);

let tasks = ref([]);

const totalRows = ref(0);

const currentPageSize = ref(5);

const currentPage = ref(0);

let multipleSelection = ref([]);
loadTasks();
eventBus.$on(HelperConstants.NEWTASKS, addTask);

onBeforeUnmount(() => {
  eventBus.$off(HelperConstants.NEWTASKS, addTask);
});

function addTask({alertTask: data}: any) {
  if (props.isApplyRealData) {
    if (props.filter.status_id !== "" && props.filter.status_id !== data.state) {
      data = false;
    }
    if (props.filter.assignee_id !== "" && props.filter.assignee_id !== data.assignee) {
      data = false;
    }

    if (props.filter.priority_id !== "" && props.filter.priority_id !== data.priority) {
      data = false;
    }

    if (data) {
      const task = tasks.value.find((el) => el.id === data.id);
      if (task) {
        const index = tasks.value.indexOf(task);
        if (index !== -1) {
          tasks.value[index] = data

        }
      } else {
        tasks.value.unshift(data);
        if (tasks.value.length > currentPageSize.value) {
          tasks.value.pop();
        }
        totalRows.value += 1;
      }
    }
  }
}

async function loadTasks() {
  try {
    let page = currentPage.value - 1;
    if (page < 0) {
      page = 0;
    }
    loading.value = true;
    const data = await loadTasksPerPage({
      page,
      size: currentPageSize.value,
      state: props.filter.status_id,
      assignee: props.filter.assignee_id,
      priority: props.filter.priority_id
    });

    tasks.value = [];
    totalRows.value = 0;

    if (data.length > 0) {
      tasks.value = data.map((el) => el.task);
      totalRows.value = data[0].taskCount;
    }
  } finally {
    loading.value = false;
  }
}


function priorityArrow(priorityId: number) {
  if (priorityId === 2 || priorityId === 1) {
    return "arrow-down";
  }
  return "arrow-up";
}

function priorityArrowColor(priorityId: number) {
  if (priorityId === 0) {
    return "#dd4b39";
  }
  if (priorityId === 1) {
    return "#ef8157";
  }
  if (priorityId === 2) {
    return "#6bd098";
  }
  return "#ef8157";
}

function onSizeChange(val: number) {
  currentPageSize.value = val;
  onCurrentChange(1);
}

function onCurrentChange(val: number) {
  currentPage.value = val;
}

function onView(row: TableRow) {
  router.push(`/tasks/${row.id}`);
}

function onUpdatedBulk() {
  multipleTableRef.value.clearSelection();
  multipleSelection.value = [];
  loadTasks();
}

function handleSelectionChange(val) {
  multipleSelection.value = val;
}


watch(currentPageSize, () => {

  loadTasks();
});


watch(currentPage, () => {

  loadTasks();
});


watch(() => props.filter, () => {

  loadTasks();
}, {deep: true});
</script>

<style scoped>
.wrap-table {
  margin-bottom: 20px;
}

.wrap-pagination {
  justify-content: center;
  margin-top: 20px;
}

h2 {
  margin-bottom: 10px;
}
</style>
<style lang="scss">
.circle-status {
  width: 20px;
  height: 20px;
  border-radius: 20px;
}

.tasks-grid {
  .el-table-column--selection .cell {
    padding-left: 10px !important;
  }
}
</style>

// react-project/packages/tasks-react/src/components/TasksGrid.tsx
/**
 * TasksGrid Component
 * Main tasks table with pagination
 * Migrated from: .old_project/packages/tasks/src/views/tasks/index/TasksGrid.vue
 */

import React, { useState, useEffect, useMemo } from 'react';
import { Table, Button, Tooltip, Pagination } from 'antd';
import { EditOutlined, ArrowUpOutlined, ArrowDownOutlined } from '@ant-design/icons';
import { useNavigate } from 'react-router-dom';
import { HelperDictionary, HelperFormat } from '@cyoda/ui-lib-react';
import { useTasksPerPage, useTasksState } from '../hooks/useTasks';
import { BulkUpdateForm } from './BulkUpdateForm';
import type { Task, TaskFilterType, TableRow } from '../types';
import type { ColumnsType } from 'antd/es/table';

interface TasksGridProps {
  filter: TaskFilterType;
  isApplyRealData: boolean;
}

export const TasksGrid: React.FC<TasksGridProps> = ({ filter, isApplyRealData }) => {
  const navigate = useNavigate();
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(5);
  const [selectedRowKeys, setSelectedRowKeys] = useState<React.Key[]>([]);

  // Build query params
  const params = useMemo(() => ({
    page: currentPage - 1,
    size: pageSize,
    state: filter.status_id || '',
    assignee: filter.assignee_id || '',
    priority: filter.priority_id || '',
  }), [currentPage, pageSize, filter]);

  // Fetch tasks
  const { data, isLoading, refetch } = useTasksPerPage(params);

  // Transform tasks to table rows
  const tableData: TableRow[] = useMemo(() => {
    if (!data?.content) return [];
    
    return data.content.map((task: Task): TableRow => ({
      id: task.id,
      title: task.title,
      state: HelperFormat.toLowerCase(task.state),
      priority: task.priority,
      priority_name: HelperDictionary.getLabel('priorities', task.priority),
      assigned_to_name: task.assignee,
      timestamp: 0,
      timestamp_name: HelperFormat.date(task.createdDatetime),
      agent_event: task.message,
      task,
    }));
  }, [data]);

  // Priority arrow icon
  const priorityArrow = (priority: number) => {
    return priority > 5 ? <ArrowUpOutlined /> : <ArrowDownOutlined />;
  };

  // Priority arrow color
  const priorityArrowColor = (priority: number) => {
    return priority > 5 ? 'red' : 'green';
  };

  // Handle view task
  const handleView = (row: TableRow) => {
    navigate(`/tasks/${row.id}`);
  };

  // Handle selection change
  const handleSelectionChange = (selectedKeys: React.Key[]) => {
    setSelectedRowKeys(selectedKeys);
  };

  // Handle page change
  const handlePageChange = (page: number, size: number) => {
    setCurrentPage(page);
    setPageSize(size);
  };

  // Table columns
  const columns: ColumnsType<TableRow> = [
    {
      title: 'Title',
      dataIndex: 'title',
      key: 'title',
      width: 180,
      sorter: (a, b) => a.title.localeCompare(b.title),
    },
    {
      title: 'Status',
      dataIndex: 'state',
      key: 'state',
      width: 180,
      sorter: (a, b) => a.state.localeCompare(b.state),
    },
    {
      title: 'Priority',
      dataIndex: 'priority_name',
      key: 'priority_name',
      width: 180,
      sorter: (a, b) => a.priority - b.priority,
      render: (text, record) => (
        <span>
          {text}{' '}
          <span style={{ color: priorityArrowColor(record.priority) }}>
            {priorityArrow(record.priority)}
          </span>
        </span>
      ),
    },
    {
      title: 'Assigned To',
      dataIndex: 'assigned_to_name',
      key: 'assigned_to_name',
      sorter: (a, b) => a.assigned_to_name.localeCompare(b.assigned_to_name),
    },
    {
      title: 'Created',
      dataIndex: 'timestamp_name',
      key: 'timestamp_name',
      sorter: (a, b) => a.timestamp - b.timestamp,
    },
    {
      title: 'Operations',
      key: 'operations',
      render: (_, record) => (
        <Tooltip title="Edit">
          <Button
            type="default"
            icon={<EditOutlined />}
            onClick={() => handleView(record)}
          />
        </Tooltip>
      ),
    },
  ];

  // Row selection config
  const rowSelection = {
    selectedRowKeys,
    onChange: handleSelectionChange,
  };

  return (
    <div className="tasks-grid">
      <div>
        <h2>Tasks</h2>
      </div>
      <div className="wrap-table">
        <Table
          rowSelection={rowSelection}
          columns={columns}
          dataSource={tableData}
          loading={isLoading}
          rowKey="id"
          pagination={false}
        />

        {selectedRowKeys.length > 0 && (
          <BulkUpdateForm
            multipleSelection={tableData.filter(row => selectedRowKeys.includes(row.id))}
            onUpdated={() => {
              setSelectedRowKeys([]);
              refetch();
            }}
          />
        )}

        <Pagination
          current={currentPage}
          pageSize={pageSize}
          total={data?.totalElements || 0}
          showSizeChanger
          showTotal={(total) => `Total ${total} items`}
          pageSizeOptions={[5, 10, 20]}
          onChange={handlePageChange}
          style={{ marginTop: 16, textAlign: 'right' }}
        />
      </div>
    </div>
  );
};
