// react-project/packages/cobi-react/src/pages/DataSourceConfig/components/BlobStorageParameters/BlobStorageParameters.tsx
import React, { useState, useRef, useMemo } from 'react';
import { Table, Button, Modal } from 'antd';
import { PlusOutlined, EditOutlined, DeleteOutlined, MenuOutlined } from '@ant-design/icons';
import { DndContext, closestCenter, KeyboardSensor, PointerSensor, useSensor, useSensors } from '@dnd-kit/core';
import { arrayMove, SortableContext, sortableKeyboardCoordinates, verticalListSortingStrategy } from '@dnd-kit/sortable';
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import DialogEndpointParametersBlobStorage, {
  DialogEndpointParametersBlobStorageRef,
} from '../DialogEndpointParameters/DialogEndpointParametersBlobStorage';
import './BlobStorageParameters.css';

interface BlobStorageParameter {
  name: string;
  required: boolean;
  defaultValue: string;
  secure?: boolean;
  template?: boolean;
  templateValue?: string;
}

interface BlobStorageParametersProps {
  parameters: BlobStorageParameter[];
  onChange?: (parameters: BlobStorageParameter[]) => void;
}

const DraggableRow = ({ children, ...props }: any) => {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: props['data-row-key'],
  });

  const style = {
    ...props.style,
    transform: CSS.Transform.toString(transform),
    transition,
    cursor: 'move',
    ...(isDragging ? { position: 'relative', zIndex: 9999 } : {}),
  };

  return (
    <tr {...props} ref={setNodeRef} style={style} {...attributes} {...listeners}>
      {children}
    </tr>
  );
};

const BlobStorageParameters: React.FC<BlobStorageParametersProps> = ({ parameters, onChange }) => {
  const dialogRef = useRef<DialogEndpointParametersBlobStorageRef>(null);

  const sensors = useSensors(
    useSensor(PointerSensor),
    useSensor(KeyboardSensor, {
      coordinateGetter: sortableKeyboardCoordinates,
    })
  );

  const isExistTemplatesColumn = useMemo(() => {
    return parameters.some((el) => el.template && el.templateValue);
  }, [parameters]);

  const addNewParameter = () => {
    dialogRef.current?.openDialogAndCreateNew();
  };

  const onEditParameter = (row: BlobStorageParameter) => {
    dialogRef.current?.openDialogAndEditRecord(row);
  };

  const onDeleteParameter = (row: BlobStorageParameter) => {
    Modal.confirm({
      title: 'Confirm!',
      content: 'Do you really want to remove parameter?',
      onOk: () => {
        const index = parameters.indexOf(row);
        if (index !== -1 && onChange) {
          const newParams = [...parameters];
          newParams.splice(index, 1);
          onChange(newParams);
        }
      },
    });
  };

  const handleDragEnd = (event: any) => {
    const { active, over } = event;

    if (active.id !== over.id && onChange) {
      const oldIndex = parameters.findIndex((item, index) => index === active.id);
      const newIndex = parameters.findIndex((item, index) => index === over.id);
      onChange(arrayMove(parameters, oldIndex, newIndex));
    }
  };

  const columns = [
    ...(parameters.length > 1
      ? [
          {
            title: '',
            key: 'drag',
            width: 50,
            align: 'center' as const,
            render: () => <MenuOutlined className="handle" />,
          },
        ]
      : []),
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
    },
    {
      title: 'Required',
      dataIndex: 'required',
      key: 'required',
      render: (required: boolean) => (required ? 'Yes' : 'No'),
    },
    {
      title: 'Default Value',
      dataIndex: 'defaultValue',
      key: 'defaultValue',
    },
    ...(isExistTemplatesColumn
      ? [
          {
            title: 'Template Value',
            dataIndex: 'templateValue',
            key: 'templateValue',
          },
        ]
      : []),
    {
      title: 'Actions',
      key: 'actions',
      render: (_: any, row: BlobStorageParameter) => (
        <>
          <Button
            type="primary"
            icon={<EditOutlined />}
            onClick={() => onEditParameter(row)}
            size="small"
            style={{ marginRight: 8 }}
          />
          <Button danger icon={<DeleteOutlined />} onClick={() => onDeleteParameter(row)} size="small" />
        </>
      ),
    },
  ];

  const dataWithKeys = parameters.map((item, index) => ({
    ...item,
    key: index,
  }));

  return (
    <div className="blob-storage-parameters">
      <div className="endpoint-actions">
        <Button type="primary" icon={<PlusOutlined />} onClick={addNewParameter}>
          Add New Parameter
        </Button>
      </div>

      <DndContext sensors={sensors} collisionDetection={closestCenter} onDragEnd={handleDragEnd}>
        <SortableContext items={dataWithKeys.map((_, index) => index)} strategy={verticalListSortingStrategy}>
          <Table
            columns={columns}
            dataSource={dataWithKeys}
            pagination={false}
            components={{
              body: {
                row: DraggableRow,
              },
            }}
          />
        </SortableContext>
      </DndContext>

      <DialogEndpointParametersBlobStorage ref={dialogRef} parameters={parameters} onChange={onChange} />
    </div>
  );
};

export default BlobStorageParameters;

// .old_project /packages/cobi/src/components/DataSourceConfig/BlobStorageParameters/BlobStorageParameters.vue
<template>
  <div class="http-parameters">
    <div class="endpoint-actions">
      <el-button @click="addNewParameter" type="primary">
        Add New Parameter
        <font-awesome-icon icon="plus"/>
      </el-button>
    </div>

    <CyodaDataTablesDraggable :animate="300" handle=".handle">
      <el-table :data="parameters" stripe style="width: 100%">
        <el-table-column v-if="parameters.length > 1" label="" align="center" width="50">
          <template>
            <font-awesome-icon class="handle" icon="align-justify"/>
          </template>
        </el-table-column>
        <el-table-column prop="name" label="Name"></el-table-column>
        <el-table-column prop="required" label="Required">
          <template v-slot:default="{ row }">
            {{ row.required ? "Yes" : "No" }}
          </template>
        </el-table-column>
        <el-table-column prop="defaultValue" label="Default Value"></el-table-column>
        <el-table-column v-if="isExistTemplatesColumn" prop="templateValue" label="Template Value"></el-table-column>
        <el-table-column label="Actions">
          <template v-slot="{ row }">
            <el-button @click="onEditParameter(row)" size="default" type="primary">
              <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
            </el-button>
            <el-button @click="onDeleteParameter(row)" size="default" type="danger">
              <font-awesome-icon icon="trash"></font-awesome-icon>
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </CyodaDataTablesDraggable>

    <DialogEndpointParametersBlobStorage ref="dialogEndpointParametersBlobStorageRef" :parameters="parameters"/>
  </div>
</template>

<script setup lang="ts">
import {ref, computed} from "vue";

import type {BlobStorageParameterDto} from "../DataSourceConfig";
import DialogEndpointParametersBlobStorage
  from "../../../components/DataSourceConfig/DialogEndpointParameters/DialogEndpointParametersBlobStorage.vue";
import CyodaDataTablesDraggable
  from "@cyoda/ui-lib/src/components-library/elements/CyodaDataTables/CyodaDataTablesDraggable.vue";
import {ElMessageBox} from "element-plus";

const props = defineProps({
  parameters: {
    default: function () {
      return [];
    }
  }
});
const isExistTemplatesColumn = computed(() => {
  return props.parameters.some((el) => el.templateValue);
});

const dialogEndpointParametersBlobStorageRef = ref(null);

function addNewParameter() {
  dialogEndpointParametersBlobStorageRef.value.openDialogAndCreateNew();
}

function onEditParameter(row: BlobStorageParameterDto) {
  dialogEndpointParametersBlobStorageRef.value.openDialogAndEditRecord(row);
}

function onDeleteParameter(row: BlobStorageParameterDto) {
  ElMessageBox.confirm("Do you really want to remove parameter?", "Confirm!", {
    callback: async (action) => {
      if (action === "confirm") {
        const index = props.parameters.indexOf(row);
        if (index !== -1) {
          props.parameters.splice(index, 1);
        }
      }
    }
  });
}
</script>

<style lang="scss">
.http-parameters {
  .endpoint-actions {
    margin-bottom: 10px;
    text-align: right;
  }
}
</style>
