// packages/processing-manager-react/src/components/state-machine/TransitionStateMachineTimeLine.tsx
/**
 * Transition State Machine Timeline Component
 * Migrated from @cyoda/processing-manager/src/components/PmTransitionStateMachine/TransitionStateMachineTimeLine.vue
 */

import React, { useMemo } from 'react';
import { Card, Timeline } from 'antd';

interface EntityVersion {
  state: string;
  date: string;
}

interface TransitionStateMachineTimeLineProps {
  entityVersions: EntityVersion[];
}

export const TransitionStateMachineTimeLine: React.FC<TransitionStateMachineTimeLineProps> = ({
  entityVersions = [],
}) => {
  const activities = useMemo(() => {
    return entityVersions.map((el) => ({
      content: el.state,
      timestamp: el.date,
    }));
  }, [entityVersions]);

  return (
    <Card title="Time Line">
      <Timeline>
        {activities.map((activity, index) => (
          <Timeline.Item key={index} label={activity.timestamp}>
            {activity.content}
          </Timeline.Item>
        ))}
      </Timeline>
    </Card>
  );
};

export default TransitionStateMachineTimeLine;

// .old_project /packages/processing-manager/src/components/PmTransitionStateMachine/TransitionStateMachineTimeLine.vue
<template>
  <div class="card">
    <div class="card-header">Time Line</div>
    <div class="card-body">
      <el-timeline>
        <el-timeline-item v-for="(activity, index) in activities" :key="index" :timestamp="activity.timestamp">
          {{ activity.content }}
        </el-timeline-item>
      </el-timeline>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";

const props = defineProps({ entityVersions: { default: () => [] } });
const activities = computed(() => {
  return props.entityVersions.map((el) => ({
    content: el.state,
    timestamp: el.date
  }));
});
</script>
